### ISSUE TITLE
LSan: iocore/cache unit tests are failed with --enable-asan

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#10008]
```
PASS: test_Cache
PASS: test_RWW
PASS: test_Alternate_L_to_S
PASS: test_Alternate_S_to_L
FAIL: test_Alternate_L_to_S_remove_L
FAIL: test_Alternate_L_to_S_remove_S
FAIL: test_Alternate_S_to_L_remove_S
FAIL: test_Alternate_S_to_L_remove_L
PASS: test_Update_L_to_S
PASS: test_Update_S_to_L
PASS: test_Update_header
make[3]: Entering directory `/home/masaori/src/trafficserver-asf-master/iocore/cache'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/masaori/src/trafficserver-asf-master/iocore/cache'
============================================================================
Testsuite summary for Apache Traffic Server 10.0.0
============================================================================
# TOTAL: 11
# PASS:  7
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0
============================================================================
See iocore/cache/test-suite.log
Please report to dev@trafficserver.apache.org
============================================================================
```

```
===============================================================================
All tests passed (10296 assertions in 1 test case)


=================================================================
==30017==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 824 byte(s) in 1 object(s) allocated from:
    #0 0x55a1598251fd in operator new(unsigned long) /workspace/build/rpmbuild/BUILD/llvm-14.0.3/llvm-project-llvmorg-14.0.3/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0x55a1599b8305 in CacheAltReadAgain::CacheAltReadAgain(unsigned long, char const*) /home/masaori/src/trafficserver-asf-master/iocore/cache/./test/test_Alternate_L_to_S_remove_L.cc:98:24
    #2 0x55a1599b5f73 in CacheAltInit::cache_init_success_callback(int, void*) /home/masaori/src/trafficserver-asf-master/iocore/cache/./test/test_Alternate_L_to_S_remove_L.cc:238:44
    #3 0x55a1599b79dd in CacheInit::start_event(int, void*) /home/masaori/src/trafficserver-asf-master/iocore/cache/./test/main.h:80:11
    #4 0x55a1599b73a1 in Continuation::handleEvent(int, void*) /home/masaori/src/trafficserver-asf-master/iocore/eventsystem/I_Continuation.h:228:12
    #5 0x55a1599b73a1 in CacheInit::init_event(int, void*) /home/masaori/src/trafficserver-asf-master/iocore/cache/./test/main.h:94:15
    #6 0x55a15a14d47f in Continuation::handleEvent(int, void*) /home/masaori/src/trafficserver-asf-master/iocore/eventsystem/./I_Continuation.h:228:12
    #7 0x55a15a14d47f in EThread::process_event(Event*, int) /home/masaori/src/trafficserver-asf-master/iocore/eventsystem/UnixEThread.cc:149:22
    #8 0x55a15a14f9b9 in EThread::execute_regular() /home/masaori/src/trafficserver-asf-master/iocore/eventsystem/UnixEThread.cc:255:11
    #9 0x55a15a151666 in EThread::execute() /home/masaori/src/trafficserver-asf-master/iocore/eventsystem/UnixEThread.cc:334:11
    #10 0x55a159870b9e in Catch::TestCase::invoke() const /home/masaori/src/trafficserver-asf-master/lib/catch2/catch.hpp:14167:15
    #11 0x55a159870b9e in Catch::RunContext::invokeActiveTestCase() /home/masaori/src/trafficserver-asf-master/lib/catch2/catch.hpp:13027:27
    #12 0x55a159870b9e in Catch::RunContext::runCurrentTest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /home/masaori/src/trafficserver-asf-master/lib/catch2/catch.hpp:13000:17
    #13 0x55a15986e8c8 in Catch::RunContext::runTest(Catch::TestCase const&) /home/masaori/src/trafficserver-asf-master/lib/catch2/catch.hpp:12761:13
    #14 0x55a159880373 in Catch::(anonymous namespace)::TestGroup::execute() /home/masaori/src/trafficserver-asf-master/lib/catch2/catch.hpp:13354:45
    #15 0x55a159880373 in Catch::Session::runInternal() /home/masaori/src/trafficserver-asf-master/lib/catch2/catch.hpp:13560:39
    #16 0x55a15987da43 in Catch::Session::run() /home/masaori/src/trafficserver-asf-master/lib/catch2/catch.hpp:13516:24
    #17 0x55a1598ce979 in int Catch::Session::run<char>(int, char const* const*) /home/masaori/src/trafficserver-asf-master/lib/catch2/catch.hpp:13238:30
    #18 0x55a1598ce979 in main /home/masaori/src/trafficserver-asf-master/lib/catch2/catch.hpp:17533:29
    #19 0x7fc5251cb554 in __libc_start_main (/lib64/libc.so.6+0x22554) (BuildId: a317b42b15368adcae21c11107691a03ec91059d)

SUMMARY: AddressSanitizer: 824 byte(s) leaked in 1 allocation(s).
```

**Comment by masaori335** [comment]
We don't have any ci job with ASan?

**Comment by bneradt** [comment]
> We don't have any ci job with ASan?

Not yet. We'd like to add asan and tsan eventually.
