### ISSUE TITLE
H3 request causing crash

### ISSUE THREAD

**Issue by duke8253** [apache/trafficserver#10636]
This crash started happening #10596 

Running ats with generator plugin. The command I used for the request: 
`curl https://127.0.0.1:9090/cache/1024 -v -k --proxy-insecure --http3-only` 

```
#0  0x00007ffff5db5acf in raise () from /lib64/libc.so.6
#1  0x00007ffff5d88ea5 in abort () from /lib64/libc.so.6
#2  0x00007ffff72e6114 in CRYPTO_set_ex_data (ad=<optimized out>, index=-1, val=<optimized out>) at /tmp/tmp.ZhfxSaVmaB/boringssl/crypto/ex_data.c:178
#3  0x0000000000879962 in QUICPacketHandlerIn::_recv_packet (this=<optimized out>, event=<optimized out>, udp_packet=0x7fffe4ce5f50) at ../../../iocore/net/QUICPacketHandler_quiche.cc:304
#4  0x00000000008783bf in QUICPacketHandlerIn::acceptEvent (this=0x7ffff5925300, event=<optimized out>, data=0x7fffe5afd610) at ../../../iocore/net/QUICPacketHandler_quiche.cc:148
#5  0x0000000000860df2 in Continuation::handleEvent (data=0x7fffe5afd610, event=210, this=0x7ffff5925300) at /home/feid/git/duke-ats/_build/../iocore/eventsystem/I_Continuation.h:228
#6  Continuation::handleEvent (data=0x7fffe5afd610, event=210, this=0x7ffff5925300) at /home/feid/git/duke-ats/_build/../iocore/eventsystem/I_Continuation.h:224
#7  UnixUDPConnection::callbackHandler (this=this@entry=0x7fffe4bc4000, event=event@entry=0, data=data@entry=0x0) at ../../../iocore/net/UnixUDPConnection.cc:96
#8  0x000000000086a6a4 in UDPNetProcessorInternal::udp_callback (this=0xbd43c0 <udpNetInternal>, nh=0x7fffe96ff9b0, thread=0x7fffe96fde00, xuc=0x7fffe4bc4000) at ../../../iocore/net/UnixUDPNet.cc:676
#9  UDPNetHandler::waitForActivity (this=0x7fffe96ff9b0, timeout=<optimized out>) at ../../../iocore/net/UnixUDPNet.cc:1809
#10 0x0000000000966d95 in EThread::execute_regular (this=this@entry=0x7fffe96fde00) at ../../../iocore/eventsystem/UnixEThread.cc:285
#11 0x0000000000966f71 in EThread::execute (this=0x7fffe96fde00) at ../../../iocore/eventsystem/UnixEThread.cc:334
#12 EThread::execute (this=0x7fffe96fde00) at ../../../iocore/eventsystem/UnixEThread.cc:312
#13 0x00000000009648b2 in spawn_thread_internal (a=0x7ffff5900240) at ../../../iocore/eventsystem/Thread.cc:78
#14 0x00007ffff6d931ca in start_thread () from /lib64/libpthread.so.0
#15 0x00007ffff5da0e73 in clone () from /lib64/libc.so.6
```

**Comment by Karthikdasari0423** [comment]
Hi @duke8253 

Could you please confirm did you use the same steps mentioned in https://github.com/apache/trafficserver/wiki/HTTP-3-Documentation
I have tried above steps and facing below issue https://github.com/apache/trafficserver/issues/10660 

So just wondering how did you built ATS with QUIC

**Comment by duke8253** [comment]
@Karthikdasari0423 you'll need to run this, https://github.com/apache/trafficserver/blob/master/tools/build_h3_tools.sh

**Comment by Karthikdasari0423** [comment]
@duke8253  yes,i tried to install using below url but failed https://github.com/apache/trafficserver/wiki/HTTP-3-Documentation
