### ISSUE TITLE
Possibly crasher in HostDB serialization (disk sync)

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#1322]
Hi Thomas,

we're seeing this odd looking crash, fairly often:

```
#0  0x00002aaaad74337d in __libc_waitpid (pid=<optimized out>, stat_loc=<optimized out>, options=<optimized out>)
    at ../sysdeps/unix/sysv/linux/waitpid.c:41
#1  0x00002aaaaab83297 in crash_logger_invoke (signo=11, info=0x2aaaf20007f0, ctx=0x2aaaf20006c0) at Crash.cc:164
#2  <signal handler called>
#3  0x0000000000000000 in ?? ()
#4  0x00002aaaaaf06270 in Continuation::handleEvent (data=0x2ae608f1b140, event=1, this=<optimized out>) at I_Continuation.h:153
#5  EThread::process_event (this=0x2aaaf1c0da00, e=0x2ae608f1b140, calling_code=1) at UnixEThread.cc:143
#6  0x00002aaaaaf0727f in EThread::execute (this=0x2aaaf1c0da00) at UnixEThread.cc:197
#7  0x00002aaaaaf05ba6 in spawn_thread_internal (a=0x2aaac51fccc0) at Thread.cc:84
#8  0x00002aaaad73baa1 in start_thread (arg=0x2aaaf2001700) at pthread_create.c:301
#9  0x00002aaaae5f293d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115
```

Not particularly helpful, I know, but in frame #4, Randal found that the data seems related to the serialization continuation:

```
(gdb) frame 4
#4  0x00002aaaaaf06270 in Continuation::handleEvent (data=0x2ae608f1b140, event=1, this=<optimized out>) at I_Continuation.h:153
153	I_Continuation.h: No such file or directory.
(gdb) print *((Event*)data).continuation
$1 = {<force_VFPT_to_top> = {_vptr.force_VFPT_to_top = 0x2aaaab1d9670 <vtable for RefCountCacheSerializer<RefCountCache<HostDBInfo> >+16>},
  handler = (int (Continuation::*)(Continuation * const, int,
    void *)) 0x2aaaaadcf7a0 <RefCountCacheSerializer<RefCountCache<HostDBInfo> >::initialize_storage(int, Event*)>, mutex = {
    m_ptr = 0x2aaaf0e46e40}, link = {<SLink<Continuation>> = {next = 0x0}, prev = 0x0}, control_flags = {raw_flags = 0}}
```

We're thinking of turning off HostDB sync again to see if that helps, but let me know if you have any brilliant ideas as to why this would fail here (unfortunately the above is all we got :-/).

**Comment by SolidWallOfCode** [comment]
Sounds like the continuation itself was deleted or not yet set up. Had these machines been running for a while or was this relatively soon after process start?

**Comment by zwoop** [comment]
Pretty sure they had been running for a while (several days at least), but let me check.

**Comment by randall** [comment]
It's been a mix. One host crashed nearly after startup, but the others have been many many hours after startup (13 hours to 3 days).

**Comment by zwoop** [comment]
Closing this for now.

**Comment by zizhong** [comment]
Looks like #1020 fixed this issue.
