### ISSUE TITLE
Core dump in SSLAccept / SSLNetVConnection::sslServerHandShakeEvent

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#1326]
We (@randall) ran into an odd crashes that seems fairly similar (but not identical) to https://issues.apache.org/jira/browse/TS-4363. Since Jira is now read-only, I'm opening this up here as a new Issue (but, odds are that this is the same as the TS-4363 issue).

Backtrace:

```
#0  0x00002aaaad74437d in __libc_waitpid (pid=<optimized out>, stat_loc=<optimized out>, options=<optimized out>)
    at ../sysdeps/unix/sysv/linux/waitpid.c:41
#1  0x00002aaaaab83297 in crash_logger_invoke (signo=11, info=0x2aaab610a8f0, ctx=0x2aaab610a7c0) at Crash.cc:164
#2  <signal handler called>
#3  0x00002aaaac715005 in ?? () from /opt/bazinga/lib/libcrypto.so.10
#4  0x00002aaaac7155cc in lh_retrieve () from /opt/bazinga/lib/libcrypto.so.10
#5  0x00002aaaac672c6f in ?? () from /opt/bazinga/lib/libcrypto.so.10
#6  0x00002aaaac67369b in ?? () from /opt/bazinga/lib/libcrypto.so.10
#7  0x00002aaaac700247 in DH_new_method () from /opt/bazinga/lib/libcrypto.so.10
#8  0x00002aaaac70170e in DHparams_dup () from /opt/bazinga/lib/libcrypto.so.10
#9  0x00002aaaac3d717a in ssl_cert_dup () from /opt/bazinga/lib/libssl.so.10
#10 0x00002aaaac3d56a4 in SSL_set_SSL_CTX () from /opt/bazinga/lib/libssl.so.10
#11 0x00002aaaaaea3724 in set_context_cert (ssl=ssl@entry=0x2aea13f9f800) at SSLUtils.cc:361
#12 0x00002aaaaaea3ad6 in ssl_cert_callback (ssl=0x2aea13f9f800) at SSLUtils.cc:398
#13 0x00002aaaac3abd40 in ssl3_get_client_hello () from /opt/bazinga/lib/libssl.so.10
#14 0x00002aaaac3b0f3f in ssl3_accept () from /opt/bazinga/lib/libssl.so.10
#15 0x00002aaaac3c0230 in ssl23_accept () from /opt/bazinga/lib/libssl.so.10
#16 0x00002aaaaaeaa383 in SSLAccept (ssl=0x2aea13f9f800) at SSLUtils.cc:2265
#17 0x00002aaaaae97a4f in SSLNetVConnection::sslServerHandShakeEvent (this=this@entry=0x2aea3b4c23e0, err=@0x2aaab610b980: 0)
    at SSLNetVConnection.cc:1068
#18 0x00002aaaaae9a058 in SSLNetVConnection::sslServerHandShakeEvent (this=0x2aea3b4c23e0, err=<optimized out>) at SSLNetVConnection.cc:1014
#19 0x00002aaaaae9a4c9 in SSLNetVConnection::sslStartHandShake (this=0x2aea3b4c23e0, event=<optimized out>, err=@0x2aaab610b980: 0)
    at SSLNetVConnection.cc:979
#20 0x00002aaaaae9cfc3 in SSLNetVConnection::net_read_io (this=0x2aea3b4c23e0, nh=0x2aaab30116f0, lthread=0x2aaab300d9c0) at SSLNetVConnection.cc:451
#21 0x00002aaaaaeaf254 in NetHandler::mainNetEvent (this=0x2aaab30116f0, event=<optimized out>, e=<optimized out>) at UnixNet.cc:526
#22 0x00002aaaaaf0758e in Continuation::handleEvent (data=0x2aaab17893a0, event=5, this=<optimized out>) at I_Continuation.h:153
#23 EThread::process_event (calling_code=5, e=0x2aaab17893a0, this=0x2aaab300d9c0) at UnixEThread.cc:143
#24 EThread::execute (this=0x2aaab300d9c0) at UnixEThread.cc:270
#25 0x00002aaaaaf06136 in spawn_thread_internal (a=0x2aaab0998460) at Thread.cc:84
#26 0x00002aaaad73caa1 in start_thread (arg=0x2aaab610c700) at pthread_create.c:301
#27 0x00002aaaae5f393d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115
```

I'm curious if @oknet recognizes this as well? This is running v7.0.0, with a small number of cherry picks:

```
* 0412dec (HEAD -> 7.0.x, origin/7.0.x) TS-5102 parent metrics
* cd53220 Fix for: TS-5108-SSL requests might stall because enabled write is ignored
* d908dc0 TS-5069: Fixes CID 1366771 and 1366771
* c95d0ff TS-5076: Test and set the in_enabled_list by atomic function
* 486cc02 TS-4429: Fixes missing curly brackets with new option
* eff5595 TS-4429: Adds a --concise (-C) option for logstats, excludes % metrics
```

**Comment by oknet** [comment]
I only saw the TS-4363 once and can not repeat it. How about your issue ? Is it repeatable ?

**Comment by zwoop** [comment]
Closing this for now.
