### ISSUE TITLE
Crash in InactivityCop::check_inactivity with dead HttpSM, ATS 6.2.1

### ISSUE THREAD

**Issue by jaaju** [apache/trafficserver#1402]
We are seeing this crash in ATS 6.2.1, with http/2 enabled:

```
Program terminated with signal 6, Aborted.
#0  0x00002b4d32759625 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00002b4d32759625 in raise () from /lib64/libc.so.6
#1  0x00002b4d3275ad8d in abort () from /lib64/libc.so.6
#2  0x00002b4d2fd314f3 in ink_die_die_die (fmt=0x2b4d2fd3ddd0 "%s:%d: failed assert `%s`", ap=0x2b4d384ffa40) at ink_error.cc:43
#3  ink_fatal_va(const char *, typedef __va_list_tag __va_list_tag *) (fmt=0x2b4d2fd3ddd0 "%s:%d: failed assert `%s`", ap=0x2b4d384ffa40) at ink_error.cc:65
#4  0x00002b4d2fd3158d in ink_fatal (message_format=0x11b0 <Address 0x11b0 out of bounds>) at ink_error.cc:73
#5  0x00002b4d2fd2ef35 in _ink_assert (expression=0xffffffffffffffff <Address 0xffffffffffffffff out of bounds>, file=0x13f6 <Address 0x13f6 out of bounds>, line=6) at ink_assert.cc:37
#6  0x00000000005a3cd2 in HttpSM::main_handler (this=0x2b4d42cad580, event=105, data=0x2b4d9b996438) at HttpSM.cc:2818
#7  0x00000000007267e9 in handleEvent (event=<value optimized out>, vc=0x2b4d9b996320) at ../../iocore/eventsystem/I_Continuation.h:153
#8  read_signal_and_update (event=<value optimized out>, vc=0x2b4d9b996320) at UnixNetVConnection.cc:148
#9  0x0000000000729ddf in UnixNetVConnection::mainEvent (this=0x2b4d9b996320, event=<value optimized out>, e=<value optimized out>) at UnixNetVConnection.cc:1205
#10 0x000000000071f921 in handleEvent (this=0x2b4d34b1b440, event=<value optimized out>, e=0x2b4d35756ca0) at ../../iocore/eventsystem/I_Continuation.h:153
#11 InactivityCop::check_inactivity (this=0x2b4d34b1b440, event=<value optimized out>, e=0x2b4d35756ca0) at UnixNet.cc:102
#12 0x0000000000749f1d in handleEvent (this=0x2b4d35507000, e=0x2b4d35756ca0, calling_code=2) at I_Continuation.h:153
#13 EThread::process_event (this=0x2b4d35507000, e=0x2b4d35756ca0, calling_code=2) at UnixEThread.cc:148
#14 0x000000000074aa43 in EThread::execute (this=0x2b4d35507000) at UnixEThread.cc:230
#15 0x000000000074935a in spawn_thread_internal (a=0x2b4d34b176d0) at Thread.cc:86
#16 0x00002b4d32ac29d1 in start_thread () from /lib64/libpthread.so.0
#17 0x00002b4d3280f9dd in clone () from /lib64/libc.so.6
(gdb) f 6
#6  0x00000000005a3cd2 in HttpSM::main_handler (this=0x2b4d42cad580, event=105, data=0x2b4d9b996438) at HttpSM.cc:2818
2818	HttpSM.cc: No such file or directory.
	in HttpSM.cc
(gdb) p/x magic
$1 = 0xdeadfeed
```

**Comment by zwoop** [comment]
If possible, can you test with 7.0 or 7.1x (branch) and see if it happens there too ?

**Comment by jaaju** [comment]
@zwoop , we are seeing this issue only in our production env and our synthetic tests and internal deployments do not have the issue. Also, we are in the process of upgrading from ATS 5 to ATS 6, and so can not quickly deploy 7 to a prod env.

I will continue to get a local repro, and will update the issue if that is possible. Meanwhile, wanted to post here to see if others have run into this, or if there have been changes to this feature recently.

Thanks!

**Comment by bryancall** [comment]
If this is still an issue please reopen.
