### ISSUE TITLE
ASAN issue in traffic_manager metrics Lua bindings

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#1475]
```
root@qa1 616/1 # /opt/ats/bin/traffic_manager
[E. Mgmt] log ==> [TrafficManager] using root directory '/opt/ats'
=================================================================
==28535==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffcbd4055f8 at pc 0x7f9fc9430d1f bp 0x7ffcbd405080 sp 0x7ffcbd404828
READ of size 8 at 0x7ffcbd4055f8 thread T0
    #0 0x7f9fc9430d1e  (/lib64/libasan.so.3+0x5ed1e)
    #1 0x7f9fc6ffd31e  (/lib64/libgcc_s.so.1+0xd31e)
    #2 0x7f9fc6fffcaa in _Unwind_RaiseException (/lib64/libgcc_s.so.1+0xfcaa)
    #3 0x54c7be in err_raise_ext /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:304
    #4 0x54c7be in lj_err_throw /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:458
    #5 0x54cad9 in lj_err_run /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:567
    #6 0x54cbf0 in err_msgv /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:580
    #7 0x54cd4a in lj_err_optype /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:614
    #8 0x5688f8 in lj_meta_tget /usr/local/src/trafficserver/lib/luajit/src/lj_meta.c:138
    #9 0x563fe3 in lj_vmeta_tgetv (/opt/ats/bin/traffic_manager+0x563fe3)
    #10 0x552dc3 in lua_pcall /usr/local/src/trafficserver/lib/luajit/src/lj_api.c:1052
    #11 0x44bb9c in Evaluator::eval(lua_State*) const /usr/local/src/trafficserver/cmd/traffic_manager/metrics.cc:84
    #12 0x44c2cf in EvaluatorList::evaluate(lua_State*) const /usr/local/src/trafficserver/cmd/traffic_manager/metrics.cc:150
    #13 0x44b4d4 in metrics_binding_evaluate(BindingInstance&) /usr/local/src/trafficserver/cmd/traffic_manager/metrics.cc:382
    #14 0x448fe5 in main /usr/local/src/trafficserver/cmd/traffic_manager/traffic_manager.cc:772
    #15 0x7f9fc6c50b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)
    #16 0x440767  (/opt/ats/bin/traffic_manager+0x440767)

Address 0x7ffcbd4055f8 is located in stack of thread T0==28535==AddressSanitizer CHECK failed: ../../../../libsanitizer/asan/asan_thread.cc:243 "((ptr[0] == kCurrentStackFrameMagic)) != (0)" (0x0, 0x0)
    #0 0x7f9fc94a27ba  (/lib64/libasan.so.3+0xd07ba)
    #1 0x7f9fc94a9173 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/lib64/libasan.so.3+0xd7173)
    #2 0x7f9fc94a6db1  (/lib64/libasan.so.3+0xd4db1)
    #3 0x7f9fc949e1ea  (/lib64/libasan.so.3+0xcc1ea)
    #4 0x7f9fc949e7ba  (/lib64/libasan.so.3+0xcc7ba)
    #5 0x7f9fc94a1c19  (/lib64/libasan.so.3+0xcfc19)
    #6 0x7f9fc9430d3d  (/lib64/libasan.so.3+0x5ed3d)
    #7 0x7f9fc6ffd31e  (/lib64/libgcc_s.so.1+0xd31e)
    #8 0x7f9fc6fffcaa in _Unwind_RaiseException (/lib64/libgcc_s.so.1+0xfcaa)
    #9 0x54c7be in err_raise_ext /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:304
    #10 0x54c7be in lj_err_throw /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:458
    #11 0x54cad9 in lj_err_run /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:567
    #12 0x54cbf0 in err_msgv /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:580
    #13 0x54cd4a in lj_err_optype /usr/local/src/trafficserver/lib/luajit/src/lj_err.c:614
    #14 0x5688f8 in lj_meta_tget /usr/local/src/trafficserver/lib/luajit/src/lj_meta.c:138
    #15 0x563fe3 in lj_vmeta_tgetv (/opt/ats/bin/traffic_manager+0x563fe3)
    #16 0x552dc3 in lua_pcall /usr/local/src/trafficserver/lib/luajit/src/lj_api.c:1052
    #17 0x44bb9c in Evaluator::eval(lua_State*) const /usr/local/src/trafficserver/cmd/traffic_manager/metrics.cc:84
    #18 0x44c2cf in EvaluatorList::evaluate(lua_State*) const /usr/local/src/trafficserver/cmd/traffic_manager/metrics.cc:150
    #19 0x44b4d4 in metrics_binding_evaluate(BindingInstance&) /usr/local/src/trafficserver/cmd/traffic_manager/metrics.cc:382
    #20 0x448fe5 in main /usr/local/src/trafficserver/cmd/traffic_manager/traffic_manager.cc:772
    #21 0x7f9fc6c50b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)
    #22 0x440767  (/opt/ats/bin/traffic_manager+0x440767)
```

**Comment by jpeach** [comment]
Check the verbose log to ensure that Lua was excluded from ASAN correctly.

**Comment by zwoop** [comment]
Invalid, I have no idea what the compilers are doing, and devtoolset-6 hate me.
