### ISSUE TITLE
Crash in Http1ClientSession::set_inactivity_timeout

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#1480]
While testing 7.1, we see the following crash and stack track

```
#0  0x0000000000000000 in ?? ()
#1  0x00000000005d6794 in Http1ClientSession::set_inactivity_timeout (this=0x2ad091121980, timeout_in=30000000000)
    at Http1ClientSession.h:161
#2  0x00000000005d71d1 in Http1ClientTransaction::set_inactivity_timeout (this=0x2ad091121c60, timeout_in=30000000000)
    at Http1ClientTransaction.h:156
#3  0x00000000005f56b5 in HttpSM::do_setup_post_tunnel (this=0x2ad0c06a35f0, to_vc_type=HTTP_SERVER_VC)
    at HttpSM.cc:5726
#4  0x00000000005e7b30 in HttpSM::state_send_server_request_header (this=0x2ad0c06a35f0, event=103, 
    data=0x2ad048ebed40) at HttpSM.cc:2001
#5  0x00000000005ea331 in HttpSM::main_handler (this=0x2ad0c06a35f0, event=103, data=0x2ad048ebed40) at HttpSM.cc:2662
#6  0x00000000005160f2 in Continuation::handleEvent (this=0x2ad0c06a35f0, event=103, data=0x2ad048ebed40)
    at /home/shinrich/yats_build/trafficserver/iocore/eventsystem/I_Continuation.h:153
#7  0x0000000000784a70 in write_signal_and_update (event=103, vc=0x2ad048ebebb0) at UnixNetVConnection.cc:176
#8  0x0000000000784c76 in write_signal_done (event=103, nh=0x2ad01ce11e60, vc=0x2ad048ebebb0)
    at UnixNetVConnection.cc:218
#9  0x0000000000785f09 in write_to_net_io (nh=0x2ad01ce11e60, vc=0x2ad048ebebb0, thread=0x2ad01ce0e010)
    at UnixNetVConnection.cc:596
#10 0x0000000000785724 in write_to_net (nh=0x2ad01ce11e60, vc=0x2ad048ebebb0, thread=0x2ad01ce0e010)
    at UnixNetVConnection.cc:430
#11 0x000000000077d30d in NetHandler::mainNetEvent (this=0x2ad01ce11e60, event=5, e=0x13863a0) at UnixNet.cc:526
#12 0x00000000005160f2 in Continuation::handleEvent (this=0x2ad01ce11e60, event=5, data=0x13863a0)
    at /home/shinrich/yats_build/trafficserver/iocore/eventsystem/I_Continuation.h:153
#13 0x00000000007a69c5 in EThread::process_event (this=0x2ad01ce0e010, e=0x13863a0, calling_code=5)
    at UnixEThread.cc:143
#14 0x00000000007a6eb1 in EThread::execute (this=0x2ad01ce0e010) at UnixEThread.cc:270
#15 0x00000000007a6089 in spawn_thread_internal (a=0x1272fe0) at Thread.cc:84
#16 0x00002ad016cafaa1 in start_thread () from /lib64/libpthread.so.0
#17 0x00002ad0169fc93d in clone () from /lib64/libc.so.6
```

I assume that the compiler has inlined the call to client_vc->set_inactivity_timeout(timeout_in) and the crash is someplace in the UnitNetVConnection::set_inactivity_timeout function.  client_vc is non-null and appears ok.

**Comment by shinrich** [comment]
I think this is the same underlying issue as issue #1476.  Another case of calling a virtual method into a VC.

**Comment by shinrich** [comment]
As issue #1476 is resolved, so is this one.
