### ISSUE TITLE
ASAN segv when ramping up traffic to a production host

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#1523]
```
ASAN:SIGSEGV
=================================================================
==38732==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x2abf141497c0 sp 0x2abf141496a8 T23)
==38732==Hint: pc points to the zero page.

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 ??
Thread T23 ([ET_NET 21]) created by T0 ([TS_MAIN]) here:
    #0 0x528ed4 in __interceptor_pthread_create (/home/y/bin64/traffic_server+0x528ed4)
    #1 0xb3e984 in ink_thread_create /home/bcall/dev/yahoo/build/_build/asan_build/../../trafficserver/lib/ts/ink_thread.h:152
    #2 0xb3ef5a in Thread::start(char const*, unsigned long, void* (*)(void*), void*, void*) ../../../../trafficserver/iocore/eventsystem/Thread.cc:102
    #3 0xb447d9 in EventProcessor::start(int, unsigned long) ../../../../trafficserver/iocore/eventsystem/UnixEventProcessor.cc:240
    #4 0x654afe in main ../../../trafficserver/proxy/Main.cc:1771
    #5 0x2abf0cdadd1c in __libc_start_main (/lib64/libc.so.6+0x1ed1c)

==38732==ABORTING
```

**Comment by bryancall** [comment]
Need to run an asan build in production again.  Closing for now.
