### ISSUE TITLE
New crash/hang after commit  daea3d765

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#1861]
After this commit, the docs.trafficserver is working ok, but ci.trafficserver either hangs, or sometimes, creates an assertion. I see

```
#0  0x00002b5d2f2bf1d7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 4846
        selftid = 4851
#1  0x00002b5d2f2c0a08 in __GI_abort () at abort.c:119
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {18446744073709551615 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00002b5d2d221b23 in ink_abort (message_format=0x2b5d2d244470 "%s:%d: failed assertion `%s`") at ink_error.cc:99
        ap = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x2aaaab3fe920, reg_save_area = 0x2aaaab3fe860}}
#3  0x00002b5d2d21ed97 in _ink_assert (expression=0x8b2a21 "p->read_success == true", file=0x8b1334 "HttpSM.cc", line=2640) at ink_assert.cc:37
No locals.
#4  0x00000000006315dd in HttpSM::tunnel_handler_post_or_put (this=0x2b5d33181000, p=0x2b5d33182498) at HttpSM.cc:2640
        c = 0x30888100
#5  0x0000000000631a73 in HttpSM::tunnel_handler_post (this=0x2b5d33181000, event=2301, data=0x2b5d33182290) at HttpSM.cc:2710
        __FUNCTION__ = "tunnel_handler_post"
        p = 0x2b5d33182498
        p_handler_state = 3
#6  0x0000000000631399 in HttpSM::main_handler (this=0x2b5d33181000, event=2301, data=0x2b5d33182290) at HttpSM.cc:2582
        jump_point = NULL
        __FUNCTION__ = "main_handler"
        vc_entry = 0x0
#7  0x0000000000561764 in Continuation::handleEvent (this=0x2b5d33181000, event=2301, data=0x2b5d33182290) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
No locals.
#8  0x0000000000688ff2 in HttpTunnel::main_handler (this=0x2b5d33182290, event=103, data=0x2b5d3302bfa0) at HttpTunnel.cc:1662
        p = 0x0
        c = 0x2b5d331822d8
        sm_callback = true
#9  0x0000000000561764 in Continuation::handleEvent (this=0x2b5d33182290, event=103, data=0x2b5d3302bfa0) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
No locals.
#10 0x00000000007b70df in write_signal_and_update (event=103, vc=0x2b5d3302be00) at UnixNetVConnection.cc:176
        __FUNCTION__ = "write_signal_and_update"
#11 0x00000000007b7316 in write_signal_done (event=103, nh=0x2b5d31a13e80, vc=0x2b5d3302be00) at UnixNetVConnection.cc:218
No locals.
#12 0x00000000007b8934 in write_to_net_io (nh=0x2b5d31a13e80, vc=0x2b5d3302be00, thread=0x2b5d31a10000) at UnixNetVConnection.cc:609
        wbe_event = 0
        e = 855746048
        s = 0x2b5d3302bf98
        mutex = 0x2b5d30ac57f0
        lock = {m = {m_ptr = 0x2b5d33024080}, lock_acquired = true}
        __FUNCTION__ = "write_to_net_io"
        ntodo = 2
        buf = @0x2b5d3302bfc0: {name = 0x0, mbuf = 0x2b5d33035f00, entry = 0x2b5d33035f40}
        towrite = 2
        signalled = 0
        needs = -2147483644
        total_written = 2
        r = 2
#13 0x00000000007b80db in write_to_net (nh=0x2b5d31a13e80, vc=0x2b5d3302be00, thread=0x2b5d31a10000) at UnixNetVConnection.cc:443
        mutex = 0x2b5d30ac57f0
#14 0x00000000007ae252 in NetHandler::mainNetEvent (this=0x2b5d31a13e80, event=5, e=0x2b5d3084a2e0) at UnixNet.cc:526
        epd = 0x2b5d3301a858
        poll_timeout = 30
        pd = 0x2b5d321d0000
        vc = 0x2b5d3302be00
        __FUNCTION__ = "mainNetEvent"
#15 0x0000000000561764 in Continuation::handleEvent (this=0x2b5d31a13e80, event=5, data=0x2b5d3084a2e0) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
No locals.
#16 0x00000000007ddbf0 in EThread::process_event (this=0x2b5d31a10000, e=0x2b5d3084a2e0, calling_code=5) at UnixEThread.cc:129
        c_temp = 0x2b5d31a13e80
        lock = {m = {m_ptr = 0x2b5d30ac6580}, lock_acquired = true}
        __FUNCTION__ = "process_event"
#17 0x00000000007de1d4 in EThread::execute (this=0x2b5d31a10000) at UnixEThread.cc:256
        done_one = false
        e = 0x2b5d3084a2e0
        NegativeQueue = {<DLL<Event, Event::Link_link>> = {head = 0x2b5d34827280}, tail = 0x2b5d34827580}
        next_time = 1494445657603646250
        __FUNCTION__ = "execute"
#18 0x00000000007dd13f in spawn_thread_internal (a=0x2b5d30a716d0) at Thread.cc:91
        p = 0x2b5d30a716d0
#19 0x00002b5d2eb6fdc5 in start_thread (arg=0x2aaaab3ff700) at pthread_create.c:308
        __res = <optimized out>
        pd = 0x2aaaab3ff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {46912505902848, -4783793944411736919, 0, 140727346025600, 46912505902848, 0, -1672565272484219735, -1502282883988556631}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#20 0x00002b5d2f38173d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
No locals.
```

I verified by reverting this commit, and without it, current master works fine.

**Comment by masaori335** [comment]
When POST request is finished, it looks like the state of session go to half-close. So every request after the first request get GOAWAY frame:(

### GET
```
[May 11 08:38:05.034] Server {0xb0006000} DEBUG: <Http2ConnectionState.cc:1332 (send_data_frames)> (http2_cs) Shutdown stream 1
[May 11 08:38:05.034] Server {0xb0006000} DEBUG: <Http2ConnectionState.cc:1110 (delete_stream)> (http2_con) [0] [1] Delete stream
[May 11 08:38:05.034] Server {0xb0006000} DEBUG: <Http2Stream.cc:378 (initiating_close)> (http2_stream) initiating_close stream 1
[May 11 08:38:05.034] Server {0xb0006000} DEBUG: <Http2Stream.cc:406 (initiating_close)> (http2_stream) handle write from destroy stream=1 event=103
[May 11 08:38:05.034] Server {0xb0006000} DEBUG: <Http2Stream.cc:615 (update_write_request)> (http2_stream) write update stream_id=1 event=103
[May 11 08:38:05.034] Server {0xb0006000} DEBUG: <Http2Stream.cc:325 (do_io_close)> (http2_stream) do_io_close stream 1
```

### POST
```
[May 11 08:35:59.745] Server {0xb0008000} DEBUG: <Http2ConnectionState.cc:1332 (send_data_frames)> (http2_cs) Shutdown stream 1
[May 11 08:35:59.745] Server {0xb0008000} DEBUG: <Http2ConnectionState.cc:1110 (delete_stream)> (http2_con) [1] [1] Delete stream
[May 11 08:35:59.745] Server {0xb0008000} DEBUG: <Http2Stream.cc:378 (initiating_close)> (http2_stream) initiating_close stream 1
[May 11 08:35:59.745] Server {0xb0008000} DEBUG: <Http2Stream.cc:406 (initiating_close)> (http2_stream) handle write from destroy stream=1 event=103
[May 11 08:35:59.745] Server {0xb0008000} DEBUG: <Http2Stream.cc:615 (update_write_request)> (http2_stream) write update stream_id=1 event=103
[May 11 08:35:59.745] Server {0xb0008000} DEBUG: <Http2ClientSession.cc:282 (set_half_close_flag)> (http2_cs) [1] session half-close
[May 11 08:35:59.745] Server {0xb0008000} DEBUG: <Http2Stream.cc:325 (do_io_close)> (http2_stream) do_io_close stream 1
```
