### ISSUE TITLE
Configuration reload on master is crashing when built with ASAN

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#2157]
```
ASAN:DEADLYSIGNAL
=================================================================
==8629==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f65e41d6780 bp 0x000000000000 sp 0x7ffec2b0e5f8 T0)
    #0 0x7f65e41d677f  (/lib64/libtcl8.5.so+0x8677f)
    #1 0x7f65e41d68db  (/lib64/libtcl8.5.so+0x868db)
    #2 0x7f65e473d50f in ink_hash_table_lookup_entry /usr/local/src/trafficserver/lib/ts/ink_hash_table.cc:219
    #3 0x7f65e473d3dc in ink_hash_table_lookup /usr/local/src/trafficserver/lib/ts/ink_hash_table.cc:162
    #4 0x5c94ac in FileManager::getRollbackObj(char const*, Rollback**) /usr/local/src/trafficserver/mgmt/FileManager.cc:165
    #5 0x5d0d0d in LocalManager::sendMgmtMsgToProcesses(_mgmt_message_hdr_type*) /usr/local/src/trafficserver/mgmt/LocalManager.cc:597
    #6 0x5d1c9b in LocalManager::processEventQueue() /usr/local/src/trafficserver/mgmt/LocalManager.cc:738
    #7 0x586f54 in main /usr/local/src/trafficserver/cmd/traffic_manager/traffic_manager.cc:684
    #8 0x7f65e3047b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)
    #9 0x4a4022  (/opt/ats/bin/traffic_manager+0x4a4022)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libtcl8.5.so+0x8677f)
```

**Comment by bryancall** [comment]
This is reproducible on docs.trafficserver.apache.org.  I wasn't able to reproduce it on my server for master and 7.1.x.

**Comment by zwoop** [comment]
Tested backing out b3adf64e27ee27b209c6bbfdec6fa6be57755340, after which the crashes are gone. So fairly confident this is the culprit. This is also on 7.1.x, so marking this issue as a 7.1.x show-stopper.

**Comment by bryancall** [comment]
Backtrace on core:
```
Thread 1 "traffic_manager" received signal SIGSEGV, Segmentation fault.
HashStringKey (tablePtr=0x6080000095a0, keyPtr=0x0) at /usr/src/debug/tcl8.5.13/generic/tclHash.c:931
931	    for (c=*string++ ; c ; c=*string++) {
#0  HashStringKey (tablePtr=0x6080000095a0, keyPtr=0x0) at /usr/src/debug/tcl8.5.13/generic/tclHash.c:931
        string = 0x0
        result = 0
        c = <optimized out>
#1  0x00007fc0d49678dc in CreateHashEntry (tablePtr=0x6080000095a0, key=0x0, newPtr=0x0) at /usr/src/debug/tcl8.5.13/generic/tclHash.c:303
        hPtr = <optimized out>
        typePtr = 0x7fc0d4c04360 <tclStringHashKeyType>
        hash = <optimized out>
        index = <optimized out>
#2  0x00007fc0d4ece510 in ink_hash_table_lookup_entry (ht_ptr=0x6080000095a0, key=0x0) at ink_hash_table.cc:219
        tcl_ht_ptr = 0x6080000095a0
        tcl_he_ptr = 0x629000021310
        he_ptr = 0x17f9cc0 <g_records_rwlock>
#3  0x00007fc0d4ece3dd in ink_hash_table_lookup (ht_ptr=0x6080000095a0, key=0x0, value_ptr=0x7ffcfaa5d590) at ink_hash_table.cc:162
        he_ptr = 0x7ffcfaa5d540
        value = 0x7ffcfaa5d570
#4  0x00000000005c98dd in FileManager::getRollbackObj (this=0x60b0000186c0, fileName=0x0, rbPtr=0x7ffcfaa5d6d0) at FileManager.cc:165
        lookup = 0x0
        found = 0
#5  0x00000000005d113e in LocalManager::sendMgmtMsgToProcesses (this=0x61600000cf80, mh=0x60600001cb20) at LocalManager.cc:597
        fname = 0x0
        rb = 0x7ffcfaa5d770
        found = true
        data_raw = 0x60600001cb28 "proxy.config.ssl.server.ticket_key.filename"
        rec_type = RECT_CONFIG
#6  0x00000000005d20cc in LocalManager::processEventQueue (this=0x61600000cf80) at LocalManager.cc:738
        mh = 0x60600001cb20
        data_raw = 0x60600001cb28 "proxy.config.ssl.server.ticket_key.filename"
        handled_by_mgmt = false
        __FUNCTION__ = "processEventQueue"
```

**Comment by persiaAziz** [comment]
was able to reproduce this on my machine. Will have PR shortly

**Comment by persiaAziz** [comment]
https://github.com/apache/trafficserver/pull/2158 fixes this issue
