### ISSUE TITLE
Crash in StringView in 7.1.0

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#2211]
Seeing the below. We're working on reproducing traces with a debug build, but wanted to capture this first.

```
#0  0x00007ffff52c794f in __strlen_sse42 () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff7bb9994 in ts::StringView::StringView (this=0x7fffecb08f48, s=0x0) at MemView.cc:33
No locals.
#2  0x0000555555862485 in SSLNetVConnection::map_tls_protocol_to_tag (this=<optimized out>, proto_string=0x0) at SSLNetVConnection.cc:1559
        PREFIX = {_ptr = 0x5555558d835b "TLSv1", _size = 5}
        proto = <error reading variable proto (Cannot access memory at address 0x0)>
#3  0x000055555586259d in SSLNetVConnection::populate_protocol (this=0x7fffd3019d00, results=0x7fffecb08fe0, n=9) at SSLNetVConnection.cc:1585
        retval = 0
#4  0x0000555555744fd4 in HttpTransactHeaders::insert_via_header_in_response (s=0x7fffeadb0a20, header=0x7fffeadb1180) at HttpTransactHeaders.cc:882
        new_via_string = "@\230\332\352\377\177\000\000\300\230\332\352\377\177\000\000\270\300\265\246\000\000\000\000@\221\260\354\001\000\001\000`\236\331\352\377\177\000\000\030\222\260\354\377\177\000\000D\000\000\000\000\000\000\000\360\221\260\354\377\177\000\000@\340#\353\377\177\000\000P\340#\353\377\177\000\000X\340#\353\377\177\000\000\021\000\000\000\000\000\000\000@\340#\353\377\177\000\000P\340#\353\377\177\000\000X\340#\353\377\177\000\000\n\000\000\000\000\000\000\000h\340#\353\377\177\000\000p\340#\353\377\177\000\000@\340#\353\n", '\000' <repeats 11 times>, "@\340#\353\377\177\000\000P\340#\353\377\177\000\000X\340#\353\377\177\000\000\t\000\000\000\000\000\000\000h\340#\353\377\177\000\000"...
        n_proto = 1
        ss = 0x0
        proto_buf = <optimized out>
        via_string = <optimized out>
        via_limit = <optimized out>
        incoming_via = <optimized out>
#5  0x000055555572fd76 in HttpTransact::build_response (s=<optimized out>, base_response=<optimized out>, outgoing_response=<optimized out>, outgoing_version=..., status_code=<optimized out>, reason_phrase=<optimized out>) at HttpTransact.cc:8036
        fields = {{name = 0x0, len = 0, presence = 0}, {name = 0x0, len = 0, presence = 0}, {name = 0x0, len = 0, presence = 0}, {name = 0x0, len = 0, presence = 0}, {name = 0x0, len = 0, presence = 0}}
#6  0x000055555571c91b in HttpTransact::build_response (s=0x7fffeadb0a20, outgoing_response=0x9, outgoing_version=..., status_code=HTTP_STATUS_BAD_GATEWAY, reason_phrase=0x5555558c0212 "internal error - server connection terminated") at HttpTransact.cc:7928
No locals.
#7  HttpTransact::build_error_response (s=0x7fffeadb0a20, status_code=HTTP_STATUS_BAD_GATEWAY, reason_phrase_or_null=<optimized out>, error_body_type=<optimized out>, format=0x0) at HttpTransact.cc:8184
        ap = {{gp_offset = 3971000384, fp_offset = 32767, overflow_arg_area = 0x7fffeadb10d4, reg_save_area = 0x34}}
        body_language = "\001\005\364\216\212\340\200\250W\\\336\352\377\177\000\000\030\000\000\000\060\000\000\000\360\352t\362\377\177\000\000@ޠ\357\377\177\000\000\360\352t\362\377\177\000\000\230g\020VUU\000\000\031\\\336\352\377\177\000\000@\250\260\354\377\177\000\000\071\324|UUU\000\000\231\037\320\323sZ\202o\205\020w\177\326\062\257\323\031\\\336\352\377\177\000\000\035\000\000\000\000\000\000\000\002\000.151.1\021\227\224\006\000\000\000\000\311\360\271\246\377\177\000\000\273\001{UUU", '\000' <repeats 18 times>, "\001\000\000\000\000\000\000\000\320\024\333\352\377\177\000\000\000\000\000\000\000\000\000\000\320\020\333\352\377\177\000\000 \n\333\352\377\177\000\000Բ"...
        body_type = "v\207\213UUU\000\000\360\bu\362\377\177\000\000p\247\260\354\377\177\000\000\256K\206UUU\000\000\320\024\333\352\377\177\000\000\260\247\260\354\377\177\000\000\260\247\260\354\377\177\000\000\000\000\000\000\000\000\000\000\260\247\260\354\377\177\000\000\030\247\260\354\377\177\000\000\000\247\260\354\377\177\000\000\237\263W\366\377\177\000\000\000\000\000\000\000\000\000\000র\354\377\177\000\000 \n\333\352\377\177\000\000\203\071\274\367\377\177\000\000\240\247\260\354\377\177\000\000\237||UUU\000\000\061\000\000\000\000\000\000\000p\232\335\367\377\177\000\000\231\037\320\323sZ\202o\205\020w\177\326\062\257\323\000\001", '\000' <repeats 14 times>, "\360\352t\362\377\177\000\000c\231"...
        url_string = <optimized out>
        reason_phrase = <optimized out>
        len = <optimized out>
        new_msg = <optimized out>
#8  0x00005555557317e3 in HttpTransact::handle_server_died (s=0x7fffeadb0a20) at HttpTransact.cc:7764
        status = HTTP_STATUS_SERVICE_UNAVAILABLE
        body_type = <optimized out>
        reason = <optimized out>
#9  0x0000555555734b40 in HttpTransact::handle_server_connection_not_open (s=0x7fffeadb0a20) at HttpTransact.cc:3956
No locals.
#10 0x0000555555733cba in HttpTransact::handle_response_from_server (s=0x7fffeadb0a20) at HttpTransact.cc:3796
        max_connect_retries = <optimized out>
#11 0x0000555555728a0e in HttpTransact::HandleResponse (s=<optimized out>) at HttpTransact.cc:3355
No locals.
#12 0x000055555570677b in HttpSM::call_transact_and_set_next_state (this=0x7fffeadb09b0, f=<optimized out>) at HttpSM.cc:7234
No locals.
#13 HttpSM::handle_server_setup_error (this=0x7fffeadb09b0, event=105, data=<optimized out>) at HttpSM.cc:5618
No locals.
#14 0x0000555555706b4d in HttpSM::state_send_server_request_header (this=0x7fffeadb09b0, event=105, data=0x7fffd3019e28) at HttpSM.cc:2075
        method = <optimized out>
#15 0x00005555556f9e71 in HttpSM::main_handler (this=0x7fffeadb09b0, event=105, data=0x7fffd3019e28) at HttpSM.cc:2685
        jump_point = <optimized out>
#16 0x000055555587a813 in Continuation::handleEvent (this=<optimized out>, event=1, data=<optimized out>) at /usr/src/debug/bazinga-trafficserver-7.1.0/iocore/eventsystem/I_Continuation.h:153
No locals.
#17 read_signal_and_update (event=1, vc=0x7fffd3019d00) at UnixNetVConnection.cc:145
No locals.
#18 0x000055555587b4ca in UnixNetVConnection::mainEvent (this=<optimized out>, event=1, e=0x7fffeadb09b0) at UnixNetVConnection.cc:1257
        signal_timeout_at = <optimized out>
        writer_cont = <optimized out>
        reader_cont = 0x7fffeadb09b0
#19 0x00005555558700ad in Continuation::handleEvent (event=1, this=<optimized out>, data=<optimized out>) at /usr/src/debug/bazinga-trafficserver-7.1.0/iocore/eventsystem/I_Continuation.h:153
No locals.
#20 InactivityCop::check_inactivity (this=<optimized out>, event=<optimized out>, e=0x7fffef160f80) at UnixNet.cc:77
        now = 1498689374980168391
#21 0x0000555555896730 in Continuation::handleEvent (this=<optimized out>, event=2, data=<optimized out>) at ./I_Continuation.h:153
No locals.
#22 EThread::process_event (this=0x7fffefa0de40, e=0x7fffef160f80, calling_code=2) at UnixEThread.cc:143
        c_temp = <optimized out>
#23 0x0000555555896d30 in EThread::execute (this=<optimized out>) at UnixEThread.cc:225
        done_one = true
        next_time = <optimized out>
#24 0x0000555555895f27 in spawn_thread_internal (a=0x7ffff33fd6f0) at Thread.cc:84
No locals.
#25 0x00007ffff4f7eaa1 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#26 0x00007ffff527cbcd in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by SolidWallOfCode** [comment]
See #2213. Do I need to prep a PR for this being backported to 7.1.x?

**Comment by calavera** [comment]
This is already in 7.1.x. I think the issue can be closed now.
