### ISSUE TITLE
Segfault when registering TS_VCONN_PRE_ACCEPT_HOOK without a mutex

### ISSUE THREAD

**Issue by clearswift** [apache/trafficserver#2353]
This might be intended behaviour, but when I register a continuation on `TS_VCONN_PRE_ACCEPT_HOOK` without a mutex:

```c
TSHttpHookAdd(
    TS_VCONN_PRE_ACCEPT_HOOK,
    TSContCreate(handler, NULL)
)
```
ATS segfaults on new connection:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff64bc700 (LWP 31355)]
0x0000000000516fd2 in Mutex_trylock(SourceLocation const&, char const*, ProxyMutex*, EThread*) ()
(gdb) bt
#0  0x0000000000516fd2 in Mutex_trylock(SourceLocation const&, char const*, ProxyMutex*, EThread*) ()
#1  0x000000000051734f in MutexTryLock::MutexTryLock(SourceLocation const&, char const*, Ptr<ProxyMutex>&, EThread*) ()
#2  0x0000000000789014 in (anonymous namespace)::ContWrapper::wrap(ProxyMutex*, Continuation*, int, void*) ()
#3  0x000000000078d0e3 in SSLNetVConnection::sslServerHandShakeEvent(int&) ()
#4  0x000000000078c949 in SSLNetVConnection::sslStartHandShake(int, int&) ()
#5  0x000000000078a7a4 in SSLNetVConnection::net_read_io(NetHandler*, EThread*)
    ()
#6  0x000000000079ecf4 in NetHandler::mainNetEvent(int, Event*) ()
#7  0x0000000000517454 in Continuation::handleEvent(int, void*) ()
#8  0x00000000007cb37e in EThread::process_event(Event*, int) ()
#9  0x00000000007cb9a1 in EThread::execute() ()
#10 0x00000000007ca998 in spawn_thread_internal(void*) ()
#11 0x00007ffff7b52aa1 in start_thread () from /lib64/libpthread.so.0
#12 0x0000003e4f8e8bbd in clone () from /lib64/libc.so.6
```
If this is not intended behaviour a simple NULL check before [calling MUTEX_TRY_LOCK](https://github.com/apache/trafficserver/blob/7.1.x/iocore/net/SSLNetVConnection.cc#L119) would probably already solve this. If this is intenden behaviour, thus a `TS_VCONN_PRE_ACCEPT_HOOK` must provide a mutex (can you please explain me why then?), I'd suggest adding an assertion on `TSHttpHookAdd`.

**Comment by oknet** [comment]
In ATS, not all the time the mutex is needed.

The TS_VCONN_PRE_ACCEPT_HOOK always need a TSCont that has a valid mutex.

```
source: SSLNetVConnection.cc
 101   /** Convenience static method.
 102 
 103       This lets a client make one call and not have to (accurately)
 104       copy the invocation logic embedded here. We duplicate it near
 105       by textually so it is easier to keep in sync.
 106 
 107       This takes the same arguments as the constructor but, if the
 108       lock can be obtained immediately, does not construct an
 109       instance but simply calls the @a target.
 110   */
 111   static void
 112   wrap(ProxyMutex *mutex,             ///< Mutex for this continuation (primary lock).
 113        Continuation *target,          ///< "Real" continuation we want to call.
 114        int eventId = EVENT_IMMEDIATE, ///< Event ID for invocation of @a target.
 115        void *edata = nullptr          ///< Data for invocation of @a target.
 116        )
 117   {
 118     EThread *eth = this_ethread();
 119     MUTEX_TRY_LOCK(lock, target->mutex, eth);
 120     if (lock.is_locked()) {
 121       target->handleEvent(eventId, edata);
 122     } else {
 123       eventProcessor.schedule_imm(new ContWrapper(mutex, target, eventId, edata), ET_NET);
 124     }
 125   }
```

```target``` is the TSCont object.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
