### ISSUE TITLE
Crash in QUICTransportParameters::get

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#2607]
```
(gdb) bt full
#0  0x0000000000af047a in std::__uniq_ptr_impl<unsigned char, void (*)(void*)>::_M_ptr (this=0x8) at /usr/include/c++/7/bits/unique_ptr.h:147
No locals.
#1  0x0000000000aeeab2 in std::unique_ptr<unsigned char, void (*)(void*)>::get (this=0x8) at /usr/include/c++/7/bits/unique_ptr.h:337
No locals.
#2  0x0000000000af0568 in std::unique_ptr<unsigned char, void (*)(void*)>::operator bool (this=0x8) at /usr/include/c++/7/bits/unique_ptr.h:351
No locals.
#3  0x0000000000b57736 in QUICTransportParameters::get (this=0x0, tpid=..., len=@0x7fffedd02af0: 0) at QUICTransportParameters.cc:87
No locals.
#4  0x0000000000b57e67 in QUICTransportParameters::initial_max_stream_data (this=0x0) at QUICTransportParameters.cc:122
        len = 0
        data = 0x4542dfd6a2e21100 <error: Cannot access memory at address 0x4542dfd6a2e21100>
#5  0x0000000000b3f109 in QUICStreamManager::_find_or_create_stream (this=0x607000017010, stream_id=1) at QUICStreamManager.cc:214
        local_tp = @0x619000020880: {_vptr.QUICTransportParameters = 0xd7ba08 <vtable for QUICTransportParametersInEncryptedExtensions+16>, _buf = std::unique_ptr<unsigned char> containing 0x0, _parameters = std::map with 5 elements = {[{_id = 0}] = std::unique_ptr<QUICTransportParameterValue> containing 0x6030000648d0, [{_id = 1}] = std::unique_ptr<QUICTransportParameterValue> containing 0x603000064900, [{_id = 2}] = std::unique_ptr<QUICTransportParameterValue> containing 0x603000064930, [{_id = 3}] = std::unique_ptr<QUICTransportParameterValue> containing 0x603000064960, [{_id = 6}] = std::unique_ptr<QUICTransportParameterValue> containing 0x603000064990}}
        remote_tp = <error reading variable>
        stream = 0x62f00000cc50
#6  0x0000000000b3eafb in QUICStreamManager::_handle_frame (this=0x607000017010, frame=std::shared_ptr (count 4, weak 0) 0x6290000a3fa0) at QUICStreamManager.cc:144
        stream = 0x603000020178
        application = 0x7fffedd02c50
        nbytes_to_read = 11399113
        error = std::unique_ptr<QUICError> containing 0xb13f71 <ats_unique_malloc(unsigned long)+230>
#7  0x0000000000b3e119 in QUICStreamManager::handle_frame (this=0x607000017010, frame=std::shared_ptr (count 4, weak 0) 0x6290000a3fa0) at QUICStreamManager.cc:102
        error = std::unique_ptr<QUICError> containing 0x60300001c1b0
        __FUNCTION__ = "handle_frame"
#8  0x0000000000b2e5e9 in QUICFrameDispatcher::receive_frames (this=0x626000000100, payload=0x61d000050080 <incomplete sequence \337>, size=44, should_send_ack=@0x7fffedd033b0: true) at QUICFrameDispatcher.cc:73
        h = 0x607000017010
        __for_range = std::vector of length 2, capacity 2 = {0x607000017010, 0x6020000220f0}
        __for_begin = 0x607000017010
        __for_end = 0x0
        type = QUICFrameType::STREAM
        handlers = std::vector of length 2, capacity 2 = {0x607000017010, 0x6020000220f0}
        frame = std::shared_ptr (count 4, weak 0) 0x6290000a3fa0
        cursor = 32
        error = std::unique_ptr<QUICError> containing 0x60300001c180
        __FUNCTION__ = "receive_frames"
#9  0x0000000000aea367 in QUICNetVConnection::_recv_and_ack (this=0x7fffe95cedb0, payload=0x61d000050080 <incomplete sequence \337>, size=44, packet_num=1733876196) at QUICNetVConnection.cc:813
        should_send_ack = true
        error = std::unique_ptr<QUICError> containing 0x60300001c150
        __FUNCTION__ = "_recv_and_ack"
        ack_frame = std::unique_ptr<QUICFrame> containing 0x7fffedd036b0
#10 0x0000000000ae7953 in QUICNetVConnection::_state_connection_established_process_packet (this=0x7fffe95cedb0, packet=std::unique_ptr<QUICPacket> containing 0x62900008fdf0) at QUICNetVConnection.cc:656
        max_plain_txt_len = 2048
        plain_txt = std::unique_ptr<unsigned char> containing 0x61d000050080 <incomplete sequence \337>
        plain_txt_len = 44
        __FUNCTION__ = "_state_connection_established_process_packet"
#11 0x0000000000ae7e44 in QUICNetVConnection::_state_common_receive_packet (this=0x7fffe95cedb0) at QUICNetVConnection.cc:674
        error = std::unique_ptr<QUICError> containing 0x60300001c120
        p = std::unique_ptr<QUICPacket> containing 0x0
#12 0x0000000000ae5be7 in QUICNetVConnection::state_connection_closing (this=0x7fffe95cedb0, event=2500, data=0x62c0000060a0) at QUICNetVConnection.cc:488
        error = std::unique_ptr<QUICError> containing 0x60300001c0f0
        __FUNCTION__ = "state_connection_closing"
#13 0x0000000000599a33 in Continuation::handleEvent (this=0x7fffe95cedb0, event=2500, data=0x62c0000060a0) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
No locals.
#14 0x0000000000b9916d in EThread::process_event (this=0x7fffee8b6800, e=0x62c0000060a0, calling_code=2500) at UnixEThread.cc:122
        c_temp = 0x7fffe95cedb0
        lock = {m = {m_ptr = 0x62a000028790}, lock_acquired = true}
        __FUNCTION__ = "process_event"
#15 0x0000000000b99df3 in EThread::execute (this=0x7fffee8b6800) at UnixEThread.cc:217
        done_one = true
        e = 0x62c0000060a0
        NegativeQueue = {<DLL<Event, Event::Link_link>> = {head = 0x62c000005200}, tail = 0x62c000006dc0}
        next_time = 1507059837086797099
        __FUNCTION__ = "execute"
#16 0x0000000000b97367 in spawn_thread_internal (a=0x608000008f20) at Thread.cc:91
        p = 0x608000008f20
#17 0x00007ffff555536d in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#18 0x00007ffff47d3bbf in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by maskit** [comment]
I didn't see this crash during the last interop. Probably it was fixed at some point.
