### ISSUE TITLE
ASAN heap-buffer-overflow in QUICNetVConnection.cc

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#2608]
```
==17321==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200001303d at pc 0x7feece4b6433 bp 0x7feec4fbd2d0 sp 0x7feec4fbca78
READ of size 2 at 0x60200001303d thread T6 ([ET_NET 7])
[Oct  3 20:17:35.121] Server {0x7feec4d1a700} DEBUG: <QUICNetVConnection.cc:748 (_store_frame)> (quic_net) [bbdc4f01a3a19409] type=STREAM
[Oct  3 20:17:35.121] Server {0x7feec4d1a700} DEBUG: <QUICNetVConnection.cc:212 (_transmit_packet)> (quic_net) [bbdc4f01a3a19409] Packet Type=SERVER_CLEARTEXT Size=1221
    #0 0x7feece4b6432  (/lib64/libasan.so.4+0x79432)
    #1 0xb142f2 in QUICTypeUtil::read_nbytes_as_uint(unsigned char const*, unsigned char) /usr/local/src/trafficserver/iocore/net/quic/QUICTypes.cc:79
    #2 0xb1e117 in QUICStreamFrame::data_length() const /usr/local/src/trafficserver/iocore/net/quic/QUICFrame.cc:195
    #3 0xb1d68d in QUICStreamFrame::size() const /usr/local/src/trafficserver/iocore/net/quic/QUICFrame.cc:94
    #4 0xae1abe in QUICNetVConnection::retransmit_packet(QUICPacket const&) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:239
    #5 0xb36c33 in QUICLossDetector::_retransmit_handshake_packets() /usr/local/src/trafficserver/iocore/net/quic/QUICLossDetector.cc:356
    #6 0xb34e32 in QUICLossDetector::_on_loss_detection_alarm() /usr/local/src/trafficserver/iocore/net/quic/QUICLossDetector.cc:246
    #7 0xb31eb1 in QUICLossDetector::event_handler(int, Event*) /usr/local/src/trafficserver/iocore/net/quic/QUICLossDetector.cc:60
    #8 0x599a32 in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
    #9 0xb99190 in EThread::process_event(Event*, int) /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:122
    #10 0xb99e16 in EThread::execute() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:217
    #11 0xb9738a in spawn_thread_internal /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:91
    #12 0x7feeccb7536c in start_thread (/lib64/libpthread.so.0+0x736c)
    #13 0x7feecbdf3bbe in __GI___clone (/lib64/libc.so.6+0x110bbe)

0x60200001303d is located 9 bytes to the right of 4-byte region [0x602000013030,0x602000013034)
allocated by thread T9 ([ET_NET 7]) here:
    #0 0x7feece51b850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0x7feece1c7115 in ats_malloc /usr/local/src/trafficserver/lib/ts/ink_memory.cc:59
    #2 0xb19f60 in QUICPacketFactory::create_version_negotiation_packet(QUICPacket const*, unsigned long) /usr/local/src/trafficserver/iocore/net/quic/QUICPacket.cc:705
    #3 0xb4b9b2 in QUICHandshake::start(QUICPacket const*, QUICPacketFactory*) /usr/local/src/trafficserver/iocore/net/quic/QUICHandshake.cc:89
    #4 0xae6970 in QUICNetVConnection::_state_handshake_process_initial_client_packet(std::unique_ptr<QUICPacket, void (*)(QUICPacket*)>) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:595
    #5 0xae42fc in QUICNetVConnection::state_handshake(int, Event*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:387
    #6 0x599a32 in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
    #7 0xae3e47 in QUICNetVConnection::state_pre_handshake(int, Event*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:371
    #8 0x599a32 in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
    #9 0xb99190 in EThread::process_event(Event*, int) /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:122
    #10 0xb99a46 in EThread::execute() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:188
    #11 0xb9738a in spawn_thread_internal /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:91
    #12 0x7feeccb7536c in start_thread (/lib64/libpthread.so.0+0x736c)

Thread T6 ([ET_NET 7]) created by T0 ([TS_MAIN]) here:
    #0 0x7feece474a2f in pthread_create (/lib64/libasan.so.4+0x37a2f)
    #1 0xb96b1a in ink_thread_create ../../lib/ts/ink_thread.h:152
    #2 0xb97614 in Thread::start(char const*, void*, unsigned long, std::function<void ()> const&) /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:111
    #3 0xb9e9b0 in EventProcessor::spawn_event_threads(int, int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:336
    #4 0xb9f027 in EventProcessor::start(int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:385
    #5 0x5e6940 in main /usr/local/src/trafficserver/proxy/Main.cc:1771
    #6 0x7feecbd03509 in __libc_start_main (/lib64/libc.so.6+0x20509)

Thread T9 ([ET_NET 7]) created by T0 ([TS_MAIN]) here:
    #0 0x7feece474a2f in pthread_create (/lib64/libasan.so.4+0x37a2f)
    #1 0xb96b1a in ink_thread_create ../../lib/ts/ink_thread.h:152
    #2 0xb97614 in Thread::start(char const*, void*, unsigned long, std::function<void ()> const&) /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:111
    #3 0xb9e9b0 in EventProcessor::spawn_event_threads(int, int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:336
    #4 0xb9f027 in EventProcessor::start(int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:385
    #5 0x5e6940 in main /usr/local/src/trafficserver/proxy/Main.cc:1771
    #6 0x7feecbd03509 in __libc_start_main (/lib64/libc.so.6+0x20509)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.4+0x79432)
Shadow bytes around the buggy address:
  0x0c047fffa5b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffa5c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffa5d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffa5e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffa5f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fffa600: fa fa fd fa fa fa 04[fa]fa fa fa fa fa fa fa fa
  0x0c047fffa610: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffa620: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffa630: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffa640: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fffa650: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==17321==ABORTING
```

**Comment by masaori335** [comment]
https://github.com/apache/trafficserver/commit/e72cfd9c10b940971ff2643d46417ab4098656fa fix this.
