### ISSUE TITLE
H2 crash with priority enabled

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#2753]
Ran with H2 priority enabled in production.  Load average was higher than its peers.  Crashed after a bit (~10 minutes) with the following stack.

```
(gdb) bt full
#0  0x000000000051c8ef in Mutex_lock (m=0x0, t=0x2b6a68606010)
    at /var/builds/workspace/157188-v3-component/BUILD_CONTAINER/rhel6-gcc5_5/label/DOCKER-HIGH/app_root/_build/ats_build/../../trafficserver/iocore/eventsystem/I_Lock.h:409
No locals.
#1  0x0000000000545bec in MutexLock::MutexLock (this=0x2b6b200fbad0, am=..., t=0x2b6a68606010)
    at /var/builds/workspace/157188-v3-component/BUILD_CONTAINER/rhel6-gcc5_5/label/DOCKER-HIGH/app_root/_build/ats_build/../../trafficserver/iocore/eventsystem/I_Lock.h:511
No locals.
#2  0x0000000000664d1e in Http2ConnectionState::send_a_data_frame (this=0x2b6add554e20, stream=0x2aaeed77b820, 
    payload_length=@0x2b6b200ffb80) at ../../../../trafficserver/proxy/http2/Http2ConnectionState.cc:1244
        window_size = 7870776
        buf_len = 16384
        write_available_size = 16384
        read_available_size = 0
        flags = 0 '\000'
        payload_buffer = "\211PNG\r\n\032\n\000\000\000\rIHDR\000\000\000P\000\000\000P\b\003\000\000\000\271\317\002\237\000\000\000uPLTE.;N-:M+8K*8KCO`gp~\177\207\223\204\214\227,9L@L]\223\232\243\334\336\341\370\371\371\377\377\377MXh\306\312\317\376\376\376\306\311ϓ\231\243\333\335\341\370\370\371\371\371\372\324\327\333\303\307\314\371\371\371\371\372\372\221\230\242;GY2?R3?R\220\227\241>J[T_nU`o\300\304\312\361\362\364\360\361\363\360\361\362\324\326ڞ\312I\377\000\000\000\001bKGD\r\366\264a\365\000\000\000\tpHYs\000\000\000H\000\000\000H\000F\311k>\000\000\001\027IDATX\303\355\327\333\016\202\060\f\200a\312q(\023\025\004\021\020P\344\375\037\321`@o\034\253\320\304D\373_/_ \341\320\032\006\307q\034\067\021\230\226&\023>\341\300v\\o2ױ\001M\n\177\265\016\244\246`\275\362\005\322ۄ[\035\327\267\r7(\021\374\035\206\353\333\371\230\273\206=\352\372\036\327\270G\200`GXO\312\310\326\213\246\023\343\301\330\061\265\240\345\342=)]K\017z\343\341C\222*J\216\343\031\357\003\060"...
        current_reader = 0x2aaeed77ba68
        stream_lock = {m = {m_ptr = 0x0}, locked_p = true}
        __func__ = "send_a_data_frame"
        data = {hdr = {length = 597, type = 0 '\000', flags = 1 '\001', streamid = 23}, ioblock = {m_ptr = 0x2b6b04162dc0}, 
          ioreader = 0x0}
        lock = {m = {m_ptr = 0x2aadc878b2b0}, locked_p = false}
#3  0x0000000000664b75 in Http2ConnectionState::send_data_frames_depends_on_priority (this=0x2b6add554e20)
    at ../../../../trafficserver/proxy/http2/Http2ConnectionState.cc:1205
        node = 0x2b6b2b635ce0
        stream = 0x2aaeed77b820
        __func__ = "send_data_frames_depends_on_priority"
---Type <return> to continue, or q <return> to quit--- 
        len = 0
        result = 11114
#4  0x00000000006636ad in Http2ConnectionState::main_event_handler (this=0x2b6add554e20, event=2254, edata=0x2aad102bb900)
    at ../../../../trafficserver/proxy/http2/Http2ConnectionState.cc:889
        lock = {m = {m_ptr = 0x2b6b66f7df80}, locked_p = true}
        __func__ = "main_event_handler"
#5  0x000000000051cb2c in Continuation::handleEvent (this=0x2b6add554e20, event=2254, data=0x2aad102bb900)
    at /var/builds/workspace/157188-v3-component/BUILD_CONTAINER/rhel6-gcc5_5/label/DOCKER-HIGH/app_root/_build/ats_build/../../trafficserver/iocore/eventsystem/I_Continuation.h:153
No locals.
#6  0x00000000007badf3 in EThread::process_event (this=0x2b6a68606010, e=0x2aad102bb900, calling_code=2254)
    at ../../../../trafficserver/iocore/eventsystem/UnixEThread.cc:122
        c_temp = 0x2b6add554e20
        lock = {m = {m_ptr = 0x2b6b66f7df80}, lock_acquired = true}
#7  0x00000000007bb08e in EThread::execute (this=0x2b6a68606010) at ../../../../trafficserver/iocore/eventsystem/UnixEThread.cc:188
        done_one = false
        e = 0x2aad102bb900
        NegativeQueue = {<DLL<Event, Event::Link_link>> = {head = 0x0}, tail = 0x0}
        next_time = 1509551457328163674
#8  0x00000000007ba366 in spawn_thread_internal (a=0x21074d0) at ../../../../trafficserver/iocore/eventsystem/Thread.cc:85
        p = 0x21074d0
#9  0x00002b6a61e0aaa1 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#10 0x00002b6a61b56bcd in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb) 
```

Looking at frame 2 it appears that stream has been deleted.  This is our version of 7.1.1.  Maskit(?) recently made a fix to clean up race conditions on stream shutdown.  We have that queued up for our build.  I'll add that in and give it a try again.

**Comment by maskit** [comment]
The stack trace looks very similar to #2207.

**Comment by shinrich** [comment]
Yep, looks like the same thing.

**Comment by shinrich** [comment]
Closing to keep the conversation on #2207
