### ISSUE TITLE
HTTP/2 AuTest Failed Intermittently 

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#2795]
Sometime (not always) "Test Case 4: Multiple request" of HTTP/2 AuTest failed.
```
   Run: 3-general: Failed
     Test : Checking that True == _isRunningAfter - Passed
        Reason: Returned Value: True == _isRunningAfter
     Starting TestRun 3-general : No Issues found - Passed
        Reason: Started!
     Process: Default: Failed
       Test : Checking that ReturnCode == 0 - Passed
          Reason: Returned Value: 0 == 0
       Stream stdout : Checking that StdOutFile matches gold/replay.gold - Failed
          Reason: File differences
           Gold File : /Users/masaori/src/github.com/apache/trafficserver/tests/gold_tests/h2/gold/replay.gold
           Data File : /tmp/autest_sandbox/http2/_tmp_http2_3-general_Default/stream.stdout.txt
             Dropped 0 sessions for being malformed. Number of correct sessions 1
             range(0, 4)
             processProcess-1 has exited
             processProcess-2 has exited
             processProcess-3 has exited
             False
             PASS
             PASS
           - PASS
           + processProcess-4 has exited
             OK enough, it is time to exit, running time in seconds 0.034689903259277344
```

**Comment by masaori335** [comment]
Using retry.sh of client, ts, and server, I got below. When this happened, it looks like a stream (id=5) close immediately.

## client
```
MasaoriMacBookPro13 $ sh /tmp/autest/http2/_tmp_http2_3-general_Default/replay.sh                                                              (git:master) - [~/src/github.com/apache/trafficserver/tests]
Dropped 0 sessions for being malformed. Number of correct sessions 1
range(0, 4)
processProcess-1 has exited
processProcess-2 has exited
False
processProcess-4 has exited
PASS
PASS
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/masaori/src/github.com/apache/trafficserver/tests/gold_tests/autest-site/../../tools/traffic-replay/h2Replay.py", line 309, in session_replay
    response = h2conn.get_response(id)
  File "/Users/masaori/src/github.com/apache/trafficserver/tests/env-test/lib/python3.6/site-packages/hyper/http20/connection.py", line 311, in get_response
    stream = self._get_stream(stream_id)
  File "/Users/masaori/src/github.com/apache/trafficserver/tests/env-test/lib/python3.6/site-packages/hyper/http20/connection.py", line 289, in _get_stream
    raise StreamResetError("Stream forcefully closed")
hyper.http20.exceptions.StreamResetError: Stream forcefully closed

processProcess-3 has exited
OK enough, it is time to exit, running time in seconds 0.031239748001098633
```

## ts
```
[Nov 10 22:20:02.210] Server {0xb0008000} DEBUG: <Http2ConnectionState.cc:1381 (send_headers_frame)> (http2_con) [8] [5] Send HEADERS frame
[Nov 10 22:20:02.210] Server {0xb0008000} DEBUG: <Http2Stream.cc:746 (response_initialize_data_handling)> (http2_stream) Response is chunked
[Nov 10 22:20:02.210] Server {0xb0008000} DEBUG: <Http2Stream.cc:622 (update_write_request)> (http2_stream) write update stream_id=5 event=103
[Nov 10 22:20:02.210] Server {0xb0008000} DEBUG: <Http2Stream.cc:317 (do_io_close)> (http2_stream) do_io_close stream 5
[Nov 10 22:20:02.210] Server {0xb0008000} DEBUG: <Http2ConnectionState.cc:1134 (delete_stream)> (http2_con) [8] [5] Delete stream
[Nov 10 22:20:02.210] Server {0xb0008000} DEBUG: <Http2ConnectionState.cc:1579 (send_rst_stream_frame)> (http2_con) [8] [5] Send RST_STREAM frame
[Nov 10 22:20:02.210] Server {0xb0008000} DEBUG: <Http2Stream.cc:264 (change_state)> (http2_stream) Http2StreamState::HTTP2_STREAM_STATE_CLOSED
[Nov 10 22:20:02.210] Server {0xb0008000} DEBUG: <Http2Stream.cc:666 (destroy)> (http2_stream) Destroy stream 5, sent 0 bytes
```
[full debug log](https://paste.apache.org/jdDE) (debug tag is changed to "http2")

**Comment by maskit** [comment]
It seems like the stream state is not changed to CLOSED state. It has to be CLOSED state before calling `delete_stream()`. Otherwise `delete_stream()` sends a RST_STREAM frame.

According to the log, the response is chunked, so we can't set END_STREAM flag to the HEADERS frame (this is fine). In this case, ATS should send a DATA frame with END_STREAM flag even if the data size was zero, but there's no DATA frames for stream 5. This is the reason why ATS sent a RST_STREAM frame.

I'm not sure why it doesn't send any DATA frames. I tested the latest master with httpbin/stream-bytes/ and it works correctly.

**Comment by masaori335** [comment]
Added a debug log if result of `send_a_data_frame` is `HTTP2_SEND_A_DATA_FRAME_NO_WINDOW`.
The stream is closed regardless it has response data or not.

## Failed
```
[Nov 13 16:12:25.024] Server {0xb0004000} DEBUG: <Http2ConnectionState.cc:202 (rcv_headers_frame)> (http2_con) [13] [5] Received HEADERS frame
[Nov 13 16:12:25.024] Server {0xb0004000} DEBUG: <Http2Stream.cc:267 (change_state)> (http2_stream) [13] [5] Http2StreamState::HTTP2_STREAM_STATE_HALF_CLOSED_REMOTE
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2ConnectionState.cc:1386 (send_headers_frame)> (http2_con) [13] [5] Send HEADERS frame
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2Stream.cc:742 (response_initialize_data_handling)> (http2_stream) [13] [5] Response is chunked
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2ConnectionState.cc:1366 (send_data_frames)> (http2_con) [13] [5] HTTP2_SEND_A_DATA_FRAME_NO_WINDOW
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2Stream.cc:625 (update_write_request)> (http2_stream) [13] [5] write update (event=103)
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2Stream.cc:320 (do_io_close)> (http2_stream) [13] [5] do_io_close
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2ConnectionState.cc:1366 (send_data_frames)> (http2_con) [13] [5] HTTP2_SEND_A_DATA_FRAME_NO_WINDOW
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2ConnectionState.cc:1135 (delete_stream)> (http2_con) [13] [5] Delete stream
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2ConnectionState.cc:1584 (send_rst_stream_frame)> (http2_con) [13] [5] Send RST_STREAM frame
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2Stream.cc:267 (change_state)> (http2_stream) [13] [5] Http2StreamState::HTTP2_STREAM_STATE_CLOSED
[Nov 13 16:12:25.025] Server {0xb0004000} DEBUG: <Http2Stream.cc:669 (destroy)> (http2_stroeam) [13] [5] Destroy stream, sent 0 bytes
```

## Success
```
[Nov 13 16:10:17.354] Server {0xb0000000} DEBUG: <Http2ConnectionState.cc:202 (rcv_headers_frame)> (http2_con) [12] [5] Received HEADERS frame
[Nov 13 16:10:17.354] Server {0xb0000000} DEBUG: <Http2Stream.cc:267 (change_state)> (http2_stream) [12] [5] Http2StreamState::HTTP2_STREAM_STATE_HALF_CLOSED_REMOTE
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ConnectionState.cc:1386 (send_headers_frame)> (http2_con) [12] [5] Send HEADERS frame
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2Stream.cc:742 (response_initialize_data_handling)> (http2_stream) [12] [5] Response is chunked
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ConnectionState.cc:1366 (send_data_frames)> (http2_con) [12] [5] HTTP2_SEND_A_DATA_FRAME_NO_WINDOW
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2Stream.cc:625 (update_write_request)> (http2_stream) [12] [5] write update (event=101)
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ConnectionState.cc:1366 (send_data_frames)> (http2_con) [12] [5] HTTP2_SEND_A_DATA_FRAME_NO_WINDOW
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2Stream.cc:625 (update_write_request)> (http2_stream) [12] [5] write update (event=103)
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ClientSession.cc:410 (state_start_frame_read)> (http2_cs) [12] [&Http2ClientSession::state_start_frame_read, VC_EVENT_READ_READY]
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ClientSession.cc:424 (do_start_frame_read)> (http2_cs) [12] receiving frame header
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ClientSession.cc:434 (do_start_frame_read)> (http2_cs) [12] frame header length=4, type=8, flags=0x0, streamid=0
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ConnectionState.cc:671 (rcv_window_update_frame)> (http2_con) [12] [0] Received WINDOW_UPDATE frame - updated to: 49152 delta: 49152
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ConnectionState.cc:1314 (send_a_data_frame)> (http2_con) [12] [5] Send a DATA frame - client window con: 49122 stream: 65505 payload: 30
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ConnectionState.cc:1328 (send_a_data_frame)> (http2_con) [12] [5] End of DATA frame
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2Stream.cc:267 (change_state)> (http2_stream) [12] [5] Http2StreamState::HTTP2_STREAM_STATE_CLOSED
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ConnectionState.cc:1360 (send_data_frames)> (http2_con) [12] [5] Shutdown stream
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2ConnectionState.cc:1135 (delete_stream)> (http2_con) [12] [5] Delete stream
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2Stream.cc:384 (initiating_close)> (http2_stream) [12] [5] initiating_close
[Nov 13 16:10:17.356] Server {0xb0000000} DEBUG: <Http2Stream.cc:412 (initiating_close)> (http2_stream) [12] [5] handle write from destroy (event=103)
[Nov 13 16:10:17.357] Server {0xb0000000} DEBUG: <Http2Stream.cc:669 (destroy)> (http2_stream) [12] [5] Destroy stream, sent 30 bytes
```
