### ISSUE TITLE
Gzip plugin wedges the ET_NET threads when Brotli is enabled

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#2947]
**Update**: Looking at this, I'm somewhat concerned about the fact that the threads seems to get stuck in error logging. Maybe this is a red-herring, and it's actually two issues here? 1) Brotli producing those errors and 2) Logging actually hanging when doing those errors?

**Update 2:** Looking at the error.log, before it wedges the threads, it has actually logged millions of errors. Once the threads are deadlocked, there are no more errors in the logs, so I'm pretty sure that we're dealing with two issues here. However, the deadlock in logging is likely less serious, so we should focus on the Brotli issue.

**Update 3:** I tried with an older version of libbrotli (v0.6.0), but it has the same issues. What  happens  is that we spew this all over error log, which if done fast enough, will wedge ATS:

```
20171218.20h02m56s [gzip/gzip.cc:380] [brotli_transform_one] ERROR: brotli-transform: ERROR: brotli avail_in is (32768): should be 0
20171218.20h02m56s [gzip/gzip.cc:380] [brotli_transform_one] ERROR: brotli-transform: ERROR: brotli avail_in is (32768): should be 0
20171218.20h02m56s [gzip/gzip.cc:380] [brotli_transform_one] ERROR: brotli-transform: ERROR: brotli avail_in is (32768): should be 0
```

So, I'm very confused how anyone is actually using Brotli in production...

**Original post:**

I tried enabling Brotli for Docs/CI, and even though it does work, after a few request, all ET_NET threads are wedged. Doing a gdb, I see

```
#0  0x0000000000601436 in printf_common(void*, char const*, __va_list_tag*) ()
No symbol table info available.
#1  0x000000000060388e in vsnprintf ()
No symbol table info available.
#2  0x00000000009a419d in LogObject::va_log (this=0x610000007740, lad=0x0, fmt=0x2ab712c8b200 "[%s:%d] [%s] ERROR: brotli-transform: ERROR: brotli avail_in is (%lu): should be 0", ap=0x2aaaaaffe660) at LogObject.cc:523
        MAX_ENTRY = 16384
        entry = "20171215.22h20m00s [gzip/gzip.cc:380] [brotli_transform_one] ERROR: brotli-transform: ERROR: brotli avail_in is (25522): should be 0", '\000' <repeats 6772 times>...
        len = 19
#3  0x000000000096c0a3 in Log::va_error (format=0x2ab712c8b200 "[%s:%d] [%s] ERROR: brotli-transform: ERROR: brotli avail_in is (%lu): should be 0", ap=0x2aaaaaffe660) at Log.cc:1122
        ret_val = 2
        mutex = 0x60c0000082c0
#4  0x00000000006b6eb2 in TSError (fmt=0x2ab712c8b200 "[%s:%d] [%s] ERROR: brotli-transform: ERROR: brotli avail_in is (%lu): should be 0") at InkAPI.cc:402
        args = {{gp_offset = 8, fp_offset = 48, overflow_arg_area = 0x2aaaaaffe780, reg_save_area = 0x2aaaaaffe6a0}}
        __FUNCTION__ = "TSError"
#5  0x00002ab712c7c621 in brotli_transform_one (data=0x611000087900, upstream_buffer=0x62d0001d7000 "2 min 40 sec\" style=\"cursor:pointer\" href=\"/job/ubuntu_14_04-7.1.x/compiler=clang,label=ubuntu_14_04,type=release/189/console\" class=\"progress-bar \"><tbody><tr><td style=\"width:72%;\" class=\"progress-b"..., upstream_length=25522) at gzip/gzip.cc:380
        downstream_blkp = 0x607000022d10
        downstream_buffer = 0x62500010a000 '\276' <repeats 200 times>...
        downstream_length = 4096
        err = 0
        __FUNCTION__ = "brotli_transform_one"
#6  0x00002ab712c7c9a6 in compress_transform_one (data=0x611000087900, upstream_reader=0x611000088340, amount=32009) at gzip/gzip.cc:414
        downstream_blkp = 0x607000022c30
        upstream_buffer = 0x62d0001d7000 "2 min 40 sec\" style=\"cursor:pointer\" href=\"/job/ubuntu_14_04-7.1.x/compiler=clang,label=ubuntu_14_04,type=release/189/console\" class=\"progress-bar \"><tbody><tr><td style=\"width:72%;\" class=\"progress-b"...
        upstream_length = 25522
        __FUNCTION__ = "compress_transform_one"
#7  0x00002ab712c7db5e in compress_transform_do (contp=0x612000075f40) at gzip/gzip.cc:572
        upstream_vio = 0x612000075ff0
        data = 0x611000087900
        upstream_todo = 39255
        upstream_avail = 39255
        downstream_bytes_written = 3995
#8  0x00002ab712c7de86 in compress_transform (contp=0x612000075f40, event=TS_EVENT_IMMEDIATE) at gzip/gzip.cc:617
        __FUNCTION__ = "compress_transform"
#9  0x00000000006b9905 in INKContInternal::handle_event (this=0x612000075f40, event=1, edata=0x609000026ff0) at InkAPI.cc:1060
        retval = 10922
        __FUNCTION__ = "handle_event"
#10 0x00000000006ac92a in Continuation::handleEvent (this=0x612000075f40, event=1, data=0x609000026ff0) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
No locals.
#11 0x0000000000be5952 in EThread::process_event (this=0x2ab70ff33800, e=0x609000026ff0, calling_code=1) at UnixEThread.cc:130
        c_temp = 0x612000075f40
        lock = {m = {m_ptr = 0x60c00004c240}, lock_acquired = true}
        __FUNCTION__ = "process_event"
#12 0x0000000000be5ec1 in EThread::process_queue (this=0x2ab70ff33800, NegativeQueue=0x2aaaaaffed10, ev_count=0x2aaaaaffec90, nq_count=0x2aaaaaffec50) at UnixEThread.cc:169
        e = 0x609000026ff0
#13 0x0000000000be64f4 in EThread::execute_regular (this=0x2ab70ff33800) at UnixEThread.cc:229
        done_one = false
        sleep_time = 4975801
        e = 0x0
        NegativeQueue = {<DLL<Event, Event::Link_link>> = {head = 0x60900000c620}, tail = 0x60900000b300}
        next_time = 1513376011684529109
        delta = 3241559
        loop_start_time = 1513376011682771360
        loop_finish_time = 1513376011682770668
        prev_metric = 0x2ab7100376c0
        nq_count = 5
        ev_count = 6
        METRIC_INIT = {_loop_time = {_start = 0, _min = 9223372036854775807, _max = 0}, _events = {_min = 2147483647, _max = 0, _total = 0}, _count = 0, _wait = 0}
#14 0x0000000000be7025 in EThread::execute (this=0x2ab70ff33800) at UnixEThread.cc:324
        __FUNCTION__ = "execute"
#15 0x0000000000be3d31 in spawn_thread_internal (a=0x6060000198e0) at Thread.cc:85
        p = 0x6060000198e0
#16 0x00002ab70b009e25 in start_thread (arg=0x2aaaaafff700) at pthread_create.c:308
        __res = <optimized out>
        pd = 0x2aaaaafff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {46912501708544, -8557452013480867189, 0, 46965734979592, 46912501708544, 105965433231584, -2564651259675702645, -2570494656708113781}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#17 0x00002ab70ba2434d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
No locals.
```

It's somewhat odd that it seems stuck in the logging, doesn't it? If I strace the LWP above, all I see is

```
futex(0x2ab70bceaec0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x2ab70bceaec0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2ab70bceaec0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2ab70bceaec0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x2ab70bceaec0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2ab70bceaec0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2ab70bceaec0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x2ab70bceaec0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2ab70bceaec0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x2ab70bceaec0, FUTEX_WAKE_PRIVATE, 1) = 0
```

In the error log, I got a few  of these (definitely not in a loop though):

```
20171215.21h59m45s [gzip/gzip.cc:380] [brotli_transform_one] ERROR: brotli-transform: ERROR: brotli avail_in is (2271): should be 0
20171215.21h59m45s [gzip/gzip.cc:380] [brotli_transform_one] ERROR: brotli-transform: ERROR: brotli avail_in is (2271): should be 0
20171215.21h59m45s [gzip/gzip.cc:380] [brotli_transform_one] ERROR: brotli-transform: ERROR: brotli avail_in is (2271): should be 0
20171215.21h59m45s [gzip/gzip.cc:380] [brotli_transform_one] ERROR: brotli-transform: ERROR: brotli avail_in is (2271): should be 0
20171215.21h59m45s [gzip/gzip.cc:380] [brotli_transform_one] ERROR: brotli-transform: ERROR: brotli avail_in is (2271): should be 0
```

The thing is, if all I do is turning off brotli support, things works well.

**Comment by zwoop** [comment]
Ok, so I commented out the section in the brotli plugin that causes logging to wedge, and that actually yields a lot more useful information. For example, we're stuck in this loop forever it seems:

```
(gdb) bt full
#0  0x00000000006aeea3 in Ptr<IOBufferBlock>::operator bool (this=0x611000068010) at ../lib/ts/Ptr.h:116
No locals.
#1  0x00000000006e0f18 in MIOBuffer::first_write_block (this=0x611000068000) at /usr/local/src/trafficserver/iocore/eventsystem/I_IOBuffer.h:923
No locals.
#2  0x00000000006e25f0 in MIOBuffer::get_current_block (this=0x611000068000) at /usr/local/src/trafficserver/iocore/eventsystem/P_IOBuffer.h:979
No locals.
#3  0x00000000006ee2f1 in TSIOBufferStart (bufp=0x611000068000) at InkIOCoreAPI.cc:586
        b = 0x611000068000
        blk = 0x2aaaab7fe7c0
#4  0x00002accc2a03289 in brotli_transform_one (data=0x6110002695c0, upstream_buffer=0x62d002031000 "an><span class=\"p\">:</span><span class=\"o\">//</span><span class=\"n\">games</span><span class=\"o\">.</span><span class=\"n\">bar</span><span class=\"o\">.</span><span class=\"n\">com</span><span class=\"o\">/</s"..., upstream_length=21531) at gzip/gzip.cc:351
        downstream_blkp = 0x6070000f5790
        downstream_buffer = 0x625000268000 '\276' <repeats 200 times>...
        downstream_length = 4096
        err = 0
#5  0x00002accc2a039a9 in compress_transform_one (data=0x6110002695c0, upstream_reader=0x611000088728, amount=21531) at gzip/gzip.cc:416
        downstream_blkp = 0x60700000e8e0
        upstream_buffer = 0x62d002031000 "an><span class=\"p\">:</span><span class=\"o\">//</span><span class=\"n\">games</span><span class=\"o\">.</span><span class=\"n\">bar</span><span class=\"o\">.</span><span class=\"n\">com</span><span class=\"o\">/</s"...
        upstream_length = 21531
        __FUNCTION__ = "compress_transform_one"
#6  0x00002accc2a04b61 in compress_transform_do (contp=0x61200009f4c0) at gzip/gzip.cc:574
        upstream_vio = 0x61200009f570
        data = 0x6110002695c0
        upstream_todo = 21531
        upstream_avail = 21531
        downstream_bytes_written = 4096
#7  0x00002accc2a04e89 in compress_transform (contp=0x61200009f4c0, event=TS_EVENT_IMMEDIATE) at gzip/gzip.cc:619
        __FUNCTION__ = "compress_transform"
#8  0x00000000006b9905 in INKContInternal::handle_event (this=0x61200009f4c0, event=1, edata=0x609000003f20) at InkAPI.cc:1060
        retval = 10922
        __FUNCTION__ = "handle_event"
#9  0x00000000006ac92a in Continuation::handleEvent (this=0x61200009f4c0, event=1, data=0x609000003f20) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
No locals.
#10 0x0000000000be5952 in EThread::process_event (this=0x2accc007e800, e=0x609000003f20, calling_code=1) at UnixEThread.cc:130
        c_temp = 0x61200009f4c0
        lock = {
          m = {
            m_ptr = 0x60c00006d780
          },
          lock_acquired = true
        }
        __FUNCTION__ = "process_event"
#11 0x0000000000be5ec1 in EThread::process_queue (this=0x2accc007e800, NegativeQueue=0x2aaaab7fed10, ev_count=0x2aaaab7fec90, nq_count=0x2aaaab7fec50) at UnixEThread.cc:169
        e = 0x609000003f20
#12 0x0000000000be64f4 in EThread::execute_regular (this=0x2accc007e800) at UnixEThread.cc:229
        done_one = false
        sleep_time = 60000000
        e = 0x0
        NegativeQueue = {
          <DLL<Event, Event::Link_link>> = {
            head = 0x60900000b660
          },
          members of Queue<Event, Event::Link_link>:
          tail = 0x60900000b0c0
        }
        next_time = 1513629949537553033
        delta = 5259176
        loop_start_time = 1513629949222813670
        loop_finish_time = 1513629949222812209
        prev_metric = 0x2accc0182420
        nq_count = 6
        ev_count = 7
        METRIC_INIT = {
          _loop_time = {
            _start = 0,
            _min = 9223372036854775807,
            _max = 0
          },
          _events = {
            _min = 2147483647,
            _max = 0,
            _total = 0
          },
          _count = 0,
          _wait = 0
        }
#13 0x0000000000be7025 in EThread::execute (this=0x2accc007e800) at UnixEThread.cc:324
        __FUNCTION__ = "execute"
#14 0x0000000000be3d31 in spawn_thread_internal (a=0x6060000195e0) at Thread.cc:85
        p = 0x6060000195e0
#15 0x00002accbad91e25 in start_thread (arg=0x2aaaab7ff700) at pthread_create.c:308
        __res = <optimized out>
        pd = 0x2aaaab7ff700
        now = <optimized out>
        unwind_buf = {
          cancel_jmp_buf = {{
              jmp_buf = {46912510097152, -7550611248619137196, 0, 47058883438600, 46912510097152, 105965433230816, -4439561953341548716, -4418133896061331628},
              mask_was_saved = 0
            }},
          priv = {
            pad = {0x0, 0x0, 0x0, 0x0},
            data = {
              prev = 0x0,
              cleanup = 0x0,
              canceltype = 0
            }
          }
        }
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#16 0x00002accbb7ac34d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
No locals.
```

**Comment by zwoop** [comment]
**Another update**: Upon further code inspection, the plugin (and Brotli code) takes a somewhat different code patch when "flush true" is set. I'm running with with "flush false" on Docs / CI, which seems stable so far.

**Comment by shukitchan** [comment]
@zwoop and @randall , should we close this now?
