### ISSUE TITLE
Double free  in TextBuffer::~TextBuffer

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#3028]
Config

dest_domain=. method=get parent="www.scw.com:80" secondary_parent="www.scw.com:81" parent_is_proxy=false round_robin=consistent_hash

```
[Jan 22 08:48:59.797] Server {0x7ffff7fe67c0} DEBUG: <ParentSelection.cc:355 (PreProcessParents)> (parent_select) token: www.scw.com, matches this machine.  Removing self from parent list at line 56
=================================================================
==32719==ERROR: AddressSanitizer: attempting double-free on 0x606000006920 in thread T0:
    #0 0x7ffff6f022ca in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x982ca)
    #1 0x7ffff6bf379a in ats_free /root/trafficserver/lib/ts/ink_memory.cc:127
    #2 0x7ffff6c26600 in TextBuffer::~TextBuffer() /root/trafficserver/lib/ts/TextBuffer.cc:58
    #3 0x4fbddd in Result::~Result() ../../lib/ts/Result.h:35
    #4 0x507a79 in ControlMatcher<ParentRecord, ParentResult>::BuildTableFromString(char*) (/usr/local/trafficserver/bin/traffic_server+0x507a79)
    #5 0x506d64 in ControlMatcher<ParentRecord, ParentResult>::BuildTable() (/usr/local/trafficserver/bin/traffic_server+0x506d64)
    #6 0x506a2a in ControlMatcher<ParentRecord, ParentResult>::ControlMatcher(char const*, char const*, matcher_tags const*, int) (/usr/local/trafficserver/bin/traffic_server+0x506a2a)
    #7 0x591da5 in ParentConfig::reconfigure() /root/trafficserver/proxy/ParentSelection.cc:275
    #8 0x591cc9 in ParentConfig::startup() /root/trafficserver/proxy/ParentSelection.cc:253
    #9 0x57d292 in main /root/trafficserver/proxy/Main.cc:1808
    #10 0x7ffff4a0d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #11 0x4f77a8 in _start (/usr/local/trafficserver/bin/traffic_server+0x4f77a8)

0x606000006920 is located 0 bytes inside of 64-byte region [0x606000006920,0x606000006960)
freed by thread T0 here:
    #0 0x7ffff6f022ca in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x982ca)
    #1 0x7ffff6bf379a in ats_free /root/trafficserver/lib/ts/ink_memory.cc:127
    #2 0x7ffff6c26600 in TextBuffer::~TextBuffer() /root/trafficserver/lib/ts/TextBuffer.cc:58
    #3 0x4fbddd in Result::~Result() ../../lib/ts/Result.h:35
    #4 0x50950c in HostMatcher<ParentRecord, ParentResult>::NewEntry(matcher_line*) (/usr/local/trafficserver/bin/traffic_server+0x50950c)
    #5 0x507a32 in ControlMatcher<ParentRecord, ParentResult>::BuildTableFromString(char*) (/usr/local/trafficserver/bin/traffic_server+0x507a32)
    #6 0x506d64 in ControlMatcher<ParentRecord, ParentResult>::BuildTable() (/usr/local/trafficserver/bin/traffic_server+0x506d64)
    #7 0x506a2a in ControlMatcher<ParentRecord, ParentResult>::ControlMatcher(char const*, char const*, matcher_tags const*, int) (/usr/local/trafficserver/bin/traffic_server+0x506a2a)
    #8 0x591da5 in ParentConfig::reconfigure() /root/trafficserver/proxy/ParentSelection.cc:275
    #9 0x591cc9 in ParentConfig::startup() /root/trafficserver/proxy/ParentSelection.cc:253
    #10 0x57d292 in main /root/trafficserver/proxy/Main.cc:1808
    #11 0x7ffff4a0d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

previously allocated by thread T0 here:
    #0 0x7ffff6f02961 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98961)
    #1 0x7ffff6bf3550 in ats_realloc /root/trafficserver/lib/ts/ink_memory.cc:79
    #2 0x7ffff6c26a77 in TextBuffer::enlargeBuffer(unsigned int) /root/trafficserver/lib/ts/TextBuffer.cc:137
    #3 0x7ffff6c27107 in TextBuffer::vformat(char const*, __va_list_tag*) /root/trafficserver/lib/ts/TextBuffer.cc:255
    #4 0x4fbff0 in Result::failure(char const*, ...) ../../lib/ts/Result.h:61
    #5 0x594b12 in ParentRecord::Init(matcher_line*) /root/trafficserver/proxy/ParentSelection.cc:670
    #6 0x509479 in HostMatcher<ParentRecord, ParentResult>::NewEntry(matcher_line*) (/usr/local/trafficserver/bin/traffic_server+0x509479)
    #7 0x507a32 in ControlMatcher<ParentRecord, ParentResult>::BuildTableFromString(char*) (/usr/local/trafficserver/bin/traffic_server+0x507a32)
    #8 0x506d64 in ControlMatcher<ParentRecord, ParentResult>::BuildTable() (/usr/local/trafficserver/bin/traffic_server+0x506d64)
    #9 0x506a2a in ControlMatcher<ParentRecord, ParentResult>::ControlMatcher(char const*, char const*, matcher_tags const*, int) (/usr/local/trafficserver/bin/traffic_server+0x506a2a)
    #10 0x591da5 in ParentConfig::reconfigure() /root/trafficserver/proxy/ParentSelection.cc:275
    #11 0x591cc9 in ParentConfig::startup() /root/trafficserver/proxy/ParentSelection.cc:253
    #12 0x57d292 in main /root/trafficserver/proxy/Main.cc:1808
    #13 0x7ffff4a0d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: double-free ??:0 __interceptor_free
```

**Comment by bryancall** [comment]
@vmamidi Can you see if this has been fixed?

**Comment by vmamidi** [comment]
@scw00 is this still happening? I am unable to reproduce this.

**Comment by vmamidi** [comment]
closing after talking to @scw00.
