### ISSUE TITLE
Crash around handshake

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#3155]
```
[Feb 21 22:37:14.893] Server {0x7f946eb33700} DEBUG: <QUICNetVConnection.cc:1184 (_dequeue_rec> (quic_net)                  [5504b7201d66f464] Not ready to decrypt the packet
ASAN:DEADLYSIGNAL
=================================================================
==22764==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x000000ba0747 bp 0x7f946eb322d0 sp 0x7f946eb322c0 T2)
==22764==The signal is caused by a READ memory access.
==22764==Hint: address points to the zero page.
    #0 0xba0746 in QUICPacket::type() const /usr/local/src/trafficserver/iocore/net/quic/QUICPacket.cc:507
    #1 0xb66742 in QUICNetVConnection::_state_handshake_process_packet(std::unique_ptr<QUICPacket, void (*)(QUICPacket*)>) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:772
    #2 0xb6407e in QUICNetVConnection::state_handshake(int, Event*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:532
    #3 0x5dec1e in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:153
    #4 0xb660cb in QUICNetVConnection::net_read_io(NetHandler*, EThread*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:700
    #5 0xb22b6b in NetHandler::process_ready_list() /usr/local/src/trafficserver/iocore/net/UnixNet.cc:391
    #6 0xb23feb in NetHandler::waitForActivity(long) /usr/local/src/trafficserver/iocore/net/UnixNet.cc:523
    #7 0xc4d79c in EThread::execute_regular() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:271
    #8 0xc4dfb3 in EThread::execute() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:324
    #9 0xc4a788 in spawn_thread_internal /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:85
    #10 0x7f9475a4e36c in start_thread (/lib64/libpthread.so.0+0x736c)
    #11 0x7f9474cc8e1e in __GI___clone (/lib64/libc.so.6+0x110e1e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/local/src/trafficserver/iocore/net/quic/QUICPacket.cc:507 in QUICPacket::type() const
Thread T2 ([ET_NET 0]) created by T0 ([TS_MAIN]) here:
    #0 0x7f9477602a2f in pthread_create (/lib64/libasan.so.4+0x37a2f)
    #1 0xc4a022 in ink_thread_create ../../lib/ts/ink_thread.h:156
    #2 0xc4a8b1 in Thread::start(char const*, void*, unsigned long, std::function<void ()> const&) /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:102
    #3 0xc53d0d in EventProcessor::spawn_event_threads(int, int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:383
    #4 0xc54525 in EventProcessor::start(int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:446
    #5 0x62eeab in main /usr/local/src/trafficserver/proxy/Main.cc:1825
    #6 0x7f9474bd8889 in __libc_start_main (/lib64/libc.so.6+0x20889)

==22764==ABORTING

```

**Comment by maskit** [comment]
6706e60b8c49c64df3c42d4ff415d2986bee02af should fixed this. Leave a while to check if it really does.

**Comment by maskit** [comment]
Seems to be fixed.
