### ISSUE TITLE
jtest segment fault

### ISSUE THREAD

**Issue by hankai17** [apache/trafficserver#3528]
./jtest -s 9080 -S localhost -u url.txt -x -l -F
url.txt just has one url. Here is www.ifeng.com.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5d86eca in memchr () from /usr/lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5d86eca in memchr () from /usr/lib64/libc.so.6
#1  0x0000000000404012 in strncasestr (s=0x235a9bb "tml", find=0x411dd1 "href", len=-2) at jtest/jtest.cc:799
#2  0x0000000000407f34 in find_href_start (tag=0x411dd1 "href", 
    base=0x64595b "shtml\".clearfix:after {\n        content: \".\";\n        display: block;\n        height: 0;\n        clear: both;\n        visibility: hidden;\n    }\n    \n    * html .clearfix {\n        height: 1%;\n    }\n  "..., len=-2) at jtest/jtest.cc:1901
#3  0x00000000004082b6 in compose_all_urls (tag=0x411dd1 "href", 
    buf=0x6450d0 "<li><a href=\"http://zj.ifeng.com/a/20180425/6527254_0.shtml\" target=\"_blank\">港资本市场迎25年来最大改革 与错过阿里巴巴有关</a></li>\n\n\n<li class=\"bold\"><a href=\"http://zj.ifeng.com"..., 
    start=0x645957 "htx.shtml\".clearfix:after {\n        content: \".\";\n        display: block;\n        height: 0;\n        clear: both;\n        visibility: hidden;\n    }\n    \n    * html .clearfix {\n        height: 1%;\n    "..., 
    end=0x64595b "shtml\".clearfix:after {\n        content: \".\";\n        display: block;\n        height: 0;\n        clear: both;\n        visibility: hidden;\n    }\n    \n    * html .clearfix {\n        height: 1%;\n    }\n  "..., buflen=2185, base_url=0x6429b0 "www.ifeng.com")
    at jtest/jtest.cc:1963
#4  0x000000000040878f in extract_urls (
    buf=0x6450d0 "<li><a href=\"http://zj.ifeng.com/a/20180425/6527254_0.shtml\" target=\"_blank\">港资本市场迎25年来最大改革 与错过阿里巴巴有关</a></li>\n\n\n<li class=\"bold\"><a href=\"http://zj.ifeng.com"..., buflen=2185, base_url=0x6429b0 "www.ifeng.com") at jtest/jtest.cc:2033
#5  0x00000000004088e3 in follow_links (sock=4) at jtest/jtest.cc:2056
#6  0x000000000040a519 in read_response (sock=4) at jtest/jtest.cc:2426
#7  0x0000000000407498 in poll_loop () at jtest/jtest.cc:1627
#8  0x000000000040d33b in main (argc=10, argv=0x7fffffffe4a8) at jtest/jtest.cc:3349
```
In "#2" you can see that" 0x0000000000404012 in strncasestr (s=0x235a9bb "tml", find=0x411dd1 "href", len=-2)". Through my analysis， len should more than 0.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
