### ISSUE TITLE
ASan : heap-buffer-overflow on  QUICPacketFactory::create

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#3772]
```
[Jun  4 07:44:58.416] {0x7faf3ee80cc0} DEBUG: <QUICNetProcessor.cc:69 (start)> (quic_ps)                        TLS 1.3 (draft 28)                                                                                                [23/205]
[Jun  4 07:44:58.877] {0x7faf31b1d700} DEBUG: <QUICPacketHandler.cc:200 (_recv_packet)> (quic_sec)                       [f30ea9d8-153a221b] recv packet from 172.56.42.104:23146, size=1252
[Jun  4 07:44:58.877] {0x7faf31b1d700} DEBUG: <QUICPacketHandler.cc:237 (_recv_packet)> (quic_sec)                       [f30ea9d8-153a221b] client initial dcid=153a221b95800ba2
[Jun  4 07:44:58.903] {0x7faf31b1d700} DEBUG: <QUICNetVConnection.cc:99 (init)> (quic_net)                       [f30ea9d8-f98bcf6c] dcid=f30ea9d841b0fca9 scid=f98bcf6c94dee3c9ffd5a28b4dc6807192be
[Jun  4 07:44:58.904] {0x7faf31b1d700} DEBUG: <QUICTLS.cc:188 (initialize_key_materials> (quic_tls)                       Generating CLEARTEXT keys
[Jun  4 07:44:58.904] {0x7faf31b1d700} DEBUG: <QUICTLS.cc:194 (initialize_key_materials> (vv_quic_crypto)                 client key 0x27A4C87DF0752C4AB3CE2C1354A9A400
[Jun  4 07:44:58.904] {0x7faf31b1d700} DEBUG: <QUICTLS.cc:196 (initialize_key_materials> (vv_quic_crypto)                 client iv 0x63B8E1ADAC5ADDEE63F21F1F
[Jun  4 07:44:58.904] {0x7faf31b1d700} DEBUG: <QUICTLS.cc:203 (initialize_key_materials> (vv_quic_crypto)                 server key 0x70FA27B6DB4569E7F3980584460523A8
[Jun  4 07:44:58.904] {0x7faf31b1d700} DEBUG: <QUICTLS.cc:205 (initialize_key_materials> (vv_quic_crypto)                 server iv 0x55EF6D9CA8D066978EE68AD2
[Jun  4 07:44:58.904] {0x7faf31b1d700} DEBUG: <QUICNetVConnection.cc:1620 (_schedule_pa> (quic_net)                       [f30ea9d8-f98bcf6c] Schedule QUIC_EVENT_PATH_VALIDATION_TIMEOUT event
[Jun  4 07:44:58.917] {0x7faf338fe700} DEBUG: <QUICNetVConnection.cc:1671 (_switch_to_h> (quic_net)                       [f30ea9d8-f98bcf6c] Enter state_handshake
[Jun  4 07:44:58.918] {0x7faf338fe700} DEBUG: <QUICPacket.cc:730 (create)> (quic_packet)                    [f30ea9d8-153a221b] Decrypting INITIAL packet #1572707275 using CLEARTEXT
=================================================================
==887==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61a000010164 at pc 0x7faf3dd31433 bp 0x7faf338fc840 sp 0x7faf338fbfe8
READ of size 1228 at 0x61a000010164 thread T9 ([ET_NET 7])
    #0 0x7faf3dd31432  (/lib64/libasan.so.4+0x79432)
    #1 0xbfc186 in QUICPacketFactory::create(IpEndpoint, std::unique_ptr<unsigned char, void (*)(void*)>, unsigned long, unsigned long, QUICPacketCreationResult&) /usr/local/src/trafficserver/iocore/net/quic/QUICPacket.cc:742
    #2 0xc8c89e in QUICPacketReceiveQueue::dequeue(QUICPacketCreationResult&) /usr/local/src/trafficserver/iocore/net/quic/QUICPacketReceiveQueue.cc:127
    #3 0xbc47c0 in QUICNetVConnection::_dequeue_recv_packet(QUICPacketCreationResult&) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:1467
    #4 0xbb4890 in QUICNetVConnection::state_handshake(int, Event*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:566
    #5 0x5fd62c in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:160
    #6 0xbb43e5 in QUICNetVConnection::state_pre_handshake(int, Event*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:545
    #7 0x5fd62c in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:160
    #8 0xbb745f in QUICNetVConnection::net_read_io(NetHandler*, EThread*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:768
    #9 0xb73765 in NetHandler::process_ready_list() /usr/local/src/trafficserver/iocore/net/UnixNet.cc:395
    #10 0xb74fb2 in NetHandler::waitForActivity(long) /usr/local/src/trafficserver/iocore/net/UnixNet.cc:528
    #11 0xcc5888 in EThread::execute_regular() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:273
    #12 0xcc60a9 in EThread::execute() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:326
    #13 0xcc2789 in spawn_thread_internal /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:85
    #14 0x7faf3c0d836c in start_thread (/lib64/libpthread.so.0+0x736c)
    #15 0x7faf3b352b4e in __clone (/lib64/libc.so.6+0x110b4e)

0x61a000010164 is located 0 bytes to the right of 1252-byte region [0x61a00000fc80,0x61a000010164)
allocated by thread T9 ([ET_NET 7]) here:
    #0 0x7faf3dd96850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0x7faf3da28e74 in ats_malloc /usr/local/src/trafficserver/lib/ts/ink_memory.cc:59
    #2 0x7faf3da293f5 in ats_unique_malloc(unsigned long) /usr/local/src/trafficserver/lib/ts/ink_memory.cc:167
    #3 0xc8bfdc in QUICPacketReceiveQueue::dequeue(QUICPacketCreationResult&) /usr/local/src/trafficserver/iocore/net/quic/QUICPacketReceiveQueue.cc:81
    #4 0xbc47c0 in QUICNetVConnection::_dequeue_recv_packet(QUICPacketCreationResult&) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:1467
    #5 0xbb4890 in QUICNetVConnection::state_handshake(int, Event*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:566
    #6 0x5fd62c in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:160
    #7 0xbb43e5 in QUICNetVConnection::state_pre_handshake(int, Event*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:545
    #8 0x5fd62c in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:160
    #9 0xbb745f in QUICNetVConnection::net_read_io(NetHandler*, EThread*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:768
    #10 0xb73765 in NetHandler::process_ready_list() /usr/local/src/trafficserver/iocore/net/UnixNet.cc:395
    #11 0xb74fb2 in NetHandler::waitForActivity(long) /usr/local/src/trafficserver/iocore/net/UnixNet.cc:528
    #12 0xcc5888 in EThread::execute_regular() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:273
    #13 0xcc60a9 in EThread::execute() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:326
    #14 0xcc2789 in spawn_thread_internal /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:85
    #15 0x7faf3c0d836c in start_thread (/lib64/libpthread.so.0+0x736c)

Thread T9 ([ET_NET 7]) created by T0 ([TS_MAIN]) here:
    #0 0x7faf3dcefa2f in pthread_create (/lib64/libasan.so.4+0x37a2f)
    #1 0xcc201e in ink_thread_create ../../lib/ts/ink_thread.h:155
    #2 0xcc28b7 in Thread::start(char const*, void*, unsigned long, std::function<void ()> const&) /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:102
    #3 0xccc02f in EventProcessor::spawn_event_threads(int, int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:383
    #4 0xccc8d6 in EventProcessor::start(int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:446
    #5 0x6534b7 in main /usr/local/src/trafficserver/proxy/Main.cc:1842
    #6 0x7faf3b262889 in __libc_start_main (/lib64/libc.so.6+0x20889)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.4+0x79432)
Shadow bytes around the buggy address:
  0x0c347fff9fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fff9fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fff9ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fffa000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c347fffa010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c347fffa020: 00 00 00 00 00 00 00 00 00 00 00 00[04]fa fa fa
  0x0c347fffa030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c347fffa040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c347fffa050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c347fffa060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c347fffa070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==887==ABORTING
```
Client was picoquic and it sent draft-12 CI with (V=FF00000C).

**Comment by masaori335** [comment]
For workaround, this is fixed by https://github.com/apache/trafficserver/commit/aea857dc20a372e72c769b8381dbb764bf233e15.

**Comment by masaori335** [comment]
The definition of payload length is changed by draft-12 + 1389. We should ignore all version unmatched packets. Probably, it's time to refactor QUICPacket class.



https://github.com/quicwg/base-drafts/blob/master/draft-ietf-quic-invariants.md
