### ISSUE TITLE
ASan: QUICNetVConnection::_unschedule_path_validation_timeout()

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#3774]
```
[Jun  4 07:00:46.232] {0x7fe9c1cf7700} DEBUG: <QUICPacket.cc:730 (create)> (quic_packet)                    [00000000-1f26e114] Decrypting PROTECTED packet #126816428 using PHASE_0
[Jun  4 07:00:46.232] {0x7fe9c1cf7700} DEBUG: <QUICNetVConnection.cc:1504 (_dequeue_rec> (quic_net)                       [1b104fe5-1f26e114] Dequeue PROTECTED pkt_num=126816428 size=54
[Jun  4 07:00:46.233] {0x7fe9c1cf7700} DEBUG: <QUICFrameDispatcher.cc:65 (receive_frame> (quic_net)                       [1b104fe5-1f26e114] [RX] type=CONNECTION_CLOSE size=18
[Jun  4 07:00:46.233] {0x7fe9c1cf7700} DEBUG: <QUICNetVConnection.cc:1346 (_recv_and_ac> (quic_flow_ctrl)                 [1b104fe5-1f26e114] [LOCAL] 7/131072
[Jun  4 07:00:47.222] {0x7fe9c2f8e700} DEBUG: <QUICNetVConnection.cc:443 (retransmit_pa> (quic_net)                       [1b104fe5-1f26e114] Retransmit packet #3207176893 type PROTECTED
[Jun  4 07:00:47.222] {0x7fe9c2f8e700} DEBUG: <QUICNetVConnection.cc:443 (retransmit_pa> (quic_net)                       [1b104fe5-1f26e114] Retransmit packet #3207176894 type HANDSHAKE
[Jun  4 07:00:47.222] {0x7fe9c2f8e700} DEBUG: <QUICNetVConnection.cc:443 (retransmit_pa> (quic_net)                       [1b104fe5-1f26e114] Retransmit packet #3207176895 type PROTECTED
[Jun  4 07:00:47.222] {0x7fe9c2f8e700} DEBUG: <QUICCongestionController.cc:100 (on_pack> (quic_cc)                        [1b104fe5-1f26e114] window: 2920 bytes: 0 ssthresh: 2920 packet lost, window changed
[Jun  4 07:00:47.222] {0x7fe9c2f8e700} DEBUG: <QUICLossDetector.cc:358 (_on_loss_detect> (quic_loss_detector)             [1b104fe5-1f26e114] Unacked packets 0 (retransmittable 0, includes 0 handshake packets)
[Jun  4 07:00:47.222] {0x7fe9c2f8e700} DEBUG: <QUICLossDetector.cc:282 (_set_loss_detec> (quic_loss_detector)             [1b104fe5-1f26e114] Loss detection alarm has been unset
ASAN:DEADLYSIGNAL
=================================================================
==20925==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000bc74ab bp 0x7fe9c1cf6630 sp 0x7fe9c1cf6620 T9)
==20925==The signal is caused by a READ memory access.
==20925==Hint: address points to the zero page.
    #0 0xbc74aa in QUICNetVConnection::_unschedule_path_validation_timeout() /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:1629
    #1 0xbc9b70 in QUICNetVConnection::_switch_to_close_state() /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:1750
    #2 0xbb6998 in QUICNetVConnection::state_connection_draining(int, Event*) /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:711
    #3 0x5fd62c in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:160
    #4 0xcc4545 in EThread::process_event(Event*, int) /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:132
    #5 0xcc5491 in EThread::execute_regular() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:245
    #6 0xcc60a9 in EThread::execute() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:326
    #7 0xcc2789 in spawn_thread_internal /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:85
    #8 0x7fe9ca42d36c in start_thread (/lib64/libpthread.so.0+0x736c)
    #9 0x7fe9c96a7b4e in __clone (/lib64/libc.so.6+0x110b4e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/local/src/trafficserver/iocore/net/QUICNetVConnection.cc:1629 in QUICNetVConnection::_unschedule_path_validation_timeout()
Thread T9 ([ET_NET 7]) created by T0 ([TS_MAIN]) here:
    #0 0x7fe9cc044a2f in pthread_create (/lib64/libasan.so.4+0x37a2f)
    #1 0xcc201e in ink_thread_create ../../lib/ts/ink_thread.h:155
    #2 0xcc28b7 in Thread::start(char const*, void*, unsigned long, std::function<void ()> const&) /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:102
    #3 0xccc02f in EventProcessor::spawn_event_threads(int, int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:383
    #4 0xccc8d6 in EventProcessor::start(int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:446
    #5 0x6534b7 in main /usr/local/src/trafficserver/proxy/Main.cc:1842
    #6 0x7fe9c95b7889 in __libc_start_main (/lib64/libc.so.6+0x20889)

==20925==ABORTING
```

**Comment by maskit** [comment]
Should be fixed by 7b8f86e28457b96d2aa61e70be0b92bd99a03546
