### ISSUE TITLE
ATS 8.0.0 core with 100 continue

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#3836]
Coredump with ATS 8.0.0 running in debug mode:

```
(gdb) bt
#0  0x00002b244fabc1d7 in raise () from /lib64/libc.so.6
#1  0x00002b244fabd8c8 in abort () from /lib64/libc.so.6
#2  0x00002b244d4c0ba9 in ink_abort (message_format=0x2b244d4ec38c "%s:%d: failed assertion `%s`") at ../../../../trafficserver/lib/ts/ink_error.cc:99
#3  0x00002b244d4bdfac in _ink_assert (expression=0x81d426 "active == false", file=0x81d228 "../../../../trafficserver/proxy/http/HttpTunnel.cc", line=530) at ../../../../trafficserver/lib/ts/ink_assert.cc:37
#4  0x00000000005e8d27 in HttpTunnel::reset (this=0x2b24ccb21790) at ../../../../trafficserver/proxy/http/HttpTunnel.cc:530
#5  0x000000000059e575 in HttpSM::setup_100_continue_transfer (this=0x2b24ccb208c0) at ../../../../trafficserver/proxy/http/HttpSM.cc:6164
#6  0x00000000005a31c2 in HttpSM::set_next_state (this=0x2b24ccb208c0) at ../../../../trafficserver/proxy/http/HttpSM.cc:7368
#7  0x00000000005a22e3 in HttpSM::call_transact_and_set_next_state (this=0x2b24ccb208c0, f=0x0) at ../../../../trafficserver/proxy/http/HttpSM.cc:7156
#8  0x000000000058aedc in HttpSM::handle_api_return (this=0x2b24ccb208c0) at ../../../../trafficserver/proxy/http/HttpSM.cc:1589
#9  0x000000000058ac74 in HttpSM::state_api_callout (this=0x2b24ccb208c0, event=60000, data=0x0) at ../../../../trafficserver/proxy/http/HttpSM.cc:1524
#10 0x0000000000589e74 in HttpSM::state_api_callback (this=0x2b24ccb208c0, event=60000, data=0x0) at ../../../../trafficserver/proxy/http/HttpSM.cc:1291
#11 0x0000000000539e7c in TSHttpTxnReenable (txnp=0x2b24ccb208c0, event=TS_EVENT_HTTP_CONTINUE) at ../../../trafficserver/src/traffic_server/InkAPI.cc:5905
#12 0x00002b24675aa15f in handle_response (txnp=0x2b24ccb208c0) at ../../../trafficserver/plugins/experimental/custom_redirect/custom_redirect.cc:87
#13 0x00002b24675aa1b2 in plugin_main_handler (contp=0x1aa8f50, event=TS_EVENT_HTTP_READ_RESPONSE_HDR, edata=0x2b24ccb208c0) at ../../../trafficserver/plugins/experimental/custom_redirect/custom_redirect.cc:97
#14 0x000000000052da6c in INKContInternal::handle_event (this=0x1aa8f50, event=60006, edata=0x2b24ccb208c0) at ../../../trafficserver/src/traffic_server/InkAPI.cc:1070

(gdb) p active
$7 = true
(gdb) p consumers[0].alive
$8 = true
(gdb) p producers[0].alive
$9 = true
```

**Comment by bryancall** [comment]
If this is still an issue please reopen.
