### ISSUE TITLE
ATS 8.0.0 coredump with inactivity cop

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#3837]
```
(gdb) bt
#0  0x00002b333aa8c1d7 in raise () from /lib64/libc.so.6
#1  0x00002b333aa8d8c8 in abort () from /lib64/libc.so.6
#2  0x00002b33384921fe in ink_abort (message_format=0x2b33384bca6c "%s:%d: failed assertion `%s`") at ../../../../trafficserver/lib/ts/ink_error.cc:99
#3  0x00002b333848f668 in _ink_assert (expression=0x7e7b06 "magic == HTTP_SM_MAGIC_ALIVE", file=0x7e75a8 "../../../../trafficserver/proxy/http/HttpSM.cc", line=2538) at ../../../../trafficserver/lib/ts/ink_assert.cc:37
#4  0x000000000058b60b in HttpSM::main_handler (this=0x2b33c82a2980, event=105, data=0x2b3530047a60) at ../../../../trafficserver/proxy/http/HttpSM.cc:2538
#5  0x000000000052874e in Continuation::handleEvent (this=0x2b33c82a2980, event=105, data=0x2b3530047a60) at /home/bcall/dev/yahoo/build_8/_build/ats_build/../../trafficserver/iocore/eventsystem/I_Continuation.h:160
#6  0x0000000000794b07 in read_signal_and_update (event=105, vc=0x2b3530047910) at ../../../../trafficserver/iocore/net/UnixNetVConnection.cc:83
#7  0x0000000000798273 in UnixNetVConnection::mainEvent (this=0x2b3530047910, event=1, e=0x2abc580) at ../../../../trafficserver/iocore/net/UnixNetVConnection.cc:1189
#8  0x0000000000798283 in UnixNetVConnection::mainEvent (this=0x2b6138130800, event=1, e=0xde5ce0) at ../../../../trafficserver/iocore/net/UnixNetVConnection.cc:1189
#9  0x000000000052874e in Continuation::handleEvent (this=0x2b6138130800, event=1, data=0xde5ce0) at /home/bcall/dev/yahoo/build_8/_build/ats_build/../../trafficserver/iocore/eventsystem/I_Continuation.h:160
#10 0x000000000078d4ec in InactivityCop::check_inactivity (this=0x2b5f680008c0, event=2, e=0xde5ce0) at ../../../../trafficserver/iocore/net/UnixNet.cc:81

(gdb) p vc->is_internal_request
$3 = false
(gdb) p vc->id
$4 = 0
(gdb) p vc->is_transparent
$5 = false
(gdb) p vc->inactivity_timeout_in
$6 = 60000000000

(gdb) p terminate_sm
$30 = true
(gdb) p kill_this_async_done
$31 = true
(gdb) p/x magic
$33 = 0xdeadfeed
```

**Comment by zwoop** [comment]
I'm seeing something similar with 7.1.4 (latest build) too:

```
(gdb) bt full
#0  0x00002ba5f5eee86d in waitpid () from /lib64/libc.so.6
No symbol table info available.
#1  0x00005623b4665e04 in crash_logger_invoke (signo=6, info=0x2ba5fbf0b630, ctx=0x2ba5fbf0b500) at Crash.cc:164
        status = 0
#2  <signal handler called>
No symbol table info available.
#3  0x00002ba5f5e74495 in raise () from /lib64/libc.so.6
No symbol table info available.
#4  0x00002ba5f5e75c75 in abort () from /lib64/libc.so.6
No symbol table info available.
#5  0x00002ba5f32ef4a4 in ink_abort (message_format=<optimized out>) at ink_error.cc:99
        ap = {{
            gp_offset = 32,
            fp_offset = 48,
            overflow_arg_area = 0x2ba5fbf0bca0,
            reg_save_area = 0x2ba5fbf0bbc0
          }}
#6  0x00002ba5f32ed375 in _ink_assert (expression=0x2ba5f5e74495 <raise+53> "H=", file=0x9b9c <error: Cannot access memory at address 0x9b9c>, line=6) at ink_assert.cc:37
No locals.
#7  0x00005623b473e5e6 in HttpSM::main_handler (this=0x2bae3731d8e0, event=2301, data=0x2bae3731ec80) at HttpSM.cc:2610
        jump_point = <optimized out>
#8  0x00005623b478ff14 in Continuation::handleEvent (this=<optimized out>, event=2301, data=<optimized out>) at /usr/src/debug/bazinga-trafficserver-7.1.4/iocore/eventsystem/I_Continuation.h:152
No locals.
#9  HttpTunnel::main_handler (this=0x2bae3731ec80, event=<optimized out>, data=<optimized out>) at HttpTunnel.cc:1651
        p = <optimized out>
        c = <optimized out>
#10 0x00005623b48e8486 in Continuation::handleEvent (this=<optimized out>, event=103, data=<optimized out>) at ./I_Continuation.h:152
No locals.
#11 EThread::process_event (this=0x2ba5f8e0da40, e=0x2ba6fffd6800, calling_code=103) at UnixEThread.cc:140
        c_temp = <optimized out>
#12 0x00005623b48e8774 in EThread::process_queue (this=0x2ba5f8e0da40, NegativeQueue=0x2ba5fbf0bdd0) at UnixEThread.cc:175
No locals.
#13 0x00005623b48e8a3c in EThread::execute_regular (this=0x2ba5f8e0da40) at UnixEThread.cc:207
        done_one = <optimized out>
        sleep_time = <optimized out>
        next_time = 0
        NegativeQueue = {
          <DLL<Event, Event::Link_link>> = {
            head = 0x0
          },
          members of Queue<Event, Event::Link_link>:
          tail = 0x0
        }
#14 0x00005623b48e7b97 in spawn_thread_internal (a=0x2ba5f73b49f0) at Thread.cc:84
        p = 0x2ba5f73b49f0
#15 0x00002ba5f61ddaa1 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#16 0x00002ba5f5f2abcd in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb) frame 7
#7  0x00005623b473e5e6 in HttpSM::main_handler (this=0x2bae3731d8e0, event=2301, data=0x2bae3731ec80) at HttpSM.cc:2610
2610	  ink_release_assert(magic == HTTP_SM_MAGIC_ALIVE);
(gdb) print history
$3 = {{
    fileline = 0x5623b49089f2 "HttpSM.cc:638",
    event = 100,
    reentrancy = 2
  }, {
    fileline = 0x5623b49089f2 "HttpSM.cc:638",
    event = 100,
    reentrancy = 1
  }, {
    fileline = 0x5623b4908e4c "HttpSM.cc:1307",
    event = 60000,
    reentrancy = 2
  }, {
    fileline = 0x5623b4908e77 "HttpSM.cc:1347",
    event = 60000,
    reentrancy = 2
  }, {
    fileline = 0x5623b4908e4c "HttpSM.cc:1307",
    event = 60000,
    reentrancy = 3
  }, {
    fileline = 0x5623b4908e77 "HttpSM.cc:1347",
    event = 60000,
    reentrancy = 3
  }, {
    fileline = 0x5623b4908e4c "HttpSM.cc:1307",
    event = 60000,
    reentrancy = 4
  }, {
    fileline = 0x5623b4908e77 "HttpSM.cc:1347",
    event = 60000,
    reentrancy = 4
  }, {
    fileline = 0x5623b4908e4c "HttpSM.cc:1307",
    event = 60000,
    reentrancy = 5
  }, {
    fileline = 0x5623b4908e77 "HttpSM.cc:1347",
    event = 60000,
    reentrancy = 5
  }, {
    fileline = 0x5623b490b5ef "HttpSM.cc:7401",
    event = 65535,
    reentrancy = 5
  }, {
    fileline = 0x5623b4903ff1 "HttpCacheSM.cc:118",
    event = 1102,
    reentrancy = -1
  }, {
    fileline = 0x5623b49095b5 "HttpSM.cc:2549",
    event = 1102,
    reentrancy = 6
  }, {
    fileline = 0x5623b4908e4c "HttpSM.cc:1307",
    event = 60000,
    reentrancy = 7
  }, {
    fileline = 0x5623b4908e77 "HttpSM.cc:1347",
    event = 60000,
    reentrancy = 7
  }, {
    fileline = 0x5623b4908e4c "HttpSM.cc:1307",
    event = 60000,
    reentrancy = 8
  }, {
    fileline = 0x5623b4908e77 "HttpSM.cc:1347",
    event = 60000,
    reentrancy = 8
  }, {
    fileline = 0x5623b4908e4c "HttpSM.cc:1307",
    event = 60000,
    reentrancy = 9
  }, {
    fileline = 0x5623b4908e77 "HttpSM.cc:1347",
    event = 60000,
    reentrancy = 9
  }, {
    fileline = 0x5623b490ab92 "HttpSM.cc:6133",
    event = 65535,
    reentrancy = 9
  }, {
    fileline = 0x5623b4909a5d "HttpSM.cc:3363",
    event = 102,
    reentrancy = 5
  }, {
    fileline = 0x5623b490a2bd "HttpSM.cc:4551",
    event = 0,
    reentrancy = 5
  }, {
    fileline = 0x0,
    event = 0,
    reentrancy = 0
  } <repeats 42 times>}
```

**Comment by bryancall** [comment]
This was fixed after revert
