### ISSUE TITLE
ATS 8.0.x assert in HttpServerSession::get_server_ip

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#3936]
```
(gdb) bt
#0  0x00002b03848631d7 in raise () from /lib64/libc.so.6
#1  0x00002b03848648c8 in abort () from /lib64/libc.so.6
#2  0x00002b03821f947e in ink_abort (message_format=0x2b03822630cc "%s:%d: failed assertion `%s`") at ../../../../trafficserver/lib/ts/ink_error.cc:99
#3  0x00002b03821f68e8 in _ink_assert (expression=0x7af489 "server_vc != nullptr", file=0x7af448 "../../../../trafficserver/proxy/http/../http/HttpServerSession.h", line=136) at ../../../../trafficserver/lib/ts/ink_assert.cc:37
#4  0x00000000005adcaf in HttpServerSession::get_server_ip (this=0x2b03b00aff40) at ../../../../trafficserver/proxy/http/../http/HttpServerSession.h:136
#5  0x00000000005b57c6 in ServerSessionPool::IPHashing::key (value=0x2b03b00aff40) at ../../../../trafficserver/proxy/http/HttpSessionManager.h:85
#6  0x00000000005b7023 in TSHashTable<ServerSessionPool::IPHashing>::Location::advance (this=0x2b038f7c1b80) at /home/bcall/dev/yahoo/build_8/_build/ats_build/../../trafficserver/lib/ts/Map.h:2084
#7  0x00000000005b60f8 in TSHashTable<ServerSessionPool::IPHashing>::Location::operator++ (this=0x2b038f7c1b80) at /home/bcall/dev/yahoo/build_8/_build/ats_build/../../trafficserver/lib/ts/Map.h:1839
#8  0x00000000005b4555 in ServerSessionPool::acquireSession (this=0x13660c0, addr=0x2b03c013a440, hostname_hash=..., match_style=TS_SERVER_SESSION_SHARING_MATCH_BOTH, sm=0x2b03c0139da0, to_return=@0x2b038f7c1d08: 0x0)
    at ../../../../trafficserver/proxy/http/HttpSessionManager.cc:125
#9  0x00000000005b5197 in HttpSessionManager::acquire_session (this=0xaed588 <httpSessionManager>, ip=0x2b03c013a440, hostname=0x2b040f8db819 "ym.zenfs.com", ua_txn=0x2b040402c898, sm=0x2b03c0139da0)
    at ../../../../trafficserver/proxy/http/HttpSessionManager.cc:325
#10 0x000000000059f8f1 in HttpSM::do_http_server_open (this=0x2b03c0139da0, raw=false) at ../../../../trafficserver/proxy/http/HttpSM.cc:4753
```

**Comment by bryancall** [comment]
I believe this was resolved after reverting some changes on the 8.0.x branch.
