### ISSUE TITLE
Crashes when enabled HTTP/2 priority

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#4057]
Set  proxy.config.http2.stream_priority_enabled to enable HTTP/2 priority processing.  Within an hour we had two core files.

```
(gdb) bt
#0  0x00002aea8ec411d7 in raise () from /lib64/libc.so.6
#1  0x00002aea8ec428c8 in abort () from /lib64/libc.so.6
#2  0x00002aea8c15e277 in ink_abort (message_format=0x2aea8c186fe0 "%s:%d: failed assertion `%s`") at ../../../../trafficserver/lib/ts/ink_error.cc:99
#3  0x00002aea8c15b3c7 in _ink_assert (expression=0x852f77 "node->parent != nullptr", file=0x852e60 "../../../../trafficserver/proxy/http2/Http2DependencyTree.h", line=319)
    at ../../../../trafficserver/lib/ts/ink_assert.cc:37
#4  0x00000000006abd99 in Http2DependencyTree::Tree<Http2Stream*>::_change_parent (this=0x2aeaa9c96fb0, node=0x2aeaa940cf00, new_parent=0x2aeaaa4f8370, exclusive=false)
    at ../../../../trafficserver/proxy/http2/Http2DependencyTree.h:319
#5  0x00000000006ab42e in Http2DependencyTree::Tree<Http2Stream*>::reprioritize (this=0x2aeaa9c96fb0, node=0x2aeaaac35780, new_parent_id=0, exclusive=true)
    at ../../../../trafficserver/proxy/http2/Http2DependencyTree.h:305
#6  0x00000000006a3d2d in rcv_priority_frame (cstate=..., frame=...) at ../../../../trafficserver/proxy/http2/Http2ConnectionState.cc:423
#7  0x00000000006a615f in Http2ConnectionState::main_event_handler (this=0x2aeed40e5080, event=2253, edata=0x2aea968b4910) at ../../../../trafficserver/proxy/http2/Http2ConnectionState.cc:927
#8  0x0000000000551968 in Continuation::handleEvent (this=0x2aeed40e5080, event=2253, data=0x2aea968b4910)
    at /var/builds/workspace/157188-v3-component/BUILD_CONTAINER/rhel7-gcc6_2/label/DOCKER-HIGH/app_root/_build/ats_build/../../trafficserver/iocore/eventsystem/I_Continuation.h:153
#9  0x000000000069e6a1 in send_connection_event (cont=0x2aeed40e5080, event=2253, edata=0x2aea968b4910) at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:58
#10 0x00000000006a0b09 in Http2ClientSession::do_complete_frame_read (this=0x2aeed40e4de0) at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:494
#11 0x00000000006a0cf9 in Http2ClientSession::state_process_frame_read (this=0x2aeed40e4de0, event=100, vio=0x2aedfc23fdf0, inside_frame=false)
    at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:531
#12 0x00000000006a02be in Http2ClientSession::state_start_frame_read (this=0x2aeed40e4de0, event=100, edata=0x2aedfc23fdf0) at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:424
#13 0x000000000069fa1e in Http2ClientSession::main_event_handler (this=0x2aeed40e4de0, event=100, edata=0x2aedfc23fdf0) at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:324
#14 0x0000000000551968 in Continuation::handleEvent (this=0x2aeed40e4de0, event=100, data=0x2aedfc23fdf0)
    at /var/builds/workspace/157188-v3-component/BUILD_CONTAINER/rhel7-gcc6_2/label/DOCKER-HIGH/app_root/_build/ats_build/../../trafficserver/iocore/eventsystem/I_Continuation.h:153
#15 0x00000000007e84b6 in read_signal_and_update (event=100, vc=0x2aedfc23fca0) at ../../../../trafficserver/iocore/net/UnixNetVConnection.cc:144
#16 0x00000000007eb4ec in UnixNetVConnection::readSignalAndUpdate (this=0x2aedfc23fca0, event=100) at ../../../../trafficserver/iocore/net/UnixNetVConnection.cc:1095
#17 0x00000000007c2aea in SSLNetVConnection::net_read_io (this=0x2aedfc23fca0, nh=0x2aea94644cf0, lthread=0x2aea94641010) at ../../../../trafficserver/iocore/net/SSLNetVConnection.cc:607
#18 0x00000000007dfdfd in NetHandler::waitForActivity (this=0x2aea94644cf0, timeout=39999854) at ../../../../trafficserver/iocore/net/UnixNet.cc:497
#19 0x000000000080d670 in EThread::execute_regular (this=0x2aea94641010) at ../../../../trafficserver/iocore/eventsystem/UnixEThread.cc:272
#20 0x000000000080d837 in EThread::execute (this=0x2aea94641010) at ../../../../trafficserver/iocore/eventsystem/UnixEThread.cc:325
#21 0x000000000080c46c in spawn_thread_internal (a=0x1f36db0) at ../../../../trafficserver/iocore/eventsystem/Thread.cc:85
#22 0x00002aea8dfd4dc5 in start_thread () from /lib64/libpthread.so.0
#23 0x00002aea8ed0376d in clone () from /lib64/libc.so.6
```

and 

```
(gdb) bt
#0  0x00002b4ada5d61d7 in raise () from /lib64/libc.so.6
#1  0x00002b4ada5d78c8 in abort () from /lib64/libc.so.6
#2  0x00002b4ad7af3277 in ink_abort (message_format=0x2b4ad7b1bfe0 "%s:%d: failed assertion `%s`") at ../../../../trafficserver/lib/ts/ink_error.cc:99
#3  0x00002b4ad7af03c7 in _ink_assert (expression=0x852f4e "entry->index < _v.length()", 
    file=0x852eb0 "/var/builds/workspace/157188-v3-component/BUILD_CONTAINER/rhel7-gcc6_2/label/DOCKER-HIGH/app_root/_build/ats_build/../../trafficserver/lib/ts/PriorityQueue.h", line=142)
    at ../../../../trafficserver/lib/ts/ink_assert.cc:37
#4  0x00000000006abbb6 in PriorityQueue<Http2DependencyTree::Node*, PriorityQueueLess<Http2DependencyTree::Node*> >::erase (this=0x2b5278167c60, entry=0x2b552f7ba3c0)
    at /var/builds/workspace/157188-v3-component/BUILD_CONTAINER/rhel7-gcc6_2/label/DOCKER-HIGH/app_root/_build/ats_build/../../trafficserver/lib/ts/PriorityQueue.h:142
#5  0x00000000006ab659 in Http2DependencyTree::Tree<Http2Stream*>::deactivate (this=0x2b4b4d432ac0, node=0x2b4b4e0a8be0, sent=0)
    at ../../../../trafficserver/proxy/http2/Http2DependencyTree.h:405
#6  0x00000000006a6feb in Http2ConnectionState::delete_stream (this=0x2b568b05b9a0, stream=0x2b527ac33ac0) at ../../../../trafficserver/proxy/http2/Http2ConnectionState.cc:1163
#7  0x00000000006a4272 in rcv_rst_stream_frame (cstate=..., frame=...) at ../../../../trafficserver/proxy/http2/Http2ConnectionState.cc:490
#8  0x00000000006a615f in Http2ConnectionState::main_event_handler (this=0x2b568b05b9a0, event=2253, edata=0x2b4b383a4910) at ../../../../trafficserver/proxy/http2/Http2ConnectionState.cc:927
#9  0x0000000000551968 in Continuation::handleEvent (this=0x2b568b05b9a0, event=2253, data=0x2b4b383a4910)
    at /var/builds/workspace/157188-v3-component/BUILD_CONTAINER/rhel7-gcc6_2/label/DOCKER-HIGH/app_root/_build/ats_build/../../trafficserver/iocore/eventsystem/I_Continuation.h:153
#10 0x000000000069e6a1 in send_connection_event (cont=0x2b568b05b9a0, event=2253, edata=0x2b4b383a4910) at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:58
#11 0x00000000006a0b09 in Http2ClientSession::do_complete_frame_read (this=0x2b568b05b700) at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:494
#12 0x00000000006a0cf9 in Http2ClientSession::state_process_frame_read (this=0x2b568b05b700, event=100, vio=0x2b4e42ddcb30, inside_frame=false)
    at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:531
#13 0x00000000006a02be in Http2ClientSession::state_start_frame_read (this=0x2b568b05b700, event=100, edata=0x2b4e42ddcb30) at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:424
#14 0x000000000069fa1e in Http2ClientSession::main_event_handler (this=0x2b568b05b700, event=100, edata=0x2b4e42ddcb30) at ../../../../trafficserver/proxy/http2/Http2ClientSession.cc:324
#15 0x0000000000551968 in Continuation::handleEvent (this=0x2b568b05b700, event=100, data=0x2b4e42ddcb30)
    at /var/builds/workspace/157188-v3-component/BUILD_CONTAINER/rhel7-gcc6_2/label/DOCKER-HIGH/app_root/_build/ats_build/../../trafficserver/iocore/eventsystem/I_Continuation.h:153
#16 0x00000000007e84b6 in read_signal_and_update (event=100, vc=0x2b4e42ddc9e0) at ../../../../trafficserver/iocore/net/UnixNetVConnection.cc:144
#17 0x00000000007eb4ec in UnixNetVConnection::readSignalAndUpdate (this=0x2b4e42ddc9e0, event=100) at ../../../../trafficserver/iocore/net/UnixNetVConnection.cc:1095
#18 0x00000000007c2aea in SSLNetVConnection::net_read_io (this=0x2b4e42ddc9e0, nh=0x2b4ae1507cf0, lthread=0x2b4ae1504010) at ../../../../trafficserver/iocore/net/SSLNetVConnection.cc:607
#19 0x00000000007dfdfd in NetHandler::waitForActivity (this=0x2b4ae1507cf0, timeout=19999267) at ../../../../trafficserver/iocore/net/UnixNet.cc:497
#20 0x000000000080d670 in EThread::execute_regular (this=0x2b4ae1504010) at ../../../../trafficserver/iocore/eventsystem/UnixEThread.cc:272
#21 0x000000000080d837 in EThread::execute (this=0x2b4ae1504010) at ../../../../trafficserver/iocore/eventsystem/UnixEThread.cc:325
#22 0x000000000080c46c in spawn_thread_internal (a=0x1fd3800) at ../../../../trafficserver/iocore/eventsystem/Thread.cc:85
#23 0x00002b4ad9969dc5 in start_thread () from /lib64/libpthread.so.0
#24 0x00002b4ada69876d in clone () from /lib64/libc.so.6
```

**Comment by zwoop** [comment]
I believe this is fixed now.
