### ISSUE TITLE
jemalloc crash while calling LogField destructor (happens when trafficserver stops)

### ISSUE THREAD

**Issue by Nishant-Gaurav** [apache/trafficserver#4416]
I see 2 different types of crashes when stopping trafficserver (6.2.1). These happen frequently

**Crash 1:**

```
(gdb) bt
#0  0x00002ad064019eae in je_arena_dalloc_bin_locked () from /usr/bin/../lib64/libjemalloc.so.1
#1  0x00002ad064032881 in je_tcache_bin_flush_small () from /usr/bin/../lib64/libjemalloc.so.1
#2  0x00002ad064010640 in free () from /usr/bin/../lib64/libjemalloc.so.1
#3  0x000000000062dfce in ~LogFieldAliasTableEntry (this=0x2ad067c28da8, __in_chrg=<optimized out>) at ../../proxy/logging/LogFieldAliasMap.h:115
#4  ~LogFieldAliasTable (this=0x2ad067f19550, __in_chrg=<optimized out>) at ../../proxy/logging/LogFieldAliasMap.h:130
#5  LogFieldAliasTable::~LogFieldAliasTable (this=0x2ad067f19550, __in_chrg=<optimized out>) at ../../proxy/logging/LogFieldAliasMap.h:130
#6  0x000000000063cb2c in ~Ptr (this=0x2ad068ffe1c0, __in_chrg=<optimized out>) at ../../lib/ts/Ptr.h:379
#7  ~LogField (this=0x2ad068ffe160, __in_chrg=<optimized out>) at LogField.cc:364
#8  clear (this=0xa8a090 <Log::global_field_list>) at LogField.cc:667
#9  LogFieldList::~LogFieldList (this=0xa8a090 <Log::global_field_list>, __in_chrg=<optimized out>) at LogField.cc:659
#10 0x00002ad0658aea49 in __run_exit_handlers () from /lib64/libc.so.6
#11 0x00002ad0658aea95 in exit () from /lib64/libc.so.6
#12 0x00002ad065897b3c in __libc_start_main () from /lib64/libc.so.6
#13 0x000000000049cb6c in _start ()
```

**Crash 2:**
```
(gdb) bt
#0  0x00002b4b46688eae in je_arena_dalloc_bin_locked () from /usr/bin/../lib64/libjemalloc.so.1
#1  0x00002b4b466a1881 in je_tcache_bin_flush_small () from /usr/bin/../lib64/libjemalloc.so.1
#2  0x00002b4b4667f640 in free () from /usr/bin/../lib64/libjemalloc.so.1
#3  0x000000000063cad5 in ~LogField (this=0x2b4b4a0a12e0, __in_chrg=<optimized out>) at LogField.cc:366
#4  clear (this=0xa8a090 <Log::global_field_list>) at LogField.cc:667
#5  LogFieldList::~LogFieldList (this=0xa8a090 <Log::global_field_list>, __in_chrg=<optimized out>) at LogField.cc:659
#6  0x00002b4b47f1da49 in __run_exit_handlers () from /lib64/libc.so.6
#7  0x00002b4b47f1da95 in exit () from /lib64/libc.so.6
#8  0x00002b4b47f06b3c in __libc_start_main () from /lib64/libc.so.6
#9  0x000000000049cb6c in _start ()
```

Has any one similar crashes? Any help or pointers debugging this will be very helpful.

**Comment by bryancall** [comment]
I haven't seen this before.  What version are you running?  If this is still an issue please reopen.
