### ISSUE TITLE
ATS 8.0.3 - asserting on magic == HTTP_SM_MAGIC_ALIVE

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#4970]
```
(gdb) bt full
#0  0x00002aaaadd121d7 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00002aaaadd138c8 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00002aaaaad29a3b in ink_abort (message_format=message_format@entry=0x2aaaaad906a7 "%s:%d: failed assertion `%s`") at ink_error.cc:99
        ap = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x2aaabb3fe570, reg_save_area = 0x2aaabb3fe4b0}}
#3  0x00002aaaaad27525 in _ink_assert (expression=expression@entry=0x735706 "magic == HTTP_SM_MAGIC_ALIVE", file=file@entry=0x7350d6 "HttpSM.cc", line=line@entry=2516) at ink_assert.cc:37
No locals.
#4  0x000000000050f767 in HttpSM::main_handler (this=<optimized out>, event=<optimized out>, data=<optimized out>) at HttpSM.cc:2516
        __FUNCTION__ = "main_handler"
#5  0x0000000000557969 in handleEvent (data=0x2aaca5780258, event=2301, this=<optimized out>) at /home/bcall/dev/yahoo/build/_build/build_debug_posix-x86_64_gcc_8/trafficserver8/iocore/eventsystem/I_Continuation.h:160
No locals.
#6  HttpTunnel::main_handler (this=0x2aaca5780258, event=<optimized out>, data=<optimized out>) at HttpTunnel.cc:1643
        p = <optimized out>
        c = <optimized out>
        sm_callback = <optimized out>
#7  0x000000000071a4b2 in handleEvent (data=0x2aabe1e51500, event=103, this=<optimized out>) at I_Continuation.h:160
No locals.
#8  EThread::process_event(Event*, int) () at UnixEThread.cc:131
        c_temp = <optimized out>
        lock = {m = {m_ptr = 0x2aabf326d3b0}, lock_acquired = true}
#9  0x000000000071ae4e in EThread::process_queue (this=this@entry=0x2aaab2b9ce80, NegativeQueue=NegativeQueue@entry=0x2aaabb3fe6b0, ev_count=ev_count@entry=0x2aaabb3fe6ac, nq_count=nq_count@entry=0x2aaabb3fe6a8) at UnixEThread.cc:170
        e = 0x2aabe1e51500
#10 0x000000000071b32c in EThread::execute_regular (this=0x2aaab2b9ce80) at UnixEThread.cc:230
        done_one = <optimized out>
        sleep_time = <optimized out>
        e = <optimized out>
        NegativeQueue = {<DLL<Event, Event::Link_link>> = {head = 0x0}, tail = 0x0}
        next_time = <optimized out>
        delta = <optimized out>
        loop_start_time = 1549999116851590977
        loop_finish_time = <optimized out>
        prev_metric = 0x2aaab2c9dd70
        nq_count = 0
        ev_count = 1
        METRIC_INIT = {_loop_time = {_start = 0, _min = 9223372036854775807, _max = 0}, _events = {_min = 2147483647, _max = 0, _total = 0}, _count = 0, _wait = 0}
#11 0x0000000000719f0a in spawn_thread_internal (a=0x2aaaaef992c0) at Thread.cc:85
        p = 0x2aaaaef992c0
#12 0x00002aaaad0a5dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#13 0x00002aaaaddd476d in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by bryancall** [comment]
Close this, since it looks like #4921
