### ISSUE TITLE
ATS 8.0.3 - abort in migrateToCurrentThread

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#4977]
It is crashing on this line:
`    UnixNetVConnection *netvc = static_cast<UnixNetVConnection *>(netProcessor.allocate_vc(t));
`
```
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x2aaab4107700 (LWP 32522)]
0x00002aaaadd121d7 in raise () from /lib64/libc.so.6
(gdb) bt full
#0  0x00002aaaadd121d7 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00002aaaadd138c8 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00002aaaad51e9b5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
No symbol table info available.
#3  0x00002aaaad51c926 in ?? () from /lib64/libstdc++.so.6
No symbol table info available.
#4  0x00002aaaad51c953 in std::terminate() () from /lib64/libstdc++.so.6
No symbol table info available.
#5  0x00002aaaad51d4bf in __cxa_pure_virtual () from /lib64/libstdc++.so.6
No symbol table info available.
#6  0x00000000006e0d00 in UnixNetVConnection::migrateToCurrentThread(Continuation*, EThread*) () at UnixNetVConnection.cc:1451
        netvc = <optimized out>
        client_nh = <optimized out>
        lock = {m = {m_ptr = 0x2aaaaef2ee50}, locked_p = true}
        lock_src = {m = {m_ptr = 0x2aaaaef2ed60}, lock_acquired = false}
        sslvc = 0x0
        save_ssl = <optimized out>
        ret_vc = <optimized out>
#7  0x0000000000522576 in HttpSessionManager::acquire_session(Continuation*, sockaddr const*, char const*, ProxyClientTransaction*, HttpSM*) () at HttpSessionManager.cc:332
        new_vc = <optimized out>
        server_vc = 0x2aaee231c6d0
        ethread = 0x2aaab141ac40
        pool_mutex = <optimized out>
        lock = {m = {m_ptr = 0x2aaaaef2fe90}, lock_acquired = true}
        to_return = 0x2aaab6f7b340
        match_style = <optimized out>
        hostname_hash = {b = {7978137750836667128, 8217543274417706987}, u64 = {7978137750836667128, 8217543274417706987}, u32 = {2948653816, 1857554947, 3591460843, 1913295889},
          u8 = "\370\342\300\257\003\n\270n\353W\021\326\021\224\nr"}
        retval = HSM_NOT_FOUND
        __FUNCTION__ = "acquire_session"
#8  0x0000000000510f14 in HttpSM::do_http_server_open(bool) () at HttpSM.cc:4767
```

**Comment by bryancall** [comment]
closing for now
