### ISSUE TITLE
QUIC: segment fault in test_QUICStream.cc

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5097]
```
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00000000007a8ecf in Diags::error (this=0x611000000400, level=DL_Error, loc=0x7fffffffd630, fmt=0x864320 "check private key failed") at ../../../include/tscore/Diags.h:207
        ap = {{gp_offset = 3429799609, fp_offset = 0, overflow_arg_area = 0x6110000003f0, reg_save_area = 0x0}}
#2  0x00000000007a6378 in quic_init_server_ssl_ctx (params=0x6120000007c0) at QUICConfig.cc:82
        loc = {file = 0x8642e0 "QUICConfig.cc", func = 0x865360 <quic_init_server_ssl_ctx(QUICConfigParams const*)::__FUNCTION__> "quic_init_server_ssl_ctx", line = 82}
        ssl_ctx = 0x619000005a80
        ssl_params = {ptr = 0x0}
        __FUNCTION__ = "quic_init_server_ssl_ctx"
#3  0x00000000007a7a76 in QUICConfigParams::initialize (this=0x6120000007c0) at QUICConfig.cc:197
        timeout = 100
#4  0x00000000007a8a68 in QUICConfig::reconfigure () at QUICConfig.cc:475
        params = 0x6120000007c0
#5  0x00000000007a8a37 in QUICConfig::startup () at QUICConfig.cc:466
No locals.
#6  0x0000000000646af8 in EventProcessorListener::testRunStarting (this=0x613000000580, testRunInfo=...) at ./test/event_processor_main.cc:55
        base_log_file = 0x607000000f70
        main_thread =
    0x6abb67 <std::__get_helper<0ul, Catch::IStreamingReporter*, std::default_delete<Catch::IStreamingReporter> >(std::_Tuple_impl<0ul, Catch::IStreamingReporter*, std::default_delete<Catch::IStreamingReporter> > const&)+24>
#7  0x00000000006116e4 in Catch::MultipleReporters::testRunStarting (this=0x6030000089b0, testRunInfo=...) at /root/trafficserver_quic/tests/include/catch.hpp:12451
        reporter = std::unique_ptr<Catch::IStreamingReporter> = {get() = 0x613000000580}
        __for_range = std::vector of length 2, capacity 2 = {std::unique_ptr<Catch::IStreamingReporter> = {get() = 0x6130000003c0}, std::unique_ptr<Catch::IStreamingReporter> = {get() = 0x613000000580}}
        __for_begin = std::unique_ptr<Catch::IStreamingReporter> = {get() = 0x613000000580}
        __for_end = std::unique_ptr<Catch::IStreamingReporter> = {get() = 0x2ffffff00000002}
#8  0x00000000005dc91c in Catch::RunContext::RunContext (this=0x7fffffffde80, _config=std::shared_ptr<const Catch::IConfig> (use count 6, weak count 0) = {...}, reporter=...)
    at /root/trafficserver_quic/tests/include/catch.hpp:8562
No locals.
#9  0x00000000005e482d in Catch::(anonymous namespace)::runTests (config=std::shared_ptr<Catch::Config> (use count 6, weak count 0) = {...}) at /root/trafficserver_quic/tests/include/catch.hpp:9124
        reporter = std::unique_ptr<Catch::IStreamingReporter> = {get() = 0x0}
        context = {<Catch::IResultCapture> = {_vptr.IResultCapture = 0x850818 <vtable for Catch::RunContext+16>}, <Catch::IRunner> = {_vptr.IRunner = 0x8508d8 <vtable for Catch::RunContext+208>},
          m_runInfo = {name = "lt-test_QUICStream"}, m_context = @0x604000003a10, m_activeTestCase = 0x0, m_testCaseTracker = 0x41b58ab3, m_lastResult = {nullableValue = 0x0,
            storage = "Eci\000\000\000\000\000\300(\204\000\000\000\000\000\320\001\000\000 a\000\000B\000\000\000\000\000\000\000\200\016\000\000p`\000\000\270\341\377\377\377\177\000\000 \337\377\377\377\177\000\000\330\302f\000\000\000\000\000\060\337\377\377\377\177\000\000\000\312\024:n\323\067X(\344\377\377\377\177\000\000\250\337\377\377\377\177\000\000\340\337\377\377\377\177\000\000\250\337\377\377\377\177\000\000`\337\377\377\377\177\000\000\226\071d\000\000\000\000\000 \344\377\377\377\177\000\000\240\337\377\377\377\177\000\000\000\340\377\377\377\177\000\000\062\240g\000\000\000\000"},
          m_config = std::shared_ptr<const Catch::IConfig> (use count 6, weak count 0) = {get() = 0x6120000001d0}, m_totals = {error = 0, assertions = {passed = 0, failed = 0, failedButOk = 0},
            testCases = {passed = 0, failed = 0, failedButOk = 0}}, m_reporter = std::unique_ptr<Catch::IStreamingReporter> = {get() = 0x6030000089b0}, m_messages = std::vector of length 0, capacity 0,
          m_lastAssertionInfo = {macroName = {m_start = 0x8340c0 "", m_size = 0,
```

**Comment by scw00** [comment]
It seems a ccache issue. so I close it.
