### ISSUE TITLE
failed test: test_Logutils2 (alpine linux)

### ISSUE THREAD

**Issue by jbergstroem** [apache/trafficserver#5117]
This is `a105fd3d` built on alpine linux w/ gcc 8.3. Patch/setup here: https://github.com/jbergstroem/ts-alpine.

All tests seems to pass but it bails with a segfault:
```console
$ tail proxy/logging/test-suite.log 

FAIL: test_LogUtils2
====================

===============================================================================
All tests passed (114 assertions in 1 test case)

Segmentation fault
FAIL test_LogUtils2 (exit status: 139)
```

`strace` doesn't say too much [to me]. Any ideas on how to debug further? 
```console
$ LD_LIBRARY_PATH=src/tscore/.libs:$LD_LIBRARY_PATH strace proxy/logging/.libs/test_LogUtils2 
execve("proxy/logging/.libs/test_LogUtils2", ["proxy/logging/.libs/test_LogUtil"...], 0x7ffdc8dc0be0 /* 9 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7fb624c23c28) = 0
set_tid_address(0x7fb624c23c68)         = 44305
open("src/tscore/.libs/libtscore.so.9", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=20774320, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p9\3\0\0\0\0\0"..., 960) = 960
mmap(NULL, 974848, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb624aa5000
mmap(0x7fb624ad5000, 614400, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x30000) = 0x7fb624ad5000
mmap(0x7fb624b6b000, 131072, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0xc6000) = 0x7fb624b6b000
mmap(0x7fb624b8b000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xe5000) = 0x7fb624b8b000
mmap(0x7fb624b91000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb624b91000
close(3)                                = 0
open("src/tscore/.libs/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld-musl-x86_64.path", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=1378688, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340.\n\0\0\0\0\0"..., 960) = 960
mmap(NULL, 1396736, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb624950000
mmap(0x7fb6249ec000, 450560, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x9c000) = 0x7fb6249ec000
mmap(0x7fb624a5a000, 229376, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0x10a000) = 0x7fb624a5a000
mmap(0x7fb624a93000, 73728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x142000) = 0x7fb624a93000
mmap(0x7fb624aa2000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb624aa2000
close(3)                                = 0
open("src/tscore/.libs/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=75496, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\2102\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 81920, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb62493c000
mmap(0x7fb62493f000, 49152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x3000) = 0x7fb62493f000
mmap(0x7fb62494b000, 12288, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0xf000) = 0x7fb62494b000
mmap(0x7fb62494e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x11000) = 0x7fb62494e000
close(3)                                = 0
open("src/tscore/.libs/libtscpputil.so.9", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/trafficserver/src/tscpp/util/.libs/libtscpputil.so.9", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=171992, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\20\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 20480, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb624937000
mmap(0x7fb624938000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x1000) = 0x7fb624938000
mmap(0x7fb624939000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0x7fb624939000
mmap(0x7fb62493a000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0x7fb62493a000
close(3)                                = 0
open("src/tscore/.libs/libpcre.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/trafficserver/src/tscpp/util/.libs/libpcre.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libpcre.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libpcre.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libpcre.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libpcre.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libpcre.so.1", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=374456, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\350!\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 380928, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb6248da000
mmap(0x7fb6248dc000, 249856, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x2000) = 0x7fb6248dc000
mmap(0x7fb624919000, 110592, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0x3f000) = 0x7fb624919000
mmap(0x7fb624935000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x5a000) = 0x7fb624935000
close(3)                                = 0
open("src/tscore/.libs/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/trafficserver/src/tscpp/util/.libs/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=2597536, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0`\7\0\0\0\0\0"..., 960) = 960
mmap(NULL, 2613248, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fb62465c000
mmap(0x7fb6246d1000, 1409024, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x75000) = 0x7fb6246d1000
mmap(0x7fb624829000, 528384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 3, 0x1cd000) = 0x7fb624829000
mmap(0x7fb6248ab000, 192512, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0x24e000) = 0x7fb6248ab000
mmap(0x7fb6248d7000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fb6248d7000
close(3)                                = 0
open("src/tscore/.libs/libexecinfo.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/trafficserver/src/tscpp/util/.libs/libexecinfo.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libexecinfo.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libexecinfo.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libexecinfo.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/libexecinfo.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libexecinfo.so.1", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=63056, ...}) = 0
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\10\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 2162688, PROT_READ|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7fb62444c000
mmap(0x7fb62465a000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xe000) = 0x7fb62465a000
close(3)                                = 0
mprotect(0x7fb624b8b000, 20480, PROT_READ) = 0
mprotect(0x7fb624a93000, 57344, PROT_READ) = 0
mprotect(0x7fb62494e000, 4096, PROT_READ) = 0
mprotect(0x7fb624c20000, 4096, PROT_READ) = 0
mprotect(0x7fb62493a000, 4096, PROT_READ) = 0
mprotect(0x7fb624935000, 4096, PROT_READ) = 0
mprotect(0x7fb6248ab000, 172032, PROT_READ) = 0
mprotect(0x7fb62465a000, 4096, PROT_READ) = 0
mprotect(0x55b96cb5f000, 24576, PROT_READ) = 0
brk(NULL)                               = 0x55b96e1fb000
brk(0x55b96e20d000)                     = 0x55b96e20d000
clock_gettime(CLOCK_REALTIME, {tv_sec=1551750867, tv_nsec=383744900}) = 0
brk(0x55b96e20e000)                     = 0x55b96e20e000
brk(0x55b96e20f000)                     = 0x55b96e20f000
brk(0x55b96e210000)                     = 0x55b96e210000
brk(0x55b96e211000)                     = 0x55b96e211000
brk(0x55b96e212000)                     = 0x55b96e212000
brk(0x55b96e213000)                     = 0x55b96e213000
brk(0x55b96e214000)                     = 0x55b96e214000
brk(0x55b96e215000)                     = 0x55b96e215000
brk(0x55b96e216000)                     = 0x55b96e216000
brk(0x55b96e217000)                     = 0x55b96e217000
brk(0x55b96e219000)                     = 0x55b96e219000
brk(0x55b96e21b000)                     = 0x55b96e21b000
brk(0x55b96e21c000)                     = 0x55b96e21c000
brk(0x55b96e21d000)                     = 0x55b96e21d000
brk(0x55b96e21f000)                     = 0x55b96e21f000
brk(0x55b96e221000)                     = 0x55b96e221000
brk(0x55b96e223000)                     = 0x55b96e223000
brk(0x55b96e224000)                     = 0x55b96e224000
brk(0x55b96e226000)                     = 0x55b96e226000
brk(0x55b96e227000)                     = 0x55b96e227000
clock_gettime(CLOCK_REALTIME, {tv_sec=1551750867, tv_nsec=384807700}) = 0
sigaltstack({ss_sp=0x55b96cb65d60, ss_flags=0, ss_size=8192}, {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x55b96cae1f60, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK, sa_restorer=0x7fb624bd7a8c}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGILL, {sa_handler=0x55b96cae1f60, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK, sa_restorer=0x7fb624bd7a8c}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGFPE, {sa_handler=0x55b96cae1f60, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK, sa_restorer=0x7fb624bd7a8c}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=0x55b96cae1f60, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK, sa_restorer=0x7fb624bd7a8c}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x55b96cae1f60, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK, sa_restorer=0x7fb624bd7a8c}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
rt_sigaction(SIGABRT, {sa_handler=0x55b96cae1f60, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK, sa_restorer=0x7fb624bd7a8c}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fb624bd7a8c}, NULL, 8) = 0
rt_sigaction(SIGILL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fb624bd7a8c}, NULL, 8) = 0
rt_sigaction(SIGFPE, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fb624bd7a8c}, NULL, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fb624bd7a8c}, NULL, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fb624bd7a8c}, NULL, 8) = 0
rt_sigaction(SIGABRT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fb624bd7a8c}, NULL, 8) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1551750867, tv_nsec=387478800}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=51, ws_col=144, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=51, ws_col=144, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{iov_base="\33[1;31m\33[0m\33[1;33m\33[0m\33[1;32m==="..., iov_len=112}, {iov_base="\n", iov_len=1}], 2===============================================================================
) = 113
writev(1, [{iov_base="\33[1;32mAll tests passed\33[0m (114"..., iov_len=59}, {iov_base="\n", iov_len=1}], 2All tests passed (114 assertions in 1 test case)
) = 60
writev(1, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2
) = 1
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by jbergstroem** [comment]
Thinking this is the culprit:
```
mmap(0x7fb624ad5000, 614400, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 3, 0x30000) = 0x7fb624ad5000
```
Need to give it proper permissions when running in a docker container. Will test and update.

**Comment by jbergstroem** [comment]
So, the heart of the issue is that the memory allocation for this particular tests requests exec on `/dev/shm`, whereas docker doesn't allow this (I tried `--privileged` but also failes):
```console
 # mount | grep shm
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
```

**Comment by linnaea** [comment]
This seems like a more run-of-the-mill memory corruption, got SEGV when packaging but cannot reproduce on my local machine.

However running valgrind locally gives this trace:
```
linnaea@linux-k2lg:~> LD_LIBRARY_PATH="/var/tmp/build-root/openSUSE_Leap_15.2-x86_64/home/abuild/rpmbuild/BUILD/trafficserver-9.0.0/src/tscore/.libs:/var/tmp/build-root/openSUSE_Leap_15.2-x86_64/home/abuild/rpmbuild/BUILD/trafficserver-9.0.0/src/tscpp/util/.libs:$LD_LIBRARY_PATH" valgrind /var/tmp/build-root/openSUSE_Leap_15.2-x86_64/home/abuild/rpmbuild/BUILD/trafficserver-9.0.0/proxy/logging/.libs/test_LogUtils2
==17845== Memcheck, a memory error detector
==17845== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==17845== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==17845== Command: /var/tmp/build-root/openSUSE_Leap_15.2-x86_64/home/abuild/rpmbuild/BUILD/trafficserver-9.0.0/proxy/logging/.libs/test_LogUtils2
==17845==
===============================================================================
All tests passed (120 assertions in 2 test cases)

==17845== Invalid read of size 8
==17845==    at 0x16110F: std::_Rb_tree<std::basic_string_view<char, std::char_traits<char> >, std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)>, std::_Select1st<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> >, std::less<std::basic_string_view<char, std::char_traits<char> > >, std::allocator<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> > >::_M_erase(std::_Rb_tree_node<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> >*) (stl_tree.h:1856)
==17845==    by 0x5E484A1: __cxa_finalize (in /lib64/libc-2.26.so)
==17845==    by 0x4E62F12: ??? (in /var/tmp/build-root/openSUSE_Leap_15.2-x86_64/home/abuild/rpmbuild/BUILD/trafficserver-9.0.0/src/tscore/.libs/libtscore.so.9.0.0)
==17845==    by 0x400FE62: _dl_fini (in /lib64/ld-2.26.so)
==17845==    by 0x5E48137: __run_exit_handlers (in /lib64/libc-2.26.so)
==17845==    by 0x5E48189: exit (in /lib64/libc-2.26.so)
==17845==    by 0x5E30350: (below main) (in /lib64/libc-2.26.so)
==17845==  Address 0x7e3bef8 is 24 bytes inside a block of size 56 free'd
==17845==    at 0x4C2FA0B: operator delete(void*) (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==17845==    by 0x161126: deallocate (new_allocator.h:125)
==17845==    by 0x161126: deallocate (alloc_traits.h:462)
==17845==    by 0x161126: _M_put_node (stl_tree.h:592)
==17845==    by 0x161126: _M_drop_node (stl_tree.h:659)
==17845==    by 0x161126: std::_Rb_tree<std::basic_string_view<char, std::char_traits<char> >, std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)>, std::_Select1st<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> >, std::less<std::basic_string_view<char, std::char_traits<char> > >, std::allocator<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> > >::_M_erase(std::_Rb_tree_node<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> >*) (stl_tree.h:1858)
==17845==    by 0x5E48137: __run_exit_handlers (in /lib64/libc-2.26.so)
==17845==    by 0x5E48189: exit (in /lib64/libc-2.26.so)
==17845==    by 0x5E30350: (below main) (in /lib64/libc-2.26.so)
==17845==  Block was alloc'd at
==17845==    at 0x4C2E94F: operator new(unsigned long) (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==17845==    by 0x159A12: allocate (new_allocator.h:111)
==17845==    by 0x159A12: allocate (alloc_traits.h:436)
==17845==    by 0x159A12: _M_get_node (stl_tree.h:588)
==17845==    by 0x159A12: _M_create_node<char const (&)[4], void (*)(ts::BufferWriter&, const ts::BWFSpec&)> (stl_tree.h:642)
==17845==    by 0x159A12: _M_emplace_unique<char const (&)[5], void (*)(ts::BufferWriter&, const ts::BWFSpec&)> (stl_tree.h:2351)
==17845==    by 0x159A12: emplace<char const (&)[5], void (*)(ts::BufferWriter&, const ts::BWFSpec&)> (stl_map.h:569)
==17845==    by 0x159A12: operator() (BufferWriterFormat.cc:1019)
==17845==    by 0x159A12: __static_initialization_and_destruction_0 (BufferWriterFormat.cc:1024)
==17845==    by 0x159A12: _GLOBAL__sub_I__ZN2ts7BWFSpec7DEFAULTE (BufferWriterFormat.cc:1035)
==17845==    by 0x1C93EC: __libc_csu_init (elf-init.c:88)
==17845==    by 0x5E302DA: (below main) (in /lib64/libc-2.26.so)
```
And a bunch of other errors when exiting.

Running gdb in the packaging container gives this backtrace:
```
Starting program: /home/abuild/rpmbuild/BUILD/trafficserver-9.0.0/proxy/logging/.libs/test_LogUtils2
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.26-lp152.26.3.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
===============================================================================
All tests passed (120 assertions in 2 test cases)


Program received signal SIGSEGV, Segmentation fault.
std::_Rb_tree<std::basic_string_view<char, std::char_traits<char> >, std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)>, std::_Select1st<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> >, std::less<std::basic_string_view<char, std::char_traits<char> > >, std::allocator<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> > >::_M_erase (this=this@entry=0x5555556ea0e0 <ts::bw_fmt::BWF_GLOBAL_TABLE>, __x=0x4545454545454545) at /usr/include/c++/7/bits/stl_tree.h:1856
1856              _M_erase(_S_right(__x));
Missing separate debuginfos, use: zypper install libcap2-debuginfo-2.25-lp152.4.115.x86_64 libgcc_s1-debuginfo-10.2.1+git583-lp152.2.2.x86_64 libhwloc15-debuginfo-2.1.0-lp152.2.3.1.x86_64 liblzma5-debuginfo-5.2.3-lp152.5.100.x86_64 libopenssl1_1-debuginfo-1.1.1d-lp152.7.9.1.x86_64 libpciaccess0-debuginfo-0.14-lp152.3.4.x86_64 libpcre1-debuginfo-8.41-lp152.6.104.x86_64 libstdc++6-debuginfo-10.2.1+git583-lp152.2.2.x86_64 libxml2-2-debuginfo-2.9.7-lp152.10.6.1.x86_64 libyaml-cpp0_6-debuginfo-0.6.1-lp152.5.2.1.x86_64 libz1-debuginfo-1.2.11-lp152.8.6.1.x86_64
(gdb) bt
#0  std::_Rb_tree<std::basic_string_view<char, std::char_traits<char> >, std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)>, std::_Select1st<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> >, std::less<std::basic_string_view<char, std::char_traits<char> > >, std::allocator<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> > >::_M_erase (this=this@entry=0x5555556ea0e0 <ts::bw_fmt::BWF_GLOBAL_TABLE>, __x=0x4545454545454545) at /usr/include/c++/7/bits/stl_tree.h:1856
#1  0x000055555545911b in std::_Rb_tree<std::basic_string_view<char, std::char_traits<char> >, std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)>, std::_Select1st<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> >, std::less<std::basic_string_view<char, std::char_traits<char> > >, std::allocator<std::pair<std::basic_string_view<char, std::char_traits<char> > const, void (*)(ts::BufferWriter&, ts::BWFSpec const&)> > >::_M_erase (this=0x5555556ea0e0 <ts::bw_fmt::BWF_GLOBAL_TABLE>, __x=0x5555557272e0) at /usr/include/c++/7/bits/stl_tree.h:1856
#2  0x00007ffff6a874a2 in __cxa_finalize () from /lib64/libc.so.6
#3  0x00007ffff7b7af13 in __do_global_dtors_aux () from /home/abuild/rpmbuild/BUILD/trafficserver-9.0.0/src/tscore/.libs/libtscore.so.9
#4  0x00007fffffffe770 in ?? ()
#5  0x00007ffff7de6e63 in _dl_fini () from /lib64/ld-linux-x86-64.so.2
Backtrace stopped: frame did not save the PC
```

Also it seems to be reproducible without running any test in LogUtils2:
```
abuild@linux-k2lg:/home/abuild/rpmbuild/BUILD/trafficserver-9.0.0> LD_LIBRARY_PATH="/home/abuild/rpmbuild/BUILD/trafficserver-9.0.0/src/tscore/.libs:/home/abuild/rpmbuild/BUILD/trafficserver-9.0.0/src/tscpp/util/.libs:$LD_LIBRARY_PATH" proxy/logging/.libs/test_LogUtils2 --help

Catch v2.11.0
usage:
  test_LogUtils2 [<test name|pattern|tags> ... ] options

[snip]

For more detailed usage please see the project docs

Segmentation fault (core dumped)
```

**Comment by linnaea** [comment]
https://github.com/apache/trafficserver/commit/7e8a181989ab9e27ddb86104f20065e877230210#diff-42455e4271d7de518d1ab8596e355450c996921451e222751713db6055f7143d

Blanking this seems to fix it

**Comment by bryancall** [comment]
This issue appears to be resolved / no longer relevant. Closing.

If this is still an issue, please reopen or file a new issue with reproduction steps.
