### ISSUE TITLE
ASan: stack-buffer-overflow on Http3DataFrame::store()

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#5407]
I saw below ASan with downloading 5mb file over HTTP/3.
```
[May  1 00:02:54.771] [ET_NET 6] DEBUG: <Http3FrameCollector.cc:45 (on_write_ready)        > (http3               ) [TX] [0] | HEADERS
[May  1 00:02:54.771] [ET_NET 6] DEBUG: <Http3FrameCollector.cc:45 (on_write_ready)        > (http3               ) [TX] [0] | DATA
=================================================================
==6875==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f4822f10940 at pc 0x7f482d02130d bp 0x7f4822f086c0 sp 0x7f4822f07e68
WRITE of size 32768 at 0x7f4822f10940 thread T8 ([ET_NET 6])
    #0 0x7f482d02130c  (/lib64/libasan.so.5+0x4030c)
    #1 0xe1afd6 in Http3DataFrame::store(unsigned char*, unsigned long*) const /usr/local/src/trafficserver/proxy/http3/Http3Frame.cc:153
    #2 0xe25dab in Http3FrameCollector::on_write_ready(QUICStreamIO*, unsigned long&) /usr/local/src/trafficserver/proxy/http3/Http3FrameCollector.cc:42
    #3 0xe15395 in Http3ClientTransaction::_process_write_vio() /usr/local/src/trafficserver/proxy/http3/Http3ClientTransaction.cc:509
    #4 0xe109bf in HQClientTransaction::reenable(VIO*) /usr/local/src/trafficserver/proxy/http3/Http3ClientTransaction.cc:207
    #5 0x6da5e3 in VIO::reenable() /usr/local/src/trafficserver/iocore/eventsystem/P_VIO.h:108
    #6 0x914060 in HttpTunnel::producer_handler(int, HttpTunnelProducer*) /usr/local/src/trafficserver/proxy/http/HttpTunnel.cc:1135
    #7 0x917054 in HttpTunnel::main_handler(int, void*) /usr/local/src/trafficserver/proxy/http/HttpTunnel.cc:1562
[May  1 00:02:54.944] [ET_UDP 0] DEBUG: <QUICPacketHandler.cc:280 (_recv_packet)           > (quic_sec            ) [00000000-de165855] recv SH packet from 175.177.42.113:59990 to 67.192.246.159:4433 size=42
    #8 0x6da1a1 in Continuation::handleEvent(int, void*) /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:190
    #9 0xd36cd4 in read_signal_and_update /usr/local/src/trafficserver/iocore/net/UnixNetVConnection.cc:82
    #10 0xd38532 in read_from_net /usr/local/src/trafficserver/iocore/net/UnixNetVConnection.cc:308
    #11 0xd3d854 in UnixNetVConnection::net_read_io(NetHandler*, EThread*) /usr/local/src/trafficserver/iocore/net/UnixNetVConnection.cc:890
    #12 0xd1f211 in NetHandler::process_ready_list() /usr/local/src/trafficserver/iocore/net/UnixNet.cc:396
    #13 0xd20a60 in NetHandler::waitForActivity(long) /usr/local/src/trafficserver/iocore/net/UnixNet.cc:529
    #14 0xdf63ca in EThread::execute_regular() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:273
    #15 0xdf6c00 in EThread::execute() /usr/local/src/trafficserver/iocore/eventsystem/UnixEThread.cc:334
    #16 0xdf31e1 in spawn_thread_internal /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:92
    #17 0x7f482b079593 in start_thread (/lib64/libpthread.so.0+0x7593)
    #18 0x7f482a269f4e in clone (/lib64/libc.so.6+0xf9f4e)

Address 0x7f4822f10940 is located in stack of thread T8 ([ET_NET 6]) at offset 33120 in frame
    #0 0xe25953 in Http3FrameCollector::on_write_ready(QUICStreamIO*, unsigned long&) /usr/local/src/trafficserver/proxy/http3/Http3FrameCollector.cc:30

  This frame has 6 object(s):
    [32, 40) '__for_begin'
    [96, 104) '__for_end'
    [160, 168) 'len'
    [224, 240) 'frame'
    [288, 312) 'loc'
    [352, 33120) 'tmp' <== Memory access at offset 33120 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
Thread T8 ([ET_NET 6]) created by T0 ([TS_MAIN]) here:
    #0 0x7f482d02c443 in pthread_create (/lib64/libasan.so.5+0x4b443)
    #1 0xdf2a27 in ink_thread_create ../../include/tscore/ink_thread.h:159
    #2 0xdf330f in Thread::start(char const*, void*, unsigned long, std::function<void ()> const&) /usr/local/src/trafficserver/iocore/eventsystem/Thread.cc:109
    #3 0xdfcd9f in EventProcessor::spawn_event_threads(int, int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:382
    #4 0xdfd77e in EventProcessor::start(int, unsigned long) /usr/local/src/trafficserver/iocore/eventsystem/UnixEventProcessor.cc:449
    #5 0x746e5c in main traffic_server/traffic_server.cc:1837
    #6 0x7f482a19311a in __libc_start_main (/lib64/libc.so.6+0x2311a)

SUMMARY: AddressSanitizer: stack-buffer-overflow (/lib64/libasan.so.5+0x4030c) 
Shadow bytes around the buggy address:
  0x0fe9845da0d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9845da0e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9845da0f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9845da100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe9845da110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe9845da120: 00 00 00 00 00 00 00 00[f3]f3 f3 f3 00 00 00 00
  0x0fe9845da130: 00 00 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2 f2 f2
  0x0fe9845da140: f2 f2 00 f2 f2 f2 f2 f2 f2 f2 00 00 f2 f2 f2 f2
  0x0fe9845da150: f2 f2 00 00 f2 f2 f2 f2 f2 f2 00 00 00 f2 f2 f2
  0x0fe9845da160: f2 f2 f8 f8 f8 f2 f3 f3 f3 f3 00 00 00 00 00 00
  0x0fe9845da170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==6875==ABORTING
```

**Comment by masaori335** [comment]
Fixed by 5a77a807942e8ef5eb4f0b844bcc881e0367375d
