### ISSUE TITLE
Different the cache behavious in CacheVC::openWriteMain

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5503]
There are two different `reenable` between test and ats.
 
For test, we automatically fill buffer and `CacheVC::openWriteMain` will consume data directly without returning back to event system.

https://github.com/apache/trafficserver/blob/c934b15aa817088bf18d724e01ba2bec3308f9cf/iocore/cache/CacheWrite.cc#L1423-L1431

see it will goto `Lagian`(line 1430) to consume more data. Once the `total_len` hits the limit. `it will write it down, even if it is a single fragment . That means even if it is a single fragment. we still have 2 fragment in cache for a single fragment`. These should be fixed in another pr.

For ats. `HttpTunnel` will reenable producer to produce more data and then reenable consumer. That will return back to event system between the two reenable. So the `goto Lagain` will consume nothing and finally callback with `VC_EVENT_WRITE_COMPLETE` (line 1388).

https://github.com/apache/trafficserver/blob/c934b15aa817088bf18d724e01ba2bec3308f9cf/iocore/cache/CacheWrite.cc#L1386-L1395

**Comment by scw00** [comment]
Assertion in `CacheVC::updateVector`. Test code https://github.com/scw00/trafficserver/blob/collison_test/iocore/cache/test/test_Alternate_S_to_S_remove_S_write_S.cc

```
[Apr 28 00:11:49.451] test_Alternate_ DEBUG: <Cache.cc:363 (do_io_close)> (cache_close) do_io_close 0x7f4320e25bd0 -1 1
Fatal: CacheWrite.cc:129: failed assertion `!fragment || f.data_done`

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_Alternate_S_to_S_remove_S_write_S is a Catch v2.2.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
cache write -> read
AddressSanitizer:DEADLYSIGNAL
=================================================================
==41875==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x555a63b72e30 bp 0x555a649a19e0 sp 0x555a649a19c0 T0)
==41875==The signal is caused by a READ memory access.
==41875==Hint: address points to the zero page.
    #0 0x555a63b72e2f in Catch::Colour::use(Catch::Colour::Code) /root/trafficserver/tests/include/catch.hpp:6989
    #1 0x555a63b72dab in Catch::Colour::~Colour() /root/trafficserver/tests/include/catch.hpp:6985
    #2 0x555a63bac95c in Catch::ConsoleReporter::printOpenHeader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /root/trafficserver/tests/include/catch.hpp:12063
    #3 0x555a63bac323 in Catch::ConsoleReporter::printTestCaseAndSectionHeader() /root/trafficserver/tests/include/catch.hpp:12034
    #4 0x555a63babb4d in Catch::ConsoleReporter::lazyPrintWithoutClosingBenchmarkTable() /root/trafficserver/tests/include/catch.hpp:12010
    #5 0x555a63baba49 in Catch::ConsoleReporter::lazyPrint() /root/trafficserver/tests/include/catch.hpp:11999
    #6 0x555a63baa81c in Catch::ConsoleReporter::assertionEnded(Catch::AssertionStats const&) /root/trafficserver/tests/include/catch.hpp:11920
    #7 0x555a63bb6b88 in Catch::MultipleReporters::assertionEnded(Catch::AssertionStats const&) /root/trafficserver/tests/include/catch.hpp:12478
    #8 0x555a63b822fa in Catch::RunContext::assertionEnded(Catch::AssertionResult const&) /root/trafficserver/tests/include/catch.hpp:8642
    #9 0x555a63b83afd in Catch::RunContext::handleFatalErrorCondition(Catch::StringRef) /root/trafficserver/tests/include/catch.hpp:8741
    #10 0x555a63b7463d in reportFatal /root/trafficserver/tests/include/catch.hpp:7313
    #11 0x555a63b7478c in Catch::FatalConditionHandler::handleSignal(int) /root/trafficserver/tests/include/catch.hpp:7402
    #12 0x7f432478888f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1288f)
    #13 0x7f4323880e96 in gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x3ee96)
    #14 0x7f4323882800 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x40800)
    #15 0x7f4325c98a4b in ink_abort(char const*, ...) /root/trafficserver/src/tscore/ink_error.cc:99
    #16 0x7f4325c910e5 in _ink_assert /root/trafficserver/src/tscore/ink_assert.cc:37
    #17 0x555a63dab8d0 in CacheVC::updateVector(int, Event*) /root/trafficserver/iocore/cache/CacheWrite.cc:129
    #18 0x555a63dbdba0 in CacheVC::openWriteCloseHead(int, Event*) /root/trafficserver/iocore/cache/CacheWrite.cc:1222
    #19 0x555a63dbea61 in CacheVC::openWriteClose(int, Event*) /root/trafficserver/iocore/cache/CacheWrite.cc:1313
    #20 0x555a63d4bae1 in CacheVC::die() (/root/trafficserver/iocore/cache/.libs/test_Alternate_S_to_S_remove_S_write_S+0x704ae1)
    #21 0x555a63da139e in CacheVC::calluser(int) /root/trafficserver/iocore/cache/P_CacheInternal.h:630
    #22 0x555a63dbf856 in CacheVC::openWriteMain(int, Event*) /root/trafficserver/iocore/cache/CacheWrite.cc:1394
    #23 0x555a63dbf5e7 in CacheVC::openWriteWriteDone(int, Event*) /root/trafficserver/iocore/cache/CacheWrite.cc:1366
    #24 0x555a63d12a3f in Continuation::handleEvent(int, void*) /root/trafficserver/iocore/eventsystem/I_Continuation.h:190
    #25 0x555a63dc5d1a in CacheVC::handleWriteLock(int, Event*) /root/trafficserver/iocore/cache/P_CacheInternal.h:719
    #26 0x555a63dc60b0 in CacheVC::do_write_lock_call() /root/trafficserver/iocore/cache/P_CacheInternal.h:735
    #27 0x555a63dbff25 in CacheVC::openWriteMain(int, Event*) /root/trafficserver/iocore/cache/CacheWrite.cc:1450
    #28 0x555a63d12a3f in Continuation::handleEvent(int, void*) /root/trafficserver/iocore/eventsystem/I_Continuation.h:190
    #29 0x555a642fb835 in EThread::process_event(Event*, int) /root/trafficserver/iocore/eventsystem/UnixEThread.cc:132
    #30 0x555a642fbddc in EThread::process_queue(Queue<Event, Event::Link_link>*, int*, int*) /root/trafficserver/iocore/eventsystem/UnixEThread.cc:171
    #31 0x555a642fc51a in EThread::execute_regular() /root/trafficserver/iocore/eventsystem/UnixEThread.cc:231
    #32 0x555a642fd3dd in EThread::execute() /root/trafficserver/iocore/eventsystem/UnixEThread.cc:334
    #33 0x555a63d10f0d in ____C_A_T_C_H____T_E_S_T____0 test/test_Alternate_S_to_S_remove_S_write_S.cc:348
    #34 0x555a63b93a58 in Catch::TestInvokerAsFunction::invoke() const /root/trafficserver/tests/include/catch.hpp:10067
    #35 0x555a63b92439 in Catch::TestCase::invoke() const /root/trafficserver/tests/include/catch.hpp:9968
    #36 0x555a63b85720 in Catch::RunContext::invokeActiveTestCase() /root/trafficserver/tests/include/catch.hpp:8832
    #37 0x555a63b84f5f in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /root/trafficserver/tests/include/catch.hpp:8806
    #38 0x555a63b819b8 in Catch::RunContext::runTest(Catch::TestCase const&) /root/trafficserver/tests/include/catch.hpp:8595
    #39 0x555a63b88e94 in runTests /root/trafficserver/tests/include/catch.hpp:9135
    #40 0x555a63b8bb34 in Catch::Session::runInternal() /root/trafficserver/tests/include/catch.hpp:9333
    #41 0x555a63b8b50b in Catch::Session::run() /root/trafficserver/tests/include/catch.hpp:9290
    #42 0x555a63b8b46f in Catch::Session::run(int, char**) /root/trafficserver/tests/include/catch.hpp:9258
    #43 0x555a63bbdc3b in main /root/trafficserver/tests/include/catch.hpp:12750
    #44 0x7f4323863b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #45 0x555a63b61e39 in _start (/root/trafficserver/iocore/cache/.libs/test_Alternate_S_to_S_remove_S_write_S+0x51ae39)
```

**Comment by scw00** [comment]
>It's fine to have two fragments in the case you describe, that's just how the cache works. There's a limit on how big a resident alternate can be and it's much smaller than the size of a filled buffer.

I don't think it should be that because follow two:
 - That mean, Although it is small doc, we still need to read twice (2 block) at least. It will greatly decrease the small doc performance.
 - See https://github.com/apache/trafficserver/blob/3fb2bcdf2db46eb49708eea655670997a2c04f8e/iocore/cache/CacheWrite.cc#L1305-L1314. Although we have two fragments we don't fall into `CacheVC::openWriteCloseDataDone`. So the f.complete is never be true. (It is ok because we have already write the data into the disk), that is main reason why we assert.

>That's not an assertion, that's a crash. The address 0x10 is the offset of the mutex in a continuation and that kind of SIGSEGV almost always indicates calling back a null Continuation pointer.

It is assert before coredump.

Generally, In normal case like `test_Cache`. the small document still write as 2 fragments. And it should be fix.

**Comment by scw00** [comment]
Comment by @SolidWallOfCode 

```
Two things:

1. It's fine to have two fragments in the case you describe, that's just how the cache works. There's a limit on how big a resident alternate can be and it's much smaller than the size of a filled buffer.

1. That's not an assertion, that's a crash. The address `0x10` is the offset of the mutex in a continuation and that kind of SIGSEGV almost always indicates calling back a null Continuation pointer.
```
