### ISSUE TITLE
ATS crash 7.1.6

### ISSUE THREAD

**Issue by dnj12345** [apache/trafficserver#5596]
Hi,
Running into an ATS crash when running with 7.1.6 versions. I have a custom plugin using atscppapi along with the base trafficserver. The same plugin worked without any issues on 6.2.{1.3} without any issues. Upgrading the base to 7.1.6 result with everything else remaining the same results in this crash. The backtrace is pasted below...

OS: Ubuntu 16.04

Please let me know if you need any additional info...

```
(gdb) bt full
#0  0x00002b681c7a0428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 5064
        selftid = 5070
#1  0x00002b681c7a202a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {
          __sigaction_handler = {
            sa_handler = 0x0,
            sa_sigaction = 0x0
          },
          sa_mask = {
            __val = {0 <repeats 13 times>, 8289104, 14005026710345486848, 47727018881096}
          },
          sa_flags = 0,
          sa_restorer = 0x2b685001b048
        }
        sigs = {
          __val = {32, 0 <repeats 15 times>}
        }
#2  0x00002b681a76d438 in ink_abort (
    message_format=message_format@entry=0x2b681a77a887 "%s:%d: failed assertion `%s`")
    at ink_error.cc:99
        ap = <error reading variable ap (Attempt to dereference a generic pointer.)>
#3  0x00002b681a76ad85 in _ink_assert (
    expression=expression@entry=0x7e7af8 "call_event == core_lock_retry_event",
    file=file@entry=0x7e7b2b "PluginVC.cc", line=line@entry=219) at ink_assert.cc:37
No locals.
#4  0x00000000005082a4 in PluginVC::main_handler (this=0x2b685001b048, event=<optimized out>,
    data=0x2b68301d4f20) at PluginVC.cc:219
        __FUNCTION__ = "main_handler"
        call_event = 0x2b68301d4f20
        read_mutex_held = <optimized out>
        write_mutex_held = false
        read_side_mutex = {
          m_ptr = 0x2b68301cd860
        }
---Type <return> to continue, or q <return> to quit---
        write_side_mutex = {
          m_ptr = 0x0
        }
#5  0x00000000007d5682 in Continuation::handleEvent (data=0x2b68301d4f20, event=1,
    this=<optimized out>) at I_Continuation.h:152
No locals.
#6  EThread::process_event (this=0x2b6820ef5010, e=0x2b68301d4f20, calling_code=1)
    at UnixEThread.cc:140
        c_temp = <optimized out>
        lock = {
          m = {
            m_ptr = 0x2b68301cd450
          },
          lock_acquired = true
        }
#7  0x00000000007d5fd6 in EThread::process_queue (this=this@entry=0x2b6820ef5010,
    NegativeQueue=NegativeQueue@entry=0x2b68215fbe90) at UnixEThread.cc:175
        e = 0x2b68301d4f20
#8  0x00000000007d622b in EThread::execute_regular (this=0x2b6820ef5010) at UnixEThread.cc:207
        done_one = <optimized out>
        sleep_time = <optimized out>
        e = <optimized out>
        NegativeQueue = {
          <DLL<Event, Event::Link_link>> = {
            head = 0x0
          },
          members of Queue<Event, Event::Link_link>:
          tail = 0x0
        }
        next_time = <optimized out>
#9  0x00000000007d50c5 in spawn_thread_internal (a=0x201e490) at Thread.cc:84
        p = 0x201e490
#10 0x00002b681bab06ba in start_thread (arg=0x2b68215fc700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x2b68215fc700
        now = <optimized out>
        unwind_buf = {
---Type <return> to continue, or q <return> to quit---
          cancel_jmp_buf = {{
              jmp_buf = {47726236518144, 6624414028357692307, 0, 140732152334319, 140732152334768,
                0, 954455023455038355, 954360837213383571},
              mask_was_saved = 0
            }},
          priv = {
            pad = {0x0, 0x0, 0x0, 0x0},
            data = {
              prev = 0x0,
              cleanup = 0x0,
              canceltype = 0
            }
          }
        }
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#11 0x00002b681c87241d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
(gdb)
```

**Comment by dnj12345** [comment]
I rebuilt my ATS enabling the debug option. Here's a link to the tar file that contains core file and the traffic.out file.

https://www.dropbox.com/s/s2owmjyah5akrr1/ats-crash-7.1.6.tar?dl=0

One interesting thing to note. In my plugin, it periodically performs an async fetch to retrieve data. The url for the async fetch has the following format:

https://hostname/api/v1?query-params

The crash seems to happen more quickly if the uri ends with a slash i.e

https://hostname/api/v1/?query-params

**Comment by zwoop** [comment]
Giving to @ezelkow1  for assessment.

**Comment by bryancall** [comment]
@dnj12345 Are you still having an issue with this?

**Comment by dnj12345** [comment]
Closing since I am not using ATS currently.
