### ISSUE TITLE
Memory leak in traffic_crashlog

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#5708]
```
[Jul 10 21:02:57.098] traffic_crashlo ERROR: wrote crash log to /opt/ats/var/log/trafficserver/crash-2019-07-10-210256.log

=================================================================
==14267==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 59 byte(s) in 1 object(s) allocated from:
    #0 0x7fe3c1322c48 in malloc (/lib64/libasan.so.5+0xeec48)
    #1 0x7fe3c0c2ef54 in ats_malloc /usr/local/src/trafficserver/src/tscore/ink_memory.cc:59
    #2 0x7fe3c0c2fa0c in ats_scoped_str::operator=(std::basic_string_view<char, std::char_traits<char> >) /usr/local/src/trafficserver/src/tscore/ink_memory.cc:292
    #3 0x43c641 in crashlog_name traffic_crashlog/traffic_crashlog.cc:76
    #4 0x43ddbf in main traffic_crashlog/traffic_crashlog.cc:226
    #5 0x7fe3bfc7211a in __libc_start_main (/lib64/libc.so.6+0x2311a)
```

**Comment by maskit** [comment]
#5716 fixed this.
