### ISSUE TITLE
Memory leak in QUICNetVC

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#5866]
This leak is expected, because QUICPacketReceiveQueue is a member of QUICNetVC and QUICNetVC is not destructed currently. One connection leaks one object.

Freeing / Deleting / Destructing QUICNetVC should fix this.

```
Direct leak of 382 byte(s) in 2 object(s) allocated from:
    #0 0x7f5cd10bcca8 in __interceptor_malloc (/lib64/libasan.so.5+0x10dca8)
    #1 0x7f5cd0ea1342 in ats_malloc /home/mkitajo/src/trafficserver/src/tscore/ink_memory.cc:59
    #2 0x7f5cd0ea1687 in ats_unique_malloc(unsigned long) /home/mkitajo/src/trafficserver/src/tscore/ink_memory.cc:167
    #3 0xebeb75 in QUICPacketReceiveQueue::dequeue(QUICPacketCreationResult&) /home/mkitajo/src/trafficserver/iocore/net/quic/QUICPacketReceiveQueue.cc:95
    #4 0xd52e02 in QUICNetVConnection::_dequeue_recv_packet(QUICPacketCreationResult&) /home/mkitajo/src/trafficserver/iocore/net/QUICNetVConnection.cc:1814
    #5 0xd44094 in QUICNetVConnection::state_handshake(int, Event*) /home/mkitajo/src/trafficserver/iocore/net/QUICNetVConnection.cc:779
    #6 0x6ea0e9 in Continuation::handleEvent(int, void*) /home/mkitajo/src/trafficserver/iocore/eventsystem/I_Continuation.h:190
    #7 0xd46b28 in QUICNetVConnection::net_read_io(NetHandler*, EThread*) /home/mkitajo/src/trafficserver/iocore/net/QUICNetVConnection.cc:979
    #8 0xd065c5 in NetHandler::process_ready_list() /home/mkitajo/src/trafficserver/iocore/net/UnixNet.cc:400
    #9 0xd07a4b in NetHandler::waitForActivity(long) /home/mkitajo/src/trafficserver/iocore/net/UnixNet.cc:533
    #10 0xdd4b8b in EThread::execute_regular() /home/mkitajo/src/trafficserver/iocore/eventsystem/UnixEThread.cc:277
    #11 0xdd5356 in EThread::execute() /home/mkitajo/src/trafficserver/iocore/eventsystem/UnixEThread.cc:338
    #12 0xdd1d23 in spawn_thread_internal /home/mkitajo/src/trafficserver/iocore/eventsystem/Thread.cc:92
    #13 0x7f5cd08db5a1 in start_thread (/lib64/libpthread.so.0+0x85a1)
```

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
