### ISSUE TITLE
Assertion in SSLNetVConnection::net_read_io

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#6434]
After fixing the fail_action=5 assertion, we now get

```
#0  0x00002b1db884f337 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
55	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
[Current thread is 1 (Thread 0x2b1dbca00700 (LWP 9680))]
(gdb) bt
#0  0x00002b1db884f337 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00002b1db8850a28 in __GI_abort () at abort.c:90
#2  0x00002b1db625b7d1 in ink_abort (message_format=0x2b1db62c90e8 "%s:%d: failed assertion `%s`") at ink_error.cc:99
#3  0x00002b1db625880e in _ink_assert (expression=0x9dd090 "this->handShakeReader != nullptr", file=0x9dcaf4 "SSLNetVConnection.cc", line=604) at ink_assert.cc:37
#4  0x00000000008e4c7f in SSLNetVConnection::net_read_io (this=0x2b1dbd0e3100, nh=0x2b1dbac09d10, lthread=0x2b1dbac06000) at SSLNetVConnection.cc:604
#5  0x0000000000909ecc in NetHandler::process_ready_list (this=0x2b1dbac09d10) at UnixNet.cc:400
#6  0x000000000090a6ce in NetHandler::waitForActivity (this=0x2b1dbac09d10, timeout=60000000) at UnixNet.cc:535
#7  0x000000000094726c in EThread::execute_regular (this=0x2b1dbac06000) at UnixEThread.cc:290
#8  0x000000000094746d in EThread::execute (this=0x2b1dbac06000) at UnixEThread.cc:351
#9  0x0000000000945db3 in spawn_thread_internal (a=0x2b1db9ecfac0) at Thread.cc:92
#10 0x00002b1db7be1e65 in start_thread (arg=0x2b1dbca00700) at pthread_create.c:307
#11 0x00002b1db891788d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

and

```
(gdb) bt full
#0  0x00002b1db884f337 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 9673
        selftid = 9680
#1  0x00002b1db8850a28 in __GI_abort () at abort.c:90
        save_stage = 2
        act = {
          __sigaction_handler = {
            sa_handler = 0x0,
            sa_sigaction = 0x0
          },
          sa_mask = {
            __val = {0 <repeats 16 times>}
          },
          sa_flags = 0,
          sa_restorer = 0x2b1dbd0e3320
        }
        sigs = {
          __val = {32, 0 <repeats 15 times>}
        }
#2  0x00002b1db625b7d1 in ink_abort (message_format=0x2b1db62c90e8 "%s:%d: failed assertion `%s`") at ink_error.cc:99
        ap = {{
            gp_offset = 32,
            fp_offset = 48,
            overflow_arg_area = 0x2b1dbc9ffa20,
            reg_save_area = 0x2b1dbc9ff960
          }}
#3  0x00002b1db625880e in _ink_assert (expression=0x9dd090 "this->handShakeReader != nullptr", file=0x9dcaf4 "SSLNetVConnection.cc", line=604) at ink_assert.cc:37
No locals.
#4  0x00000000008e4c7f in SSLNetVConnection::net_read_io (this=0x2b1dbd0e3100, nh=0x2b1dbac09d10, lthread=0x2b1dbac06000) at SSLNetVConnection.cc:604
        err = 11
        ret = 6
        r = 0
        bytes = 0
        s = 0x2b1dbd0e32d8
        lock = {
          m = {
            m_ptr = 0x2b1dbd0b3160
          },
          lock_acquired = true
        }
        __FUNCTION__ = "net_read_io"
        buf = @0x2b1dbd0e3300: {
          name = 0x0,
          mbuf = 0x2b1db9c1b400,
          entry = 0x0
        }
        ntodo = 0
#5  0x0000000000909ecc in NetHandler::process_ready_list (this=0x2b1dbac09d10) at UnixNet.cc:400
        vc = 0x2b1dbd0e3100
#6  0x000000000090a6ce in NetHandler::waitForActivity (this=0x2b1dbac09d10, timeout=60000000) at UnixNet.cc:535
        epd = 0x2b1dbd0e3418
        lock = {
          m = {
            m_ptr = 0x2b1dbd0b3080
          },
          locked_p = true
        }
        __FUNCTION__ = "waitForActivity"
        p = 0x2b1dbac09e40
        pd = 0x2b1dbd012000
        vc = 0x2b1dbd0e3100
#7  0x000000000094726c in EThread::execute_regular (this=0x2b1dbac06000) at UnixEThread.cc:290
        done_one = false
        sleep_time = 60000000
        e = 0x0
        NegativeQueue = {
          <DLL<Event, Event::Link_link>> = {
            head = 0x0
          },
          members of Queue<Event, Event::Link_link>:
          tail = 0x0
        }
        next_time = 1582113141391903018
        delta = 18586788
        loop_start_time = 1582113140751903018
        loop_finish_time = 1582113140751899306
        prev_metric = 0x2b1dbad0b2c0
        nq_count = 2
        ev_count = 2
        METRIC_INIT = {
          _loop_time = {
            _start = 0,
            _min = 9223372036854775807,
            _max = 0
          },
          _events = {
            _min = 2147483647,
            _max = 0,
            _total = 0
          },
          _count = 0,
          _wait = 0
        }
#8  0x000000000094746d in EThread::execute (this=0x2b1dbac06000) at UnixEThread.cc:351
        __FUNCTION__ = "execute"
#9  0x0000000000945db3 in spawn_thread_internal (a=0x2b1db9ecfac0) at Thread.cc:92
        p = 0x2b1db9ecfac0
#10 0x00002b1db7be1e65 in start_thread (arg=0x2b1dbca00700) at pthread_create.c:307
        __res = <optimized out>
        pd = 0x2b1dbca00700
        now = <optimized out>
        unwind_buf = {
          cancel_jmp_buf = {{
              jmp_buf = {47406718650112, -9220436927225808408, 0, 2101248, 0, 47406718650112, -3012604373922498072, -3012624428214928920},
              mask_was_saved = 0
            }},
          priv = {
            pad = {0x0, 0x0, 0x0, 0x0},
            data = {
              prev = 0x0,
              cleanup = 0x0,
              canceltype = 0
            }
          }
        }
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#11 0x00002b1db891788d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
```

**Comment by maskit** [comment]
Looks similar to #5712. Maybe the same?
