### ISSUE TITLE
Assertion from Http2Stream::main_event_handler into HttpSM

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#6443]
New assertion:

```
#0  0x00002b4d9310a337 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00002b4d9310ba28 in __GI_abort () at abort.c:90
#2  0x00002b4d90b167d1 in ink_abort (message_format=0x2b4d90b840e8 "%s:%d: failed assertion `%s`") at ink_error.cc:99
#3  0x00002b4d90b1380e in _ink_assert (expression=0x970b1d "pending_action == nullptr", file=0x9701d6 "HttpSM.cc", line=6800) at ink_assert.cc:37
#4  0x00000000006ed834 in HttpSM::kill_this (this=0x2b4db0778000) at HttpSM.cc:6800
#5  0x00000000006dc586 in HttpSM::main_handler (this=0x2b4db0778000, event=104, data=0x2b4d9929c490) at HttpSM.cc:2608
#6  0x000000000064a6b3 in Continuation::handleEvent (this=0x2b4db0778000, event=104, data=0x2b4d9929c490) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:190
#7  0x00000000007a0c79 in Http2Stream::main_event_handler (this=0x2b4d9929c200, event=104, edata=0x2b4d9900eb60) at Http2Stream.cc:160
#8  0x000000000064a6b3 in Continuation::handleEvent (this=0x2b4d9929c200, event=104, data=0x2b4d9900eb60) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:190
#9  0x0000000000946b23 in EThread::process_event (this=0x2b4d95806000, e=0x2b4d9900eb60, calling_code=104) at UnixEThread.cc:143
#10 0x0000000000946d75 in EThread::process_queue (this=0x2b4d95806000, NegativeQueue=0x2b4d989ffda0, ev_count=0x2b4d989ffd98, nq_count=0x2b4d989ffd9c) at UnixEThread.cc:182
#11 0x0000000000947015 in EThread::execute_regular (this=0x2b4d95806000) at UnixEThread.cc:242
#12 0x0000000000947457 in EThread::execute (this=0x2b4d95806000) at UnixEThread.cc:351
#13 0x0000000000945d9d in spawn_thread_internal (a=0x2b4d946c5d40) at Thread.cc:92
#14 0x00002b4d9249ce65 in start_thread (arg=0x2b4d98a00700) at pthread_create.c:307
#15 0x00002b4d931d288d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

```
(gdb) bt full
#0  0x00002b4d9310a337 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 2693
        selftid = 2704
#1  0x00002b4d9310ba28 in __GI_abort () at abort.c:90
        save_stage = 2
        act = {
          __sigaction_handler = {
            sa_handler = 0x0,
            sa_sigaction = 0x0
          },
          sa_mask = {
            __val = {0 <repeats 16 times>}
          },
          sa_flags = 0,
          sa_restorer = 0x2b4d95806000
        }
        sigs = {
          __val = {32, 0 <repeats 15 times>}
        }
#2  0x00002b4d90b167d1 in ink_abort (message_format=0x2b4d90b840e8 "%s:%d: failed assertion `%s`") at ink_error.cc:99
        ap = {{
            gp_offset = 32,
            fp_offset = 48,
            overflow_arg_area = 0x2b4d989ff800,
            reg_save_area = 0x2b4d989ff740
          }}
#3  0x00002b4d90b1380e in _ink_assert (expression=0x970b1d "pending_action == nullptr", file=0x9701d6 "HttpSM.cc", line=6800) at ink_assert.cc:37
No locals.
#4  0x00000000006ed834 in HttpSM::kill_this (this=0x2b4db0778000) at HttpSM.cc:6800
        __FUNCTION__ = "kill_this"
#5  0x00000000006dc586 in HttpSM::main_handler (this=0x2b4db0778000, event=104, data=0x2b4d9929c490) at HttpSM.cc:2608
        jump_point = (int (HttpSM::*)(HttpSM * const, int, void *)) 0x6d4b7a <HttpSM::state_watch_for_client_abort(int, void*)>
        __FUNCTION__ = "main_handler"
        vc_entry = 0x2b4db07793c8
#6  0x000000000064a6b3 in Continuation::handleEvent (this=0x2b4db0778000, event=104, data=0x2b4d9929c490) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:190
No locals.
#7  0x00000000007a0c79 in Http2Stream::main_event_handler (this=0x2b4d9929c200, event=104, edata=0x2b4d9900eb60) at Http2Stream.cc:160
        lock = {
          m = {
            m_ptr = 0x2b4d990b39b0
          },
          locked_p = true
        }
        lock = {
          m = {
            m_ptr = 0x2b4d990b39b0
          },
          locked_p = true
        }
        __FUNCTION__ = "main_event_handler"
        e = 0x2b4d9900eb60
#8  0x000000000064a6b3 in Continuation::handleEvent (this=0x2b4d9929c200, event=104, data=0x2b4d9900eb60) at /usr/local/src/trafficserver/iocore/eventsystem/I_Continuation.h:190
No locals.
#9  0x0000000000946b23 in EThread::process_event (this=0x2b4d95806000, e=0x2b4d9900eb60, calling_code=104) at UnixEThread.cc:143
        c_temp = 0x2b4d9929c200
        lock = {
          m = {
            m_ptr = 0x2b4d990b39b0
          },
          lock_acquired = true
        }
        __FUNCTION__ = "process_event"
#10 0x0000000000946d75 in EThread::process_queue (this=0x2b4d95806000, NegativeQueue=0x2b4d989ffda0, ev_count=0x2b4d989ffd98, nq_count=0x2b4d989ffd9c) at UnixEThread.cc:182
        e = 0x2b4d9900eb60
#11 0x0000000000947015 in EThread::execute_regular (this=0x2b4d95806000) at UnixEThread.cc:242
        done_one = false
        sleep_time = 60000000
        e = 0x0
        NegativeQueue = {
          <DLL<Event, Event::Link_link>> = {
            head = 0x0
          },
          members of Queue<Event, Event::Link_link>:
          tail = 0x0
        }
        next_time = 1582219899438563178
        delta = 17885706
        loop_start_time = 1582219899136450775
        loop_finish_time = 1582219899136448884
        prev_metric = 0x2b4d9590e410
        nq_count = 2
        ev_count = 3
        METRIC_INIT = {
          _loop_time = {
            _start = 0,
            _min = 9223372036854775807,
            _max = 0
          },
          _events = {
            _min = 2147483647,
            _max = 0,
            _total = 0
          },
          _count = 0,
          _wait = 0
        }
#12 0x0000000000947457 in EThread::execute (this=0x2b4d95806000) at UnixEThread.cc:351
        __FUNCTION__ = "execute"
#13 0x0000000000945d9d in spawn_thread_internal (a=0x2b4d946c5d40) at Thread.cc:92
        p = 0x2b4d946c5d40
#14 0x00002b4d9249ce65 in start_thread (arg=0x2b4d98a00700) at pthread_create.c:307
        __res = <optimized out>
        pd = 0x2b4d98a00700
        now = <optimized out>
        unwind_buf = {
          cancel_jmp_buf = {{
              jmp_buf = {47612273100544, 3106342837177197686, 0, 2101248, 0, 47612273100544, 9043442893771416694, 9043464213436867702},
              mask_was_saved = 0
            }},
          priv = {
            pad = {0x0, 0x0, 0x0, 0x0},
            data = {
              prev = 0x0,
              cleanup = 0x0,
              canceltype = 0
            }
          }
        }
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#15 0x00002b4d931d288d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
```

**Comment by zwoop** [comment]
Oh, this is a duplicate of  #4119. Closing.
