### ISSUE TITLE
crash reloading ssl_server_name.yaml with wildcard entry

### ISSUE THREAD

**Issue by randall** [apache/trafficserver#6522]
Reloading `ssl_server_name.yaml`, with a wildcard name (eg `*.subdomain.domain.com`), results in a crash.

This was with 8.0.6

```
#0  0x00007f40c15cf726 in __strcmp_sse42 () from /lib64/libc.so.6
#1  0x000055583b912c20 in StringHashFns::equal (a=<optimized out>, b=0x7f40a6fae420 "*.subdomain.domain.com")
    at ../../include/tscore/Map.h:1244
#2  HashMap<char const*, StringHashFns, NextHopProperty*, DefaultAlloc>::get_internal (this=<optimized out>, akey=0x0)
    at ../../include/tscore/Map.h:1581
#3  0x000055583b910fea in HashMap<char const*, StringHashFns, NextHopProperty*, DefaultAlloc>::get (
    this=<optimized out>, akey=0x7f40a6fae420 "*. subdomain.domain.com") at ../../include/tscore/Map.h:1601
#4  SNIConfigParams::cleanup (this=0x7f40bf17d310) at SSLSNIConfig.cc:206
#5  0x000055583b9110e9 in SNIConfigParams::~SNIConfigParams (this=0x7f40bf17d180) at SSLSNIConfig.cc:214
#6  0x000055583b9111de in SNIConfigParams::~SNIConfigParams (this=0x7f40bf17d180) at SSLSNIConfig.cc:213
#7  0x000055583b862b86 in ConfigProcessor::release (this=0x55583bd3c7a0 <configProcessor>, id=6, info=0x7f40bf17d180)
    at ProxyConfig.cc:203
#8  0x000055583b86346c in ConfigInfoReleaser::handle_event (this=0x7f40a25138c0) at ProxyConfig.cc:104
#9  0x000055583b950000 in Continuation::handleEvent (this=<optimized out>, event=<optimized out>, data=<optimized out>)
    at ./I_Continuation.h:160
#10 EThread::process_event (this=0x7f40bd20dac0, e=0x7f40bf1e2760, calling_code=2) at UnixEThread.cc:131
#11 0x000055583b9507e0 in EThread::execute_regular (this=0x7f40bd20dac0) at UnixEThread.cc:244
#12 0x000055583b94f66c in spawn_thread_internal (a=0x7f40bf194220) at Thread.cc:85
#13 0x00007f40c1291aa1 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f40c158fc4d in clone () from /lib64/libc.so.6
```

**Comment by randall** [comment]
This does not occur on ATS 9.x
