### ISSUE TITLE
Issues with ODR violations and leaks when running ASAN on Fedora 32 in CI

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#6765]
To get the build to pass we have to run with:
export ASAN_OPTIONS="detect_leaks=0 detect_odr_violation=1"

**Comment by bryancall** [comment]
```
=================================================================
==95550==ERROR: AddressSanitizer: odr-violation (0x7ff12cadd420):
  [1] size=88 'debugObject' unit-tests/plugin_testing_calls.cc:37:19
  [2] size=88 'debugObject' unit-tests/plugin_testing_calls.cc:37:19
These globals were registered at these points:
  [1]:
    #0 0x7ff1303ddcc8  (/lib64/libasan.so.6+0x37cc8)
    #1 0x7ff130d967e1 in call_init.part.0 (/lib64/ld-linux-x86-64.so.2+0x117e1)

  [2]:
    #0 0x7ff1303ddcc8  (/lib64/libasan.so.6+0x37cc8)
    #1 0x682d6c in __libc_csu_init (/home/bcall/dev/apache/trafficserver/proxy/http/remap/.libs/lt-test_RemapPluginInfo+0x682d6c)

==95550==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'debugObject' at unit-tests/plugin_testing_calls.cc:37:19
==95550==ABORTING
FAIL test_RemapPluginInfo (exit status: 1)
```

**Comment by bryancall** [comment]
```
Direct leak of 8640 byte(s) in 24 object(s) allocated from:
    #0 0x7fba376ce067 in operator new(unsigned long) (/lib64/libasan.so.6+0xb2067)
    #1 0x7edffd in Machine::instance() unit-tests/nexthop_test_stubs.cc:108
    #2 0x4a6fc7 in NextHopSelectionStrategy::Init(YAML::Node const&) /home/bcall/dev/apache/trafficserver/proxy/http/remap/NextHopSelectionStrategy.cc:149
    #3 0x4e350c in NextHopRoundRobin::Init(YAML::Node const&) /home/bcall/dev/apache/trafficserver/proxy/http/remap/NextHopRoundRobin.h:41
    #4 0x4e350c in NextHopStrategyFactory::createStrategy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, NHPolicyType, YAML::Node const&) /home/bcall/dev/apache/trafficserver/proxy/http/remap/NextHopStrategyFactory.cc:130
    #5 0x4f188a in NextHopStrategyFactory::NextHopStrategyFactory(char const*) /home/bcall/dev/apache/trafficserver/proxy/http/remap/NextHopStrategyFactory.cc:94
    #6 0x5f8c03 in ____C_A_T_C_H____T_E_S_T____0 unit-tests/test_NextHopStrategyFactory.cc:363
```

**Comment by bryancall** [comment]
```
=================================================================
==278773==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f281525d067 in operator new(unsigned long) (/lib64/libasan.so.6+0xb2067)
    #1 0x7e905a in br(HttpRequestData*, char const*, sockaddr const*) unit-tests/nexthop_test_stubs.cc:38
    #2 0x6b3f27 in ____C_A_T_C_H____T_E_S_T____7 unit-tests/test_NextHopConsistentHash.cc:274
    #3 0x67b3e8 in Catch::TestInvokerAsFunction::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:14036
    #4 0x679e27 in Catch::TestCase::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13929
    #5 0x66d286 in Catch::RunContext::invokeActiveTestCase() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12791
    #6 0x66cac8 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12764
    #7 0x66948e in Catch::RunContext::runTest(Catch::TestCase const&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12525
    #8 0x671205 in execute /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13119
    #9 0x673c00 in Catch::Session::runInternal() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13325
    #10 0x673579 in Catch::Session::run() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13281
    #11 0x70f30f in int Catch::Session::run<char>(int, char const* const*) (/home/bcall/dev/apache/trafficserver/proxy/http/remap/.libs/lt-test_NextHopConsistentHash+0x70f30f)
    #12 0x6a5877 in main /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:17164
    #13 0x7f2814863041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 21 byte(s) in 1 object(s) allocated from:
    #0 0x7f281525b667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x7f2814fdc396 in ats_malloc /home/bcall/dev/apache/trafficserver/src/tscore/ink_memory.cc:59
    #2 0x7f2814fdc9a2 in _xstrdup /home/bcall/dev/apache/trafficserver/src/tscore/ink_memory.cc:274
    #3 0x7e9163 in br(HttpRequestData*, char const*, sockaddr const*) unit-tests/nexthop_test_stubs.cc:40
    #4 0x6b9867 in ____C_A_T_C_H____T_E_S_T____14 unit-tests/test_NextHopConsistentHash.cc:334
    #5 0x67b3e8 in Catch::TestInvokerAsFunction::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:14036
    #6 0x679e27 in Catch::TestCase::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13929
    #7 0x66d286 in Catch::RunContext::invokeActiveTestCase() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12791
    #8 0x66cac8 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12764
    #9 0x66948e in Catch::RunContext::runTest(Catch::TestCase const&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12525
    #10 0x671205 in execute /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13119
    #11 0x673c00 in Catch::Session::runInternal() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13325
    #12 0x673579 in Catch::Session::run() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13281
    #13 0x70f30f in int Catch::Session::run<char>(int, char const* const*) (/home/bcall/dev/apache/trafficserver/proxy/http/remap/.libs/lt-test_NextHopConsistentHash+0x70f30f)
    #14 0x6a5877 in main /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:17164
    #15 0x7f2814863041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 11 byte(s) in 1 object(s) allocated from:
    #0 0x7f281525b667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x7f2814fdc396 in ats_malloc /home/bcall/dev/apache/trafficserver/src/tscore/ink_memory.cc:59
    #2 0x7f2814fdc9a2 in _xstrdup /home/bcall/dev/apache/trafficserver/src/tscore/ink_memory.cc:274
    #3 0x7e9163 in br(HttpRequestData*, char const*, sockaddr const*) unit-tests/nexthop_test_stubs.cc:40
    #4 0x6aa708 in ____C_A_T_C_H____T_E_S_T____0 unit-tests/test_NextHopConsistentHash.cc:142
    #5 0x67b3e8 in Catch::TestInvokerAsFunction::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:14036
    #6 0x679e27 in Catch::TestCase::invoke() const /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13929
    #7 0x66d286 in Catch::RunContext::invokeActiveTestCase() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12791
    #8 0x66cac8 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12764
    #9 0x66948e in Catch::RunContext::runTest(Catch::TestCase const&) /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:12525
    #10 0x671205 in execute /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13119
    #11 0x673c00 in Catch::Session::runInternal() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13325
    #12 0x673579 in Catch::Session::run() /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:13281
    #13 0x70f30f in int Catch::Session::run<char>(int, char const* const*) (/home/bcall/dev/apache/trafficserver/proxy/http/remap/.libs/lt-test_NextHopConsistentHash+0x70f30f)
    #14 0x6a5877 in main /home/bcall/dev/apache/trafficserver/tests/include/catch.hpp:17164
    #15 0x7f2814863041 in __libc_start_main (/lib64/libc.so.6+0x27041)
```
