### ISSUE TITLE
Assertion in HttpSM::main_handler

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#6776]
```
5    0x00002b7368bafb48 ink_abort(char const*, ...) + 0x10d
6    0x00002b7368ba7805 _ink_assert + 0x37
7    0x00000000007de9f9 HttpSM::kill_this() + 0x3c1
8    0x00000000007ae2ae HttpSM::main_handler(int, void*) + 0x900
9    0x000000000065aea4 Continuation::handleEvent(int, void*) + 0x19e
10   0x0000000000d2d88e read_signal_and_update(int, UnixNetVConnection*) + 0x145
11   0x0000000000d2e1ba read_signal_done(int, NetHandler*, UnixNetVConnection*) + 0x67
12   0x0000000000d35288 UnixNetVConnection::readSignalDone(int, NetHandler*) + 0x28
13   0x0000000000cbbd1a SSLNetVConnection::net_read_io(NetHandler*, EThread*) + 0x1a16
14   0x0000000000d158fe NetHandler::process_ready_list() + 0x1c4
15   0x0000000000d17215 NetHandler::waitForActivity(long) + 0x14e3
16   0x0000000000db25ce EThread::execute_regular() + 0xbba
17   0x0000000000db2e03 EThread::execute() + 0x2e9
18   0x0000000000daf486 spawn_thread_internal(void*) + 0xfd
19   0x00002b736a420ea5 start_thread + 0xc5
20   0x00002b736b1568dd clone + 0x6d
```

**Comment by randall** [comment]
```

**Comment by masaori335** [comment]
More details between [ 3  ] and [ 4  ] on randall's backtrace
```
(gdb) bt
...
#4  0x00005630e9de78b3 in cleanup_entry (this=<optimized out>, e=<optimized out>) at HttpSM.cc:232
#5  HttpVCTable::cleanup_all (this=0x7ffaeb92bfc0) at HttpSM.cc:243
#6  0x00005630e9deb2f0 in HttpSM::kill_this (this=0x7ffaeb92ac00) at HttpSM.cc:6863
...
(gdb) frame 4
#4  0x00005630e9de78b3 in cleanup_entry (this=<optimized out>, e=<optimized out>) at HttpSM.cc:232
232         e->vc->do_io_close();
```

It looks like the HttpSM is trying call `do_io_close()` of invalid `vc`. Below is the vc on frame 5.
```
(gdb) p *vc_table[1].vc
$5 = {Continuation = {force_VFPT_to_top = {_vptr$force_VFPT_to_top = 0x7ffb81d5a070}, handler = NULL, mutex = {m_ptr = 0x0}, link = {SLink<Continuation> = {next = 0x0}, prev = 0x0}, control_flags = {raw_flags = 0}, thread_affinity = 0x0}, lerrno = 0}
```

The `HttpSM::cleanup_entry()` has nullptr check of `vc`, so we forget to set it nullptr at somewhere when HttpSM close/remove the vc entry?
