### ISSUE TITLE
Crash on canceling inactive_event of Http2Stream (8.1.x)

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#6833]
Separate a crash from #6825 for clarification. We faced this crash with 8.1.x.
```
(gdb) bt
#0  0x00007f70fd4d2199 in waitpid () from /lib64/libpthread.so.0
#1  0x000055f06daffe74 in crash_logger_invoke(int, siginfo_t*, void*) (signo=11, info=0x7f70f250aa70, ctx=0x7f70f250a940) at traffic_server/Crash.cc:165
#2  <signal handler called>
#3  0x00007f70d6a13a00 in ?? ()
#4  0x000055f06dbc791c in clear_inactive_timer (this=0x7f68464d68a0) at Http2Stream.cc:878
#5  clear_timers (this=0x7f68464d68a0) at Http2Stream.cc:895
#6  Http2Stream::initiating_close() (this=0x7f68464d68a0) at Http2Stream.cc:436
#7  0x000055f06dbbd972 in Http2ConnectionState::delete_stream(Http2Stream*) (this=0x7f49eab7d7d0, stream=0x7f68464d68a0) at Http2ConnectionState.cc:1371
#8  0x000055f06dbbea72 in Http2ConnectionState::send_data_frames(Http2Stream*) (this=0x7f49eab7d7d0, stream=0x7f68464d68a0) at Http2ConnectionState.cc:1580 (<- stream state: closed)
...
(gdb) frame 4
#4  0x000055f06dbc791c in clear_inactive_timer (this=0x7f68464d68a0) at Http2Stream.cc:878
878         inactive_event->cancel();
```

I thought this crash could be fixed by setting `nullptr` like #6825 change for other events. But the approach doesn't work. Because `inactive_event` is scheduled by `schedule_every()`, we need to keep the pointer until shutdown.

An odd thing is the mutex of the event is nullptr.
```
(gdb) p *this->inactive_event
$6 = {<Action> = {_vptr$Action = 0x7f703b54c4e0, continuation = 0x7f68464d68a0, mutex = {m_ptr = 0x0}, cancelled = 0}, ethread = 0x7f70f720d140, in_the_prot_queue = 0, in_the_priority_queue = 0, immediate = 0, globally_allocated = 1, in_heap = 8, callback_event = 2, timeout_at = 1589859874690562444, period = 1000000000, cookie = 0x0, link = {<SLink<Event>> = {next = 0x0}, prev = 0x0}}
```

**Comment by masaori335** [comment]
We haven't seen this crash last 3 months. Some recent changes after May might fix. Please reopen if anybody faces this crash on 8.1.x.
