### ISSUE TITLE
Intermittent failure on autest (tls_verify_base)

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#6840]
```
Test: tls_verify_base: Failed
    File: tls_verify_base.test.py
    Directory: /var/jenkins/workspace/autest-github/src/tests/gold_tests/tls
   Starting Test tls_verify_base : No issues found - Passed
      Reason: Started!
   Process: ts: Passed
   Process: server_foo: Failed
     Setting up : MakeDir - Passed
     Test : Checking that any test passes - Failed
        Reason: None of the tests passed
     
       Test : Checking that ReturnCode == None - Failed
          Reason: Returned Value 1 != None
       
     
       Test : Checking that ReturnCode == 0 - Failed
          Reason: Returned Value 1 != 0
       
   Process: server_bar: Passed
   Process: server: Passed
   Process: Default: Skipped
      Reason: Was not started
   Process: Default: Skipped
      Reason: Was not started
   Run: Permissive-Test: Failed
     Setting up : Copy - Passed
     Setting up : Copy - Passed
     Setting up : Copy - Passed
     Setting up : Copy - Passed
     Starting TestRun 0-tr : Exception was caught! - Failed
        Reason: Traceback (most recent call last):
           File "/usr/local/lib/python3.6/site-packages/autest/core/order.py", line 157, in _isReady
             return self.__ready(*lst, **kw)
         TypeError: <lambda>() got an unexpected keyword argument 'process'
         
         During handling of the above exception, another exception occurred:
         
         Traceback (most recent call last):
           File "/usr/local/lib/python3.6/site-packages/autest/testers/lambda_tester.py", line 23, in test
             result, desc, message = self.Value(eventinfo,self)
           File "/usr/local/lib/python3.6/site-packages/autest/runlogic/testrun.py", line 50, in doStart
             tmp = self.StartOrderedItemsAync(proc_list, Process_RunLogic)
           File "/usr/local/lib/python3.6/site-packages/autest/runlogic/runlogic.py", line 159, in StartOrderedItemsAync
             isReady = self.isReady(ready_item, hasRunFor)
           File "/usr/local/lib/python3.6/site-packages/autest/runlogic/runlogic.py", line 69, in isReady
             isObjReady = obj._isReady(process=obj, hasRunFor=hasrunfor, **args)
           File "/usr/local/lib/python3.6/site-packages/autest/core/order.py", line 159, in _isReady
             return self.__ready()
           File "/usr/local/lib/python3.6/site-packages/autest/api/when.py", line 13, in <lambda>
             return func(*lst, **kw) if generator else lambda: func(*lst, **kw)
           File "/var/jenkins/workspace/autest-github/src/tests/gold_tests/autest-site/microserver.test.ext", line 133, in uServerUpAndRunning
             sock.connect((serverHost, port))
           File "/usr/lib64/python3.6/ssl.py", line 1065, in connect
             self._real_connect(addr, False)
           File "/usr/lib64/python3.6/ssl.py", line 1056, in _real_connect
             self.do_handshake()
           File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
             self._sslobj.do_handshake()
           File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
             self._sslobj.do_handshake()
         ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)
     Process: Default: Skipped
        Reason: Was not started
     Process: Default: Skipped
        Reason: Was not started
   Run: Permissive-Test with logged failure: Skipped
      Reason: Test run 0-tr failed
   Run: Override-enforcing-Test: Skipped
      Reason: Test run 0-tr failed
   Run: Override-enforcing-Test-fail-name-check: Skipped
      Reason: Test run 0-tr failed
```

**Comment by shinrich** [comment]
I see this one with fair frequency as well.  It sounds like something is talking non-TLS on the port and the port probing logic is having none of it.  

@dragon512 any idea of how we could go able debugging this?

**Comment by ywkaras** [comment]
Ran this 500 time in my environment and saw no failures.

**Comment by bneradt** [comment]
Thanks Walt. Closing this issue since the referenced changes address the problem.

**Comment by ywkaras** [comment]
What is blocking you from closing it?

**Comment by bneradt** [comment]
> What is blocking you from closing it?

I pushed the wrong button (just commented rather than closing with a comment). Thanks for noticing the issue wasn't closed.
