### ISSUE TITLE
Intermittent failure on AuTest (tls_verify3)

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#6842]
https://ci.trafficserver.apache.org/job/autest-github/13374/console
```
 Test: tls_verify3: Failed
    File: tls_verify3.test.py
    Directory: /var/jenkins/workspace/autest-github/src/tests/gold_tests/tls
   Starting Test tls_verify3 : No issues found - Passed
      Reason: Started!
   Process: ts: Failed
     Setting up : MakeDir - Passed
     Setting up : Copy - Passed
     Setting up : MakeDir - Passed
     Setting up : Chown - Passed
     Setting up : Chown - Passed
     Setting up : CopyAs - Passed
     Setting up : CopyAs - Passed
     Setting up : CopyAs - Passed
     Setting up : Copy - Passed
     Setting up : MakeDir - Passed
     Setting up : Copy - Passed
     Setting up : MakeDir - Passed
     Setting up : Chown - Passed
     Setting up : Chown - Passed
     Setting up : MakeDir - Passed
     Setting up : Chown - Passed
     Setting up : Chown - Passed
     Setting up : MakeDir - Passed
     Setting up : MakeDir - Passed
     Setting up : Chown - Passed
     Setting up : Chown - Passed
     Setting up : MakeDir - Passed
     Setting up : Chown - Passed
     Setting up : Chown - Passed
     Setting up : CopyAs - Passed
     Setting up : CopyAs - Passed
     Setting up : CopyAs - Passed
     Setting up : CopyAs - Passed
     Setting up : CopyAs - Passed
     Setting up : CopyAs - Passed
     Setting up : CopyAs - Passed
     Setting up : CopyAs - Passed
     Test : Checking that ReturnCode == 0 - Passed
        Reason: Returned Value: 0 == 0
     file /var/tmp/ausb-6841.13374/tls_verify3/ts/log/diags.log : Make sure bob.bar name checked failed. - Failed
        Reason: Contents of /var/tmp/ausb-6841.13374/tls_verify3/ts/log/diags.log did not contains expression: "WARNING: SNI \(bob.bar.com\) not in certificate"
     file /var/tmp/ausb-6841.13374/tls_verify3/ts/log/diags.log : Make sure default permissive action takes - Failed
        Reason: Contents of /var/tmp/ausb-6841.13374/tls_verify3/ts/log/diags.log did not contains expression: "WARNING: Core server certificate verification failed for \(my.foo.com\). Action=Continue"
     Appending File /var/tmp/ausb-6841.13374/tls_verify3/ts/config/records.config : Writing config file records.config - Passed
        Reason: Success
     Appending File /var/tmp/ausb-6841.13374/tls_verify3/ts/config/remap.config : Appended file /var/tmp/ausb-6841.13374/tls_verify3/ts/config/remap.config - Passed
        Reason: Success
     Appending File /var/tmp/ausb-6841.13374/tls_verify3/ts/config/ssl_multicert.config : Appended file /var/tmp/ausb-6841.13374/tls_verify3/ts/config/ssl_multicert.config - Passed
        Reason: Success
     Appending File /var/tmp/ausb-6841.13374/tls_verify3/ts/config/sni.yaml : Appended file /var/tmp/ausb-6841.13374/tls_verify3/ts/config/sni.yaml - Passed
        Reason: Success
   Process: server_foo: Failed
     Setting up : MakeDir - Passed
     Test : Checking that any test passes - Failed
        Reason: None of the tests passed
     
       Test : Checking that ReturnCode == None - Failed
          Reason: Returned Value 1 != None
       
     
       Test : Checking that ReturnCode == 0 - Failed
          Reason: Returned Value 1 != 0
       
   Process: server_bar: Passed
   Process: server: Passed
   Process: Default: Skipped
      Reason: Was not started
   Process: Default: Skipped
      Reason: Was not started
   Run: foo.com Permissive-Test: Failed
     Setting up : Copy - Passed
     Setting up : Copy - Passed
     Setting up : Copy - Passed
     Setting up : Copy - Passed
     Starting TestRun 0-tr : Exception was caught! - Failed
        Reason: Traceback (most recent call last):
           File "/usr/local/lib/python3.6/site-packages/autest/core/order.py", line 157, in _isReady
             return self.__ready(*lst, **kw)
         TypeError: <lambda>() got an unexpected keyword argument 'process'
         
         During handling of the above exception, another exception occurred:
         
         Traceback (most recent call last):
           File "/usr/local/lib/python3.6/site-packages/autest/testers/lambda_tester.py", line 23, in test
             result, desc, message = self.Value(eventinfo,self)
           File "/usr/local/lib/python3.6/site-packages/autest/runlogic/testrun.py", line 50, in doStart
             tmp = self.StartOrderedItemsAync(proc_list, Process_RunLogic)
           File "/usr/local/lib/python3.6/site-packages/autest/runlogic/runlogic.py", line 159, in StartOrderedItemsAync
             isReady = self.isReady(ready_item, hasRunFor)
           File "/usr/local/lib/python3.6/site-packages/autest/runlogic/runlogic.py", line 69, in isReady
             isObjReady = obj._isReady(process=obj, hasRunFor=hasrunfor, **args)
           File "/usr/local/lib/python3.6/site-packages/autest/core/order.py", line 159, in _isReady
             return self.__ready()
           File "/usr/local/lib/python3.6/site-packages/autest/api/when.py", line 13, in <lambda>
             return func(*lst, **kw) if generator else lambda: func(*lst, **kw)
           File "/var/jenkins/workspace/autest-github/src/tests/gold_tests/autest-site/microserver.test.ext", line 133, in uServerUpAndRunning
             sock.connect((serverHost, port))
           File "/usr/lib64/python3.6/ssl.py", line 1065, in connect
             self._real_connect(addr, False)
           File "/usr/lib64/python3.6/ssl.py", line 1056, in _real_connect
             self.do_handshake()
           File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
             self._sslobj.do_handshake()
           File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
             self._sslobj.do_handshake()
         ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:877)
     Process: Default: Skipped
        Reason: Was not started
     Process: Default: Skipped
        Reason: Was not started
   Run: my.foo.com Permissive-Test log failure: Skipped
      Reason: Test run 0-tr failed
   Run: bob.bar.com Override-enforcing-Test: Skipped
      Reason: Test run 0-tr failed
   Run: bob.foo.com override-enforcing-name-test: Skipped
      Reason: Test run 0-tr failed
   Run: random.bar.com override-no-test: Skipped
      Reason: Test run 0-tr failed
```

https://ci.trafficserver.apache.org/autest/ausb-6841.13374/tls_verify3/_output/tls_verify3-server_foo/stream.all.txt
```
size 2
Dropped 0 sessions for being malformed
Traceback (most recent call last):
  File "/usr/local/bin/microserver", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/microserver/__main__.py", line 130, in main
    clientVerify=args.clientverify, hooks=args.load, lookupKey=args.lookupkey, both=args.both, verbose=args.verbose, clientCA=args.clientCA)
  File "/usr/local/lib/python3.6/site-packages/microserver/microserver.py", line 128, in __init__
    ip), s_port), MyHandler, sslKey, sslCert, clientCA, hooks=hooks, clientverify=clientVerify))
  File "/usr/local/lib/python3.6/site-packages/microserver/servers.py", line 75, in __init__
    self.server_bind()
  File "/usr/lib64/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by bryancall** [comment]
Not failing anymore.
