### ISSUE TITLE
Crash in HttpSM

### ISSUE THREAD

**Issue by sudheerv** [apache/trafficserver#6863]
This could be another symptom of the same root cause as https://github.com/apache/trafficserver/issues/6859

```
#0  0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000550778 in HttpSM::main_handler (this=0x2b228a84ea00, event=2, data=0x2b2243d42960) at HttpSM.cc:2729
#2  0x00000000007bb7c0 in handleEvent (data=0x2b2243d42960, event=2, this=0x2b228a84ea00) at I_Continuation.h:193
#3  EThread::process_event (this=this@entry=0x2b2169806000, e=e@entry=0x2b2243d42960, calling_code=2) at UnixEThread.cc:127
#4  0x00000000007bc834 in EThread::execute_regular (this=this@entry=0x2b2169806000) at UnixEThread.cc:236
#5  0x00000000007bcc62 in EThread::execute (this=0x2b2169806000) at UnixEThread.cc:327
#6  0x00000000007bafe9 in spawn_thread_internal (a=0x2b21659650c0) at Thread.cc:92
#7  0x00002b2163731dd5 in start_thread () from /lib64/libpthread.so.0
#8  0x00002b21644e2ead in clone () from /lib64/libc.so.6
(gdb) f 1
#1  0x0000000000550778 in HttpSM::main_handler (this=0x2b228a84ea00, event=2, data=0x2b2243d42960) at HttpSM.cc:2729
2729	HttpSM.cc: No such file or directory.
(gdb) p this->magic
$1 = 65261
(gdb) p (int)0xFEED
$2 = 65261
(gdb) p this->default_handler
$3 = (int (HttpSM::*)(HttpSM * const, int, void *)) 0x539ad0 <HttpSM::tunnel_handler(int, void*)>
```

**Comment by sudheerv** [comment]
Reverting PR 4028 seems to have fixed this,

**Comment by sudheerv** [comment]
https://github.com/apache/trafficserver/pull/6889 fixes this.
