### ISSUE TITLE
Crash in h2

### ISSUE THREAD

**Issue by duke8253** [apache/trafficserver#7411]
Was testing something else with h2load, and randomly got this, h2load command is `/h2load --warm-up-time=10 -D 20 -c 4 -t 4 -m 4 https://127.0.0.1:9090/0`, running latest master branch:
```
(gdb) bt
#0  MIMEField::name_get (this=this@entry=0x0) at ../../../proxy/hdrs/MIME.cc:1756
#1  0x00005575cea64f68 in MIMEField::name_get (length=<synthetic pointer>, this=0x0) at /home/duke/Git/duke-ats/_build/../proxy/hdrs/MIME.h:812
#2  HpackIndexingTable::get_header_field (field=..., index=<optimized out>, this=<optimized out>) at ../../../proxy/http2/HPACK.cc:309
#3  HpackIndexingTable::get_header_field (this=<optimized out>, index=<optimized out>, field=...) at ../../../proxy/http2/HPACK.cc:293
#4  0x00005575cea65d6b in decode_indexed_header_field (header=..., buf_start=<optimized out>, buf_end=<optimized out>, indexing_table=...)
    at ../../../proxy/http2/HPACK.cc:705
#5  0x00005575cea67167 in hpack_decode_header_block (indexing_table=..., hdr=hdr@entry=0x7f68857c7d90, in_buf=0x7f688579b020 "\004\002/0\207\277\202\276", 
    in_buf_len=<optimized out>, max_header_size=131072, maximum_table_size=maximum_table_size@entry=4096) at ../../../proxy/http2/HPACK.cc:868
#6  0x00005575cea42dff in http2_decode_header_blocks (hdr=hdr@entry=0x7f68857c7d90, buf_start=<optimized out>, buf_len=<optimized out>, len_read=len_read@entry=0x0, 
    handle=..., trailing_header=@0x7f68857c87b0: false, maximum_table_size=4096) at ../../../proxy/http2/HTTP2.cc:688
#7  0x00005575cea5a345 in Http2Stream::decode_header_blocks (this=this@entry=0x7f68857c7c00, hpack_handle=..., maximum_table_size=<optimized out>)
    at ../../../proxy/http2/Http2Stream.cc:151
#8  0x00005575cea56a88 in rcv_headers_frame (cstate=..., frame=...) at ../../../proxy/http2/Http2ConnectionState.h:106
#9  0x00005575cea54ac6 in Http2ConnectionState::main_event_handler (this=0x7f68857c6308, event=<optimized out>, edata=0x7f689c00fe20)
    at ../../../proxy/http2/Http2ConnectionState.cc:1064
#10 0x00005575cea4902f in Continuation::handleEvent (data=0x7f689c00fe20, event=2253, this=0x7f68857c6308)
    at /home/duke/Git/duke-ats/_build/../iocore/eventsystem/I_Continuation.h:219
#11 Continuation::handleEvent (data=0x7f689c00fe20, event=2253, this=0x7f68857c6308) at /home/duke/Git/duke-ats/_build/../iocore/eventsystem/I_Continuation.h:215
#12 send_connection_event (cont=0x7f68857c6308, event=2253, edata=0x7f689c00fe20) at ../../../proxy/http2/Http2ClientSession.cc:65
#13 0x00005575cea49ae1 in Http2ClientSession::do_complete_frame_read (this=this@entry=0x7f68857c6000) at ../../../proxy/http2/Http2ClientSession.cc:529
#14 0x00005575cea4a55b in Http2ClientSession::state_process_frame_read (this=0x7f68857c6000, event=<optimized out>, vio=0x7f68859d6ae0, inside_frame=<optimized out>)
    at ../../../proxy/http2/Http2ClientSession.cc:587
#15 0x00005575cea4a79d in Http2ClientSession::state_start_frame_read (this=0x7f68857c6000, event=100, edata=0x7f68859d6ae0)
    at ../../../proxy/http2/Http2ClientSession.cc:443
#16 0x00005575cea492ec in Http2ClientSession::main_event_handler (this=0x7f68857c6000, event=100, edata=0x7f68859d6ae0)
    at ../../../proxy/http2/Http2ClientSession.cc:313
#17 0x00005575cea4571e in Continuation::handleEvent (data=0x7f68859d6ae0, event=100, this=0x7f68857c6000)
    at /home/duke/Git/duke-ats/_build/../iocore/eventsystem/I_Continuation.h:219
#18 Continuation::handleEvent (data=0x7f68859d6ae0, event=100, this=0x7f68857c6000) at /home/duke/Git/duke-ats/_build/../iocore/eventsystem/I_Continuation.h:215
#19 Http2ClientSession::state_read_connection_preface (this=0x7f68857c6000, event=<optimized out>, edata=0x7f68859d6ae0)
    at ../../../proxy/http2/Http2ClientSession.cc:423
#20 0x00005575cea492ec in Http2ClientSession::main_event_handler (this=0x7f68857c6000, event=100, edata=0x7f68859d6ae0)
    at ../../../proxy/http2/Http2ClientSession.cc:313
#21 0x00005575cebecead in Continuation::handleEvent (data=0x7f68859d6ae0, event=100, this=0x7f68857c6000)
    at /home/duke/Git/duke-ats/_build/../iocore/eventsystem/I_Continuation.h:219
#22 Continuation::handleEvent (data=0x7f68859d6ae0, event=100, this=0x7f68857c6000) at /home/duke/Git/duke-ats/_build/../iocore/eventsystem/I_Continuation.h:215
#23 read_signal_and_update (vc=0x7f68859d6900, event=100) at ../../../iocore/net/UnixNetVConnection.cc:83
#24 UnixNetVConnection::readSignalAndUpdate (this=this@entry=0x7f68859d6900, event=event@entry=100) at ../../../iocore/net/UnixNetVConnection.cc:1030
#25 0x00005575cebbacb2 in SSLNetVConnection::net_read_io (this=<optimized out>, nh=0x7f68a4f85b40, lthread=0x7f68a4f81ac0)
    at ../../../iocore/net/SSLNetVConnection.cc:671
#26 0x00005575cebdd5b6 in NetHandler::process_ready_list (this=this@entry=0x7f68a4f85b40) at ../../../iocore/net/UnixNet.cc:415
#27 0x00005575cebdda73 in NetHandler::waitForActivity (this=0x7f68a4f85b40, timeout=<optimized out>) at ../../../iocore/net/UnixNet.cc:549
#28 0x00005575cec3a3a2 in EThread::execute_regular (this=0x7f68a4f81ac0) at /home/duke/Git/duke-ats/_build/../include/tscore/ink_atomic.h:76
#29 0x00005575cec3ab2e in EThread::execute (this=0x7f68a4f81ac0) at ../../../iocore/eventsystem/UnixEThread.cc:364
#30 EThread::execute (this=0x7f68a4f81ac0) at ../../../iocore/eventsystem/UnixEThread.cc:342
#31 0x00005575cec383ca in spawn_thread_internal (a=0x7f68a9901ac0) at ../../../iocore/eventsystem/Thread.cc:92
#32 0x00007f68aa2db609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#33 0x00007f68a9eaf293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by duke8253** [comment]
Tried a few different configurations, can't recreate this crash anymore. Closing the issue for now, will reinvestigate if it pops up again.
