### ISSUE TITLE
h2spec.test.py has become flakey

### ISSUE THREAD

**Issue by bneradt** [apache/trafficserver#7915]
I've noticed that CI has started having intermittent failures with the h2spec.test.py test. I reproduced it locally, running the test 20 times, and noticing that it would fail consistently within a few runs. I did a git bisect and here's the results:

```
$ git bisect run /var/tmp/build_and_run_h2spec_test.sh
running /var/tmp/build_and_run_h2spec_test.sh
building: f80ed7354 (HEAD) Do not delete the continuation twice (#7862)
    tests failed for: f80ed7354 (HEAD) Do not delete the continuation twice (#7862)
Bisecting: 5 revisions left to test after this (roughly 3 steps)
[a0c267cdc88586679ccba4ec3e394f386d52f806] Add URI Signing cdnistd Claim Implementation (#7822)
running /var/tmp/build_and_run_h2spec_test.sh
building: a0c267cdc (HEAD) Add URI Signing cdnistd Claim Implementation (#7822)
    tests failed for: a0c267cdc (HEAD) Add URI Signing cdnistd Claim Implementation (#7822)
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[19dfdd4753232d0b77ca555f7ef5f5ba3d2ccae1] Clean up lua plugin doc for overridable configurations (#7844)
running /var/tmp/build_and_run_h2spec_test.sh
building: 19dfdd475 (HEAD) Clean up lua plugin doc for overridable configurations (#7844)
    tests failed for: 19dfdd475 (HEAD) Clean up lua plugin doc for overridable configurations (#7844)
Bisecting: 0 revisions left to test after this (roughly 1 step)
[23174f43ba543c9f56916e5d6aadb7a22f349355] Save and propagate epoll network error (#7809)
running /var/tmp/build_and_run_h2spec_test.sh
building: 23174f43b (HEAD) Save and propagate epoll network error (#7809)
    tests failed for: 23174f43b (HEAD) Save and propagate epoll network error (#7809)
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[fbdbb5b733c389e537d777938298219be43e619e] Add method to write an IpAddr value to a sockaddr. (#7821)
running /var/tmp/build_and_run_h2spec_test.sh
building: fbdbb5b73 (HEAD) Add method to write an IpAddr value to a sockaddr. (#7821)
    tests passed for: fbdbb5b73 (HEAD) Add method to write an IpAddr value to a sockaddr. (#7821)
23174f43ba543c9f56916e5d6aadb7a22f349355 is the first bad commit
commit 23174f43ba543c9f56916e5d6aadb7a22f349355
Author: Susan Hinrichs <shinrich@verizonmedia.com>
Date:   Mon May 17 19:23:48 2021 -0500

    Save and propagate epoll network error (#7809)

 iocore/net/NetEvent.h            | 17 +++++++++++++++++
 iocore/net/UnixNet.cc            | 19 ++++++++-----------
 iocore/net/UnixNetVConnection.cc | 12 ++++++++++++
 3 files changed, 37 insertions(+), 11 deletions(-)
bisect run success

```

Those results seem to indicate that this PR has made the h2spec test to pass inconsistently:
https://github.com/apache/trafficserver/pull/7809

For those trying to reproduce these results:

* Docker image: `controller.trafficserver.org/ats/centos:8`
* `./configure --prefix /var/tmp/build --with-openssl=/opt/openssl-quic --enable-experimental-plugins --enable-example-plugins --enable-werror --enable-debug --enable-wccp`
* `./autest.sh --sandbox /tmp/sb_master --ats-bin /var/tmp/build/bin/ --clean=none  -f h2spec`

**Comment by masaori335** [comment]
I got repro on my mac (intermittent failure of 2/5, 3.9/2, and 3.10/2).

**Comment by masaori335** [comment]
It looks like `http2/4.2/1` hangs intermittently.
<details><summary>Debug logs</summary>

```
[Jun  3 06:14:04.940] [ET_NET 0] DEBUG: <ALPNSupport.cc:105 (select_next_protocol)> (ssl) selected ALPN protocol h2
[Jun  3 06:14:04.940] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS read client hello
[Jun  3 06:14:04.940] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS write server hello
[Jun  3 06:14:04.940] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS write certificate
[Jun  3 06:14:04.941] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS write key exchange
[Jun  3 06:14:04.941] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS write server done
[Jun  3 06:14:04.941] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8194, ret: -1, State: SSLv3/TLS write server done
[Jun  3 06:14:04.941] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:1297 (sslServerHandShakeEvent)> (ssl-diag) SSL handshake error: SSL_ERROR_WANT_READ (2), errno=0
[Jun  3 06:14:04.941] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:626 (net_read_io)> (ssl) ssl handshake for vc 0x7ffff0426800, took 0.000 seconds, configured handshake_timer: 30
[Jun  3 06:14:04.941] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:1227 (sslServerHandShakeEvent)> (ssl) Go on with the handshake state=7
[Jun  3 06:14:04.941] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS write server done
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS read client key exchange
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS read change cipher spec
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS read finished
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS write change cipher spec
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8193, ret: 1, State: SSLv3/TLS write finished
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLUtils.cc:210 (ssl_new_cached_session)> (ssl.session_cache.insert) ssl_new_cached_session session '45874F8E9DFE0544C6A6FE6D84B3E1C96B24A1D389EA9AA876A30D504E1E783C' and context 0xde7950
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLSessionCache.cc:110 (insertSession)> (ssl.session_cache.insert) SessionCache using bucket 18 (0xdde668): Inserting session '45874F8E9DFE0544C6A6FE6D84B3E1C96B24A1D389EA9AA876A30D504E1E783C' (hash: 4867EDCB9446BD12).
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLSessionCache.cc:147 (insertSession)> (ssl.session_cache) Inserting session '45874F8E9DFE0544C6A6FE6D84B3E1C96B24A1D389EA9AA876A30D504E1E783C' to bucket 0xdde668.
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 32, ret: 1, State: SSL negotiation finished successfully
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLUtils.cc:1074 (ssl_callback_info)> (ssl) ssl_callback_info ssl: 0x7fffec028f40, where: 8194, ret: 1, State: SSL negotiation finished successfully
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:1314 (sslServerHandShakeEvent)> (ssl) SSL server handshake completed successfully
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <TLSBasicSupport.cc:132 (_record_tls_handshake_end_time)> (ssl) ssl handshake time:1130199
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:1358 (sslServerHandShakeEvent)> (ssl) client selected next protocol 'h2'
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:650 (net_read_io)> (ssl) ssl handshake EVENT_DONE ntodo=0
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2SessionAccept.cc:53 (accept)> (http2_seq) [HttpSessionAccept2:mainEvent 0x7ffff0426800] accepted connection from 127.0.0.1:43010 transport type = 4
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ClientSession.cc:209 (new_connection)> (ssl_early_data) read_from_early_data = 0
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ClientSession.cc:212 (new_connection)> (http2_cs) [8] session born, netvc 0x7ffff0426800
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ConnectionState.cc:1959 (send_settings_frame)> (http2_con) [8] [0] Send SETTINGS frame
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ConnectionState.cc:1970 (send_settings_frame)> (http2_con) [8] [0]   MAX_CONCURRENT_STREAMS : 100
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ConnectionState.cc:1970 (send_settings_frame)> (http2_con) [8] [0]   MAX_HEADER_LIST_SIZE : 131072
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4096
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=0
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:308 (ssl_read_from_net)> (ssl.error) SSL_ERROR_WOULD_BLOCK(read)
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:719 (net_read_io)> (ssl) read finished - would block
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:780 (load_buffer_and_write)> (ssl) towrite=21
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:836 (load_buffer_and_write)> (ssl) try_to_write=21 written=21 total_written=21
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4096
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=24
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4072
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=15
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4057
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=9
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4048
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=0
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:308 (ssl_read_from_net)> (ssl.error) SSL_ERROR_WOULD_BLOCK(read)
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:349 (ssl_read_from_net)> (ssl) bytes_read=48
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ClientSession.cc:388 (state_read_connection_preface)> (http2_cs) [8] [&Http2ClientSession::state_read_connection_preface, VC_EVENT_READ_READY/TS_EVENT_VCONN_READ_READY]
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ClientSession.cc:409 (state_read_connection_preface)> (http2_cs) [8] received connection preface
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ClientSession.cc:438 (state_start_frame_read)> (http2_cs) [8] [&Http2ClientSession::state_start_frame_read, VC_EVENT_READ_READY/TS_EVENT_VCONN_READ_READY]
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ClientSession.cc:452 (do_start_frame_read)> (http2_cs) [8] receiving frame header
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ClientSession.cc:469 (do_start_frame_read)> (http2_cs) [8] frame header length=6, type=4, flags=0x0, streamid=0
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ConnectionState.cc:566 (rcv_settings_frame)> (http2_con) [8] [0] Received SETTINGS frame
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ConnectionState.cc:638 (rcv_settings_frame)> (http2_con) [8] [0]    INITIAL_WINDOW_SIZE : 65535
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ClientSession.cc:452 (do_start_frame_read)> (http2_cs) [8] receiving frame header
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ClientSession.cc:469 (do_start_frame_read)> (http2_cs) [8] frame header length=0, type=4, flags=0x1, streamid=0
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <Http2ConnectionState.cc:566 (rcv_settings_frame)> (http2_con) [8] [0] Received SETTINGS frame
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4048
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=0
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:308 (ssl_read_from_net)> (ssl.error) SSL_ERROR_WOULD_BLOCK(read)
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:719 (net_read_io)> (ssl) read finished - would block
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:780 (load_buffer_and_write)> (ssl) towrite=9
[Jun  3 06:14:04.942] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:836 (load_buffer_and_write)> (ssl) try_to_write=9 written=9 total_written=9
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4048
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=25
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4023
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=0
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:308 (ssl_read_from_net)> (ssl.error) SSL_ERROR_WOULD_BLOCK(read)
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:349 (ssl_read_from_net)> (ssl) bytes_read=25
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:438 (state_start_frame_read)> (http2_cs) [8] [&Http2ClientSession::state_start_frame_read, VC_EVENT_READ_READY/TS_EVENT_VCONN_READ_READY]
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:452 (do_start_frame_read)> (http2_cs) [8] receiving frame header
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:469 (do_start_frame_read)> (http2_cs) [8] frame header length=16, type=1, flags=0x4, streamid=1
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ConnectionState.cc:233 (rcv_headers_frame)> (http2_con) [8] [1] Received HEADERS frame
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2Stream.cc:370 (change_state)> (http2_stream) [8] [1] Http2StreamState::HTTP2_STREAM_STATE_OPEN
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4023
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=4023
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4096
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=1872
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=2224
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=2224
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:349 (ssl_read_from_net)> (ssl) bytes_read=8119
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:438 (state_start_frame_read)> (http2_cs) [8] [&Http2ClientSession::state_start_frame_read, VC_EVENT_READ_READY/TS_EVENT_VCONN_READ_READY]
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:452 (do_start_frame_read)> (http2_cs) [8] receiving frame header
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:469 (do_start_frame_read)> (http2_cs) [8] frame header length=16384, type=0, flags=0x1, streamid=1
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4096
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=4096
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:349 (ssl_read_from_net)> (ssl) bytes_read=4096
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:499 (state_complete_frame_read)> (http2_cs) [8] [&Http2ClientSession::state_complete_frame_read, VC_EVENT_READ_READY/TS_EVENT_VCONN_READ_READY]
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4096
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=754
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=3342
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=3342
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:349 (ssl_read_from_net)> (ssl) bytes_read=4096
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:499 (state_complete_frame_read)> (http2_cs) [8] [&Http2ClientSession::state_complete_frame_read, VC_EVENT_READ_READY/TS_EVENT_VCONN_READ_READY]
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4096
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=82
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4014
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=0
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:308 (ssl_read_from_net)> (ssl.error) SSL_ERROR_WOULD_BLOCK(read)
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:349 (ssl_read_from_net)> (ssl) bytes_read=82
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:499 (state_complete_frame_read)> (http2_cs) [8] [&Http2ClientSession::state_complete_frame_read, VC_EVENT_READ_READY/TS_EVENT_VCONN_READ_READY]
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ClientSession.cc:514 (state_complete_frame_read)> (http2_cs) [8] completed frame read, 16384 bytes available
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ConnectionState.cc:89 (rcv_data_frame)> (http2_con) [8] [1] Received DATA frame
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2Stream.cc:370 (change_state)> (http2_stream) [8] [1] Http2StreamState::HTTP2_STREAM_STATE_HALF_CLOSED_REMOTE
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <Http2ConnectionState.cc:176 (rcv_data_frame)> (http2_con) [8] [1] Received DATA frame: rwnd con=49151/65535 stream=49151/65535
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:282 (ssl_read_from_net)> (ssl) amount_to_read=4014
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:287 (ssl_read_from_net)> (ssl) nread=0
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:308 (ssl_read_from_net)> (ssl.error) SSL_ERROR_WOULD_BLOCK(read)
[Jun  3 06:14:04.943] [ET_NET 0] DEBUG: <SSLNetVConnection.cc:719 (net_read_io)> (ssl) read finished - would block
### got timeout after 10 seconds
```
</details>

**Comment by shinrich** [comment]
Weird.  Hitting proxy-requests after hooks 2 times seems very bad.

**Comment by masaori335** [comment]
After #7809, `read_from_net` raises `VC_EVENT_ERROR` when the origin server resets the connection after sending the response.

<details><summary>`VC_EVENT_ERROR` on `HttpSM::state_read_server_response_header`</summary>

```
(gdb) bt
#0  HttpSM::state_read_server_response_header (this=0x7ffff02a03b0, event=3, data=0x7fffec1552e8) at HttpSM.cc:1981
#1  0x0000000000594768 in HttpSM::main_handler (this=0x7ffff02a03b0, event=3, data=0x7fffec1552e8) at HttpSM.cc:2703
#2  0x00000000007e052e in read_signal_and_update (event=3, vc=0x7fffec155100) at UnixNetVConnection.cc:83
#3  0x00000000007e4f41 in UnixNetVConnection::readSignalAndUpdate (event=3, this=0x7fffec155100) at UnixNetVConnection.cc:1043
#4  read_from_net (nh=0x7ffff3845180, vc=0x7fffec155100, thread=0x7ffff3841010) at UnixNetVConnection.cc:204
#5  0x00000000007d1947 in NetHandler::process_ready_list (this=this@entry=0x7ffff3845180) at UnixNet.cc:415
#6  0x00000000007d1d13 in NetHandler::waitForActivity (this=0x7ffff3845180, timeout=<optimized out>) at UnixNet.cc:546
#7  0x00000000008271aa in EThread::execute_regular (this=this@entry=0x7ffff3841010) at I_PriorityEventQueue.h:115
#8  0x0000000000827412 in EThread::execute (this=0x7ffff3841010) at UnixEThread.cc:364
#9  EThread::execute (this=0x7ffff3841010) at UnixEThread.cc:342
#10 0x00000000008257ea in spawn_thread_internal (a=0xd5e7f0) at Thread.cc:92
#11 0x00007ffff68a614a in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff5aa4f23 in clone () from /lib64/libc.so.6
(gdb) frame 4
#4  read_from_net (nh=0x7ffff3845180, vc=0x7fffec155100, thread=0x7ffff3841010) at UnixNetVConnection.cc:204
204         vc->readSignalAndUpdate(VC_EVENT_ERROR);
(gdb) p vc->error
$1 = 104
```
</details>

<details><summary>tcpdump trafficserver <-> origin server</summary>

```
    1 2021-06-07 02:51:09.889582   0.000000 TCP    127.0.0.1 51260 127.0.0.1    61000 74 51260 → 61000 [SYN] Seq=0 Win=43690 Len=0 MSS=65495 SACK_PERM=1 TSval=1062468354 TSecr=0 WS=128
    2 2021-06-07 02:51:09.889596   0.000014 TCP    127.0.0.1 61000 127.0.0.1    51260 74 61000 → 51260 [SYN, ACK] Seq=0 Ack=1 Win=43690 Len=0 MSS=65495 SACK_PERM=1 TSval=1062468354 TSecr=1062468354 WS=128
    3 2021-06-07 02:51:09.889605   0.000023 TCP    127.0.0.1 51260 127.0.0.1    61000 66 51260 → 61000 [ACK] Seq=1 Ack=1 Win=43776 Len=0 TSval=1062468354 TSecr=1062468354
    4 2021-06-07 02:51:09.889839   0.000257 TCP    127.0.0.1 51260 127.0.0.1    61000 282 POST / HTTP/1.1  [TCP segment of a reassembled PDU]
    5 2021-06-07 02:51:09.889845   0.000263 TCP    127.0.0.1 61000 127.0.0.1    51260 66 61000 → 51260 [ACK] Seq=1 Ack=217 Win=44800 Len=0 TSval=1062468355 TSecr=1062468355
    6 2021-06-07 02:51:09.889993   0.000411 HTTP    127.0.0.1 51260 127.0.0.1    61000 16487 POST / HTTP/1.1
    7 2021-06-07 02:51:09.889999   0.000417 TCP    127.0.0.1 61000 127.0.0.1    51260 66 61000 → 51260 [ACK] Seq=1 Ack=16638 Win=175744 Len=0 TSval=1062468355 TSecr=1062468355
    8 2021-06-07 02:51:09.891157   0.001575 TCP    127.0.0.1 61000 127.0.0.1    51260 335 HTTP/1.1 405 METHOD NOT ALLOWED  [TCP segment of a reassembled PDU]
    9 2021-06-07 02:51:09.891169   0.001587 TCP    127.0.0.1 51260 127.0.0.1    61000 66 51260 → 61000 [ACK] Seq=16638 Ack=270 Win=44800 Len=0 TSval=1062468356 TSecr=1062468356
   10 2021-06-07 02:51:09.891184   0.001602 HTTP    127.0.0.1 61000 127.0.0.1    51260 244 HTTP/1.1 405 METHOD NOT ALLOWED  (text/html)
   11 2021-06-07 02:51:09.891189   0.001607 TCP    127.0.0.1 51260 127.0.0.1    61000 66 51260 → 61000 [ACK] Seq=16638 Ack=448 Win=45952 Len=0 TSval=1062468356 TSecr=1062468356
   12 2021-06-07 02:51:09.891231   0.001649 TCP    127.0.0.1 61000 127.0.0.1    51260 66 61000 → 51260 [RST, ACK] Seq=448 Ack=16638 Win=175744 Len=0 TSval=1062468356 TSecr=1062468356
```
</details>
