### ISSUE TITLE
9.1.0 and 9.1.x crashes with ts.http.skip_remapping_set(1) and dead origin

### ISSUE THREAD

**Issue by hnakamur** [apache/trafficserver#8318]
Here "dead origin" means no origin server process running at localhost:80.
The expected result is that trafficserver returns 502.

However it crashes at 9.1.0 https://github.com/apache/trafficserver/commit/682f899871b5af5252d1c1105bf998239a2a8eb8 and the current latest commit in 9.1.x https://github.com/apache/trafficserver/commit/b8c9267caaef5ea0a71ff44ba2abacb0e8e7d656.

The current master https://github.com/apache/trafficserver/commit/40843a975fb7f76da91e8c2f9287ce841232e38a works as expected.

Also the common ancestor of master and 9.1.x https://github.com/apache/trafficserver/commit/57a1854100bc515c7ae4c2fe772cb55c936ab2bf works as expected.

```
# git merge-base master 9.1.x
57a1854100bc515c7ae4c2fe772cb55c936ab2bf
```

I tried `git bisect` using the following script to build and test trafficserver.

`build-and-test.sh`
```
#!/bin/bash

build() {
  autoreconf -if
  ./configure
  make -j
  make install
}

stop_trafficserver() {
  pids="$(jobs -p)"
  [ -n "$pids" ] && kill $pids
}

run_test() {
  trap 'stop_trafficserver' exit
  cat <<'EOF' > /usr/local/etc/trafficserver/proxy.lua
function do_global_read_request()
    ts.http.skip_remapping_set(1)
    ts.client_request.set_url_scheme('http')
    ts.client_request.set_url_host('localhost')
    ts.client_request.set_url_port(80)
    return 0
end
EOF

  echo 'tslua.so /usr/local/etc/trafficserver/proxy.lua' > /usr/local/etc/trafficserver/plugin.config

  /usr/local/bin/traffic_server &
  sleep 2

  curl -v localhost:8080
}

build
run_test
```

```
git bisect start 682f899871b5af5252d1c1105bf998239a2a8eb8 57a1854100bc515c7ae4c2fe772cb55c936ab2bf
git bisect run /path/to/build-and-test.sh
```

The first bad commit reported by `git bisect` is
[Add dead server policy control and metric. Improve messages. (#8213) · apache/trafficserver@439ac46](https://github.com/apache/trafficserver/commit/439ac460f2f1bdcb24282a31c1bdebb249b694ce)

```
439ac460f2f1bdcb24282a31c1bdebb249b694ce is the first bad commit
commit 439ac460f2f1bdcb24282a31c1bdebb249b694ce
Author: Brian Neradt <brian.neradt@gmail.com>
Date:   Fri Aug 6 10:51:07 2021 -0500

    Add dead server policy control and metric. Improve messages. (#8213)
    
    (cherry picked from commit 01b91f348a919fa69ccd9727e39aae11bfca2a38)
    
    Co-authored-by: Susan Hinrichs <shinrich@verizonmedia.com>

 doc/admin-guide/files/records.config.en.rst        | 11 +++++-
 .../statistics/core/http-connection.en.rst         |  4 ++
 include/ts/apidefs.h.in                            |  1 +
 mgmt/RecordsConfig.cc                              |  2 +
 plugins/lua/ts_lua_http_config.c                   |  2 +
 proxy/http/HttpConfig.cc                           |  6 +++
 proxy/http/HttpConfig.h                            |  4 ++
 proxy/http/HttpSM.cc                               | 24 ++++++++++--
 proxy/http/HttpSM.h                                |  5 +++
 proxy/http/HttpTransact.cc                         | 45 ++++++++++++++++------
 src/shared/overridable_txn_vars.cc                 |  2 +
 src/traffic_server/InkAPI.cc                       |  3 ++
 src/traffic_server/InkAPITest.cc                   |  3 +-
 src/tscore/BufferWriterFormat.cc                   |  8 +++-
 14 files changed, 100 insertions(+), 20 deletions(-)
bisect run success
```

**Comment by bneradt** [comment]
Thank you @hnakamur . I've reproduced the issue locally on 9.1.x (b8c9267) and also verified that master (40843a975fb7f76da91e8c2f9287ce841232e38a and the latest commit which reverts incompatible changes 4208ecb8719add76aa46ab2005ff9424531e2e73) does not have the issue. I'll search for the commit on master that fixes the crash.

Re-running in gdb, here is more state information about the 9.1.x crash:

```
(gdb) bt
#0  0x00007fa09196337f in raise () from /lib64/libc.so.6
#1  0x00007fa09194ddb5 in abort () from /lib64/libc.so.6
#2  0x00007fa093e2d384 in ink_abort (message_format=0x7fa093e93ed0 "%s:%d: failed assertion `%s`") at ink_error.cc:99
#3  0x00007fa093e2a3b2 in _ink_assert (expression=0xb7247f "valid()", file=0xb72410 "/home/bneradt/src/ts_asf_master_fix_dead_origin_crash_on_91x/proxy/hdrs/URL.h", line=588) at ink_assert.cc:37
#4  0x00000000007c6501 in URL::host_get (this=0x7fa08ca22010, length=0x7fa08f4c32a4) at /home/bneradt/src/ts_asf_master_fix_dead_origin_crash_on_91x/proxy/hdrs/URL.h:588
#5  0x00000000008786f8 in HttpTransact::error_log_connection_failure (s=0x7fa08ca214b8, conn_state=HttpTransact::CONNECTION_ERROR) at HttpTransact.cc:3860
#6  0x0000000000878c29 in HttpTransact::retry_server_connection_not_open (s=0x7fa08ca214b8, conn_state=HttpTransact::CONNECTION_ERROR, max_retries=3) at HttpTransact.cc:3898
#7  0x0000000000877b12 in HttpTransact::handle_response_from_server (s=0x7fa08ca214b8) at HttpTransact.cc:3784
#8  0x000000000087627a in HttpTransact::HandleResponse (s=0x7fa08ca214b8) at HttpTransact.cc:3465
#9  0x000000000084d950 in HttpSM::call_transact_and_set_next_state (this=0x7fa08ca213b0, f=0x875ab4 <HttpTransact::HandleResponse(HttpTransact::State*)>) at HttpSM.cc:7391
#10 0x00000000008361df in HttpSM::state_http_server_open (this=0x7fa08ca213b0, event=3, data=0x7fa05001fa60) at HttpSM.cc:1957
#11 0x0000000000839c23 in HttpSM::main_handler (this=0x7fa08ca213b0, event=3, data=0x7fa05001fa60) at HttpSM.cc:2718
#12 0x000000000079dc57 in Continuation::handleEvent (this=0x7fa08ca213b0, event=3, data=0x7fa05001fa60) at /home/bneradt/src/ts_asf_master_fix_dead_origin_crash_on_91x/iocore/eventsystem/I_Continuation.h:219
#13 0x0000000000a7cd04 in write_signal_and_update (event=3, vc=0x7fa05001f800) at UnixNetVConnection.cc:117
#14 0x0000000000a7db4b in write_to_net_io (nh=0x7fa08f7e71a0, vc=0x7fa05001f800, thread=0x7fa08f7e3010) at UnixNetVConnection.cc:374
#15 0x0000000000a7da11 in write_to_net (nh=0x7fa08f7e71a0, vc=0x7fa05001f800, thread=0x7fa08f7e3010) at UnixNetVConnection.cc:356
#16 0x0000000000a7fcf9 in UnixNetVConnection::net_write_io (this=0x7fa05001f800, nh=0x7fa08f7e71a0, lthread=0x7fa08f7e3010) at UnixNetVConnection.cc:927
#17 0x0000000000a7374e in NetHandler::process_ready_list (this=0x7fa08f7e71a0) at UnixNet.cc:432
#18 0x0000000000a73cc3 in NetHandler::waitForActivity (this=0x7fa08f7e71a0, timeout=10000000) at UnixNet.cc:552
#19 0x0000000000ad7bb5 in EThread::execute_regular (this=0x7fa08f7e3010) at UnixEThread.cc:303
#20 0x0000000000ad7db7 in EThread::execute (this=0x7fa08f7e3010) at UnixEThread.cc:364
#21 0x0000000000ad66d0 in spawn_thread_internal (a=0x15a2f30) at Thread.cc:92
#22 0x00007fa09282c14a in start_thread () from /lib64/libpthread.so.0
#23 0x00007fa091a28dc3 in clone () from /lib64/libc.so.6
(gdb) f 4
#4  0x00000000007c6501 in URL::host_get (this=0x7fa08ca22010, length=0x7fa08f4c32a4) at /home/bneradt/src/ts_asf_master_fix_dead_origin_crash_on_91x/proxy/hdrs/URL.h:588
588       ink_assert(valid());
(gdb) l
583       -------------------------------------------------------------------------*/
584
585     inline const char *
586     URL::host_get(int *length)
587     {
588       ink_assert(valid());
589       *length = m_url_impl->m_len_host;
590       return m_url_impl->m_ptr_host;
591     }
```

**Comment by bneradt** [comment]
Found the fix:
https://github.com/apache/trafficserver/pull/8191

If I cherry-pick that commit locally on my local 9.1.x branch, the crash goes away. And the description makes sense that it would match this.

**Comment by bneradt** [comment]
Note that #8191 is marked for 9.2.x. It will be in the upcoming 9.2.0 release which we're planning to release soon.

**Comment by bneradt** [comment]
Thank you, @hnakamur, for documenting your reproduction steps well. It helped me find the commit that fixed this.
