### ISSUE TITLE
ASAN reports odr-violation in vtable for YAML::EmitFromEvents

### ISSUE THREAD

**Issue by moonchen** [apache/trafficserver#9516]
Master branch.  Built with clang-15.  Configured with `--prefix=/opt/ats  --enable-debug --enable-asan`

```=================================================================
==128097==ERROR: AddressSanitizer: odr-violation (0xffffb4c0bc60):
  [1] size=112 'vtable for YAML::EmitFromEvents' src/emitfromevents.cpp
  [2] size=112 'vtable for YAML::EmitFromEvents' src/emitfromevents.cpp
These globals were registered at these points:
  [1]:
    #0 0xaaaae2ecfe24 in __asan_register_globals (/opt/ats/bin/traffic_server+0x6bfe24) (BuildId: 75d3d2b4cd60af0195e734facbc41f2a8859b92e)
    #1 0xffffb4ad1540 in asan.module_ctor emitfromevents.cpp
    #2 0xffffb4c4e7c0  (/lib/ld-linux-aarch64.so.1+0x47c0) (BuildId: 7eafdbf8be0fa4793253d94204399db43301e5e5)
    #3 0xffffb4c4e8c0  (/lib/ld-linux-aarch64.so.1+0x48c0) (BuildId: 7eafdbf8be0fa4793253d94204399db43301e5e5)
    #4 0xffffb4c651b4  (/lib/ld-linux-aarch64.so.1+0x1b1b4) (BuildId: 7eafdbf8be0fa4793253d94204399db43301e5e5)

  [2]:
    #0 0xaaaae2ecfe24 in __asan_register_globals (/opt/ats/bin/traffic_server+0x6bfe24) (BuildId: 75d3d2b4cd60af0195e734facbc41f2a8859b92e)
    #1 0xffffb46e31d0 in asan.module_ctor emitfromevents.cpp
    #2 0xffffb4c4e7c0  (/lib/ld-linux-aarch64.so.1+0x47c0) (BuildId: 7eafdbf8be0fa4793253d94204399db43301e5e5)
    #3 0xffffb4c4e8c0  (/lib/ld-linux-aarch64.so.1+0x48c0) (BuildId: 7eafdbf8be0fa4793253d94204399db43301e5e5)
    #4 0xffffb4c651b4  (/lib/ld-linux-aarch64.so.1+0x1b1b4) (BuildId: 7eafdbf8be0fa4793253d94204399db43301e5e5)

==128097==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'vtable for YAML::EmitFromEvents' at src/emitfromevents.cpp
==128097==ABORTING```

**Comment by ywkaras** [comment]
It seems this is a know issue with LLVM:  https://github.com/google/sanitizers/issues/1017

**Comment by masaori335** [comment]
This is fixed by llvm-16.0.0. ( I don't see this with llvm-16.0.4 )

**Comment by bryancall** [comment]
This was a known LLVM bug ([google/sanitizers#1017](https://github.com/google/sanitizers/issues/1017)), fixed in LLVM 16.0.0 as confirmed by @masaori335. Closing.

If this is still an issue, please reopen or file a new issue with the specific compiler version.
