### ISSUE TITLE
Test run in Au test tls_tunnel causing exception in proxy_protocol_client.py

### ISSUE THREAD

**Issue by ywkaras** [apache/trafficserver#9550]
Specifically this test run:  https://github.com/apache/trafficserver/blob/96066eec2d4e4cc29c1665d8a9e484160932c0f3/tests/gold_tests/tls/tls_tunnel.test.py#L217

Causes this exception:
```
2023-03-22 02:41:41,351 - root - INFO - Sending PROXY protocol version 2
Traceback (most recent call last):
  File "/home/wkaras/REPOS/TS/tests/_sandbox/tls_tunnel/proxy_protocol_client.py", line 176, in <module>
    sys.exit(main())
  File "/home/wkaras/REPOS/TS/tests/_sandbox/tls_tunnel/proxy_protocol_client.py", line 165, in main
    with context.wrap_socket(sock, server_hostname=args.sni) as ssock:
  File "/opt/y/1.0/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/y/1.0/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/y/1.0/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)
```
Was this intended?

**Comment by ywkaras** [comment]
Still seeing this problem.

**Comment by masaori335** [comment]
Recently, I faced below error on PRB. Is this related?
```
Run: Proxy Protocol v2 without blind tunneling on TLS connection to origin: Failed
...
Process: Default: Failed
       Setting up : Copying '/home/jenkins/workspace/Github_Builds/autest/src/build/proxy-verifier-v2.10.1/linux-amd64' to '/tmp/sandbox/proxy_protocol/pp-out-client-5/bin' - Passed
       Setting up : Copying 'replay/proxy_protocol_out.replay.yaml' to '/tmp/sandbox/proxy_protocol/pp-out-client-5/proxy_protocol_out.replay.yaml' - Passed
       Setting up : Copying '/home/jenkins/workspace/Github_Builds/autest/src/tests/gold_tests/autest-site/../../tools/proxy-verifier/ssl/client.pem' to '/tmp/sandbox/proxy_protocol/pp-out-client-5/client.pem' - Passed
       Setting up : Copying '/home/jenkins/workspace/Github_Builds/autest/src/tests/gold_tests/autest-site/../../tools/proxy-verifier/ssl/ca.pem' to '/tmp/sandbox/proxy_protocol/pp-out-client-5/ca.pem' - Passed
       Test : Checking that ReturnCode == 0 - Failed
          Reason: Returned Value 1 != 0
       Time-Out : Process finishes within expected time - Passed
          Reason: Returned value: 5.022040843963623 < 600.0
       file /tmp/sandbox/proxy_protocol/_output/7-tr-Default/stream.all.txt : Verify the client got a 200 response. - Failed
          Reason: Contents of /tmp/sandbox/proxy_protocol/_output/7-tr-Default/stream.all.txt did not contains expression: "HTTP/1.1 200 OK"
       file /tmp/sandbox/proxy_protocol/_output/7-tr-Default/stream.stdout.txt : There should be no Proxy Verifier violation errors. - Passed
          Reason: Contents of /tmp/sandbox/proxy_protocol/_output/7-tr-Default/stream.stdout.txt excludes expression
```
