### ISSUE TITLE
H3 crash in Http3FrameFactory::fast_create

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#9887]
```
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 7954878057845441792, 0 <repeats 14 times>}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fed5da1b859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x1}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fed5e7d8ff1 in ink_abort (message_format=0x7fed5e846040 "%s:%d: failed assertion `%s`") at ink_error.cc:99
        ap = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fed5a36dce0, reg_save_area = 0x7fed5a36dc20}}
#3  0x00007fed5e7d3e9d in _ink_assert (expression=0x55d7196a4f0d "sizeof(buf) > frame_len", file=0x55d7196a4dec "Http3Frame.cc", line=458) at ink_assert.cc:37
No locals.
#4  0x000055d71958f06a in Http3FrameFactory::fast_create (this=0x7fed2c0dd0e0, reader=..., frame_len=984837) at Http3Frame.cc:458
        buf = "\300\000\000\004\232\221}\347\002\263\316\200\017\a\000\a\000u=0, i\200\017\a\000\004\004u=\002?1/\003AH\264\245I'ZB\241?\206\220䶒ԟ]\261\235)\255\027\030bC\221\v\246\301\313)\210\202\331ܶ.:\306Iʹ왋\vAF\202\255Q\322T1\342q\245\vT_\v\226\245\347M4\177\337_9\213-Kp\335\364Z\276\373@\005\337", '\000' <repeats 39761 times>...
#5  0x000055d719595071 in Http3FrameDispatcher::on_read_ready (this=0x7fed2c0dd0c0, stream_id=2, reader=..., nread=@0x7fed5a37de90: 31)
    at Http3FrameDispatcher.cc:93
        frame_len = 984837
        cloned_reader = 0x7fed2c0daa30
        type = Http3FrameType::UNKNOWN
        handlers = std::vector of length 0, capacity 0 = {<error reading variable handlers (Cannot access memory at address 0x4)>
        head = "0\200\017\a\000\004\bu=0\200\017\a\000\004\f"
        p = 0x7fed5a37de20 "@\336\067Z\355\177"
        read_len = 16
        frame = <error reading variable: Cannot access memory at address 0x7fed2fe018c8>
        error = std::unique_ptr<Http3Error> = {get() = 0x7fed2da00fa0}
        __FUNCTION__ = "on_read_ready"
#6  0x000055d71957f9e8 in Http3App::_handle_uni_stream_on_read_ready (this=0x7fed2c0dd020, vio=0x7fed2c0d2a30) at Http3App.cc:215
        nread = 31
        type = Http3StreamType::CONTROL
        adapter = 0x7fed2c0d29d0
        it = <error reading variable: Cannot access memory at address 0x7fecf86007b0>
        __FUNCTION__ = "_handle_uni_stream_on_read_ready"
#7  0x000055d71957f054 in Http3App::main_event_handler (this=0x7fed2c0dd020, event=100, data=0x7fed2c1ffc20) at Http3App.cc:136
        __FUNCTION__ = "main_event_handler"
        vio = 0x7fed2c0d2a30
        adapter = 0x7fed2c0d29d0
        is_bidirectional = false
#8  0x000055d719050477 in Continuation::handleEvent (this=0x7fed2c0dd020, event=100, data=0x7fed2c1ffc20)
    at /home/maskit/src/trafficserver/iocore/eventsystem/I_Continuation.h:228
No locals.
#9  0x000055d7195c4e65 in EThread::process_event (this=0x55d71bf27570, e=0x7fed2c1ffc20, calling_code=100) at UnixEThread.cc:149
        c_temp = 0x7fed2c0dd020
        lock = {m = {m_ptr = 0x7fed2c0cfdd0}, lock_acquired = true}
        __FUNCTION__ = "process_event"
```

**Comment by maskit** [comment]
This is probably the same as #https://github.com/apache/trafficserver/issues/9797
