### ISSUE TITLE
QUIC crash in QUICStreamAdapter::read

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#9888]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055acf1365928 in QUICStreamAdapter::read (this=0x98, len=50089) at QUICStreamAdapter.cc:29
29	  auto ret = this->_read(len);
[Current thread is 1 (Thread 0x7fdad77fb700 (LWP 2013395))]
#0  0x000055acf1365928 in QUICStreamAdapter::read (this=0x98, len=50089) at QUICStreamAdapter.cc:29
        ret = {m_ptr = 0x6c}
#1  0x000055acf1364dbf in QUICStreamImpl::send_data (this=0x7fdac4167990, quiche_con=0x7fda740b00a0) at QUICStream_quiche.cc:82
        fin = false
        len = 50089
        block = {m_ptr = 0x6c}
#2  0x000055acf12bc1c3 in QUICNetVConnection::_handle_write_ready (this=0x7fda740b4640) at QUICNetVConnection_quiche.cc:613
        stream = 0x7fdac4167990
        writable = 0x7fdac4167990
        s = 124
        udp_payload = {m_ptr = 0x55acf0e00d92 <ClassAllocator<ProxyMutex, false, FreelistAllocator>::free(ProxyMutex*)+58>}
        send_info = {from = {ss_family = 40512, __ss_padding = "\177\327\332\177\000\000\261\310\063\361\254U\000\000\300\000\000\000\000\000\000\000\320\004\r\304\332\177\000\000\016\226E\361\254U\000\000\000\000\000\000\000\000\000\000О\177\327\332\177\000\000\000\300{!.Ρ\312\300\a\000\305\332\177\000\000\260\213\340\027\332\177\000\000\240\236\177\327\332\177\000\000\250\342\022\363\254U\000\000/h\366\316\375\177\000\000О\177\327\332\177\000\000\000\237\177\327\332\177\000", __ss_align = 140578034264704}, from_len = 3289327456, to = {ss_family = 7056, __ss_padding = "\003\363\254U\000\000О\177\327\000\000\000\000\327\060\314\337\332\177\000\000О\177\327\332\177\000\000\240\213\340\027\332\177\000\000\001\000\000\000\000\000\000\000\216", '\000' <repeats 15 times>, "\200\237\177\327\332\177\000\000\240\213\340\027\001", '\000' <repeats 11 times>, " \237\177\327\332\177\000\000P\237\177\327\332\177\000\000\320\a\000\305\332\177\000\000@\237\177\327\332\177\000", __ss_align = 94201300837032}, to_len = 3472255023, at = {tv_sec = 140577895063344, tv_nsec = 94201263975113}}
        res = 140577569384848
        written = 140577568782800
        quantum = 94201269447165
        max_udp_payload_size = 140577895063072
#3  0x000055acf12ba4d8 in QUICNetVConnection::state_established (this=0x7fda740b4640, event=2501, data=0x7fdac50007c0) at QUICNetVConnection_quiche.cc:184
        __FUNCTION__ = "state_established"
#4  0x000055acf0e07477 in Continuation::handleEvent (this=0x7fda740b4640, event=2501, data=0x7fdac50007c0) at /home/maskit/src/trafficserver/iocore/eventsystem/I_Continuation.h:228
No locals.
#5  0x000055acf137be65 in EThread::process_event (this=0x55acf302d570, e=0x7fdac50007c0, calling_code=2501) at UnixEThread.cc:149
        c_temp = 0x7fda740b4640
        lock = {m = {m_ptr = 0x7fda1fe01f30}, lock_acquired = true}
        __FUNCTION__ = "process_event"

```

**Comment by duke8253** [comment]
Do you still remember how you produced this crash?

**Comment by maskit** [comment]
If Http3App is deleted where the QUICNetVC is still available, the adapter may not be already unavailable. Http3App should close all streams in the destructor.
